/*       Source:  Global Cache                                                                */
/*     Location:  js/feedcomment.js r119324                                                   */
/*      Machine:  10.16.139.107                                                               */
/*    Generated:  September 13th 2008 1:22:10 AM PDT                                          */
/*    HTTP Host:  static.ak.fbcdn.net                                                         */
/*       Locale:  nu_ll                                                                       */


function feedcomment_show_error(error_target,title,description){set_inner_html(error_target,'<h2>'+title+'</h2><p>'+description+'</p>');show(error_target);}
function feedcomment_submit(story_fbid,story_key,newsfeed,actor,target_fbid){var add_comment_form=ge('add_comment_'+story_fbid);var add_comment_textarea=ge('add_comment_text_'+story_fbid);var comment_button_id='submit_comment_'+story_fbid;var comment_button=ge(comment_button_id);var onResponse=function(asyncResponse){var result=asyncResponse.getPayload();var feed_comments=ge('feed_comments_'+story_fbid);var comment_count;if(typeof result.comment_count!='undefined'){comment_count=result.comment_count;}else{comment_count=feed_comments_get_count(story_fbid)+1;}
feed_comment_update_count(story_fbid,story_key,comment_count-1,comment_count,newsfeed);if(!Rect.getViewportBounds().contains(Rect.getElementBounds(comment_button))){var scroll_offset=-1*Math.max(getViewportHeight()/2,100);animation(document.body).to('scrollTop',Vector2.getElementPosition(comment_button).y+scroll_offset).ease(animation.ease.end).duration(1500).go();}
set_inner_html(feed_comments,result.all_comments_html);add_comment_textarea.value='';comment_button.disabled=false;hide(add_comment_form);show(ge('add_another_comment_'+story_fbid));}
var onTransportFail=function(response){feedcomment_show_error(add_comment_form,tx('wp02'),tx('wp03'));comment_button.disabled=false;};var onFail=function(response){comment_button.disabled=false;if(payload=response.getPayload()){if(payload.errTitle){feedcomment_show_error(add_comment_form,payload.errTitle,payload.errBody?payload.errBody:'');}else{onTransportFail(response);}}else{onTransportFail(response);}};var comment_text=trim(add_comment_textarea.value);if(!comment_text){animation(add_comment_textarea).to('background','#fff').from('#fcc').duration(140).go();}
if(comment_text&&add_comment_textarea.getControl&&add_comment_textarea.getControl().getValue()){comment_button.disabled=true;new AsyncRequest().setURI('/ajax/feed_wallpost_ajax.php').setData({'story_fbid':story_fbid,'story_key':story_key,'target_fbid':target_fbid,'actor':actor,'comment_text':comment_text,'newsfeed':newsfeed}).setHandler(onResponse).setErrorHandler(onFail).send();}
return status;}
function feed_comment_hide_add_box(story_fbid,story_key,newsfeed){if(ge('add_comment_text_'+story_fbid)&&!ge('add_comment_text_'+story_fbid).value){var story=feedcomments_get_story_div(story_fbid,story_key,newsfeed);var comments=$('feed_comments_'+story_fbid);if(DOM.scry(comments,'div','wallpost').length==0){CSS.addClass(story,'collapsed_comments');CSS.removeClass(story,'expanded_comments');if(CSS.hasClass(story,'story_ff')){CSS.addClass(story,'ff_collapsed_comments');CSS.removeClass(story,'ff_expanded_comments');}}
CSS.addClass(story,'hidden_add_button');}}
function feed_comment_show_add_box(story_fbid,story_key,newsfeed){var story=feedcomments_get_story_div(story_fbid,story_key,newsfeed);CSS.removeClass(story,'collapsed_comments');CSS.addClass(story,'expanded_comments');if(CSS.hasClass(story,'story_ff')){CSS.removeClass(story,'ff_collapsed_comments');CSS.addClass(story,'ff_expanded_comments');}
CSS.removeClass(story,'collapsed_add_box');if(ge('add_comment_text_'+story_fbid)){ge('add_comment_text_'+story_fbid).focus();}}
function feed_comment_show_add_button(story_fbid,story_key,newsfeed){var story=feedcomments_get_story_div(story_fbid,story_key,newsfeed);CSS.removeClass(story,'hidden_add_button');}
function feed_comment_update_count(story_fbid,story_key,old_count,new_count,newsfeed){var story=feedcomments_get_story_div(story_fbid,story_key,newsfeed);var comment_bubble=ge('comment_bubble_'+story_fbid);var comment_link=ge('comment_link_'+story_fbid);if(new_count==0){CSS.removeClass(story,'with_comments');CSS.addClass(story,'no_comments');if(comment_bubble){set_inner_html(comment_bubble,'');}
if(comment_link){set_inner_html(comment_link,tx('fc07'));}}else{if(comment_bubble){set_inner_html(comment_bubble,new_count.toString());}
if(new_count==1){if(comment_link){set_inner_html(comment_link,tx('fc08'));}
if(old_count==0){CSS.removeClass(story,'no_comments');CSS.addClass(story,'with_comments');}}else{if(comment_link){set_inner_html(comment_link,tx('fc09',{'num-comments':new_count}));}}}}
function feed_comments_get_count(story_fbid){var comments=ge('feed_comments_'+story_fbid);var count=0;if(comments){var comment_divs=comments.getElementsByTagName('div');for(var i=0;i<comment_divs.length;i++){if(CSS.hasClass(comment_divs[i],'wallpost')){count++;}}}
return count;}
function load_all_feed_comments(story_fbid,story_key,actor,target_fbid){var add_comment_form=ge('add_comment_'+story_fbid);var onResponse=function(asyncResponse){var result=asyncResponse.getPayload();var feed_comments=ge('feed_comments_'+story_fbid);set_inner_html(feed_comments,result.all_comments_html);};var onFail=function(response){if(payload=response.getPayload()){if(payload.errTitle){if(add_comment_form){feedcomment_show_error(add_comment_form,payload.errTitle,payload.errBody?payload.errBody:'');}}else{onTransportFail(response);}}else{onTransportFail(response);}};new AsyncRequest().setURI('/ajax/feed_wallpost_ajax.php').setData({'story_fbid':story_fbid,'story_key':story_key,'target_fbid':target_fbid,'get_all':1,'actor':actor}).setHandler(onResponse).setErrorHandler(onFail).send();}
function remove_feed_comment_dialog(story_fbid,story_key,comment_id,actor,newsfeed,target_fbid){var add_comment_form=ge('add_comment_'+story_fbid);var onResponse=function(asyncResponse){var result=asyncResponse.getPayload();remove_feed_comment(story_fbid,story_key,comment_id,result.comment_count,newsfeed);};var onFail=function(response){if(payload=response.getPayload()){if(payload.errTitle){feedcomment_show_error(add_comment_form,payload.errTitle,payload.errBody?payload.errBody:'');}else{onTransportFail(response);}}else{onTransportFail(response);}};new Dialog().setTitle(tx('fc01')).setBody(tx('fc02')).setButtons([{name:'delete',label:tx('sh:delete'),handler:bind(this,function(){new AsyncRequest().setURI('/ajax/feed_wallpost_ajax.php').setData({'story_fbid':story_fbid,'story_key':story_key,'target_fbid':target_fbid,'del_id':comment_id,'actor':actor,'newsfeed':newsfeed}).setHandler(onResponse).setErrorHandler(onFail).send();})},Dialog.CANCEL]).show();}
function remove_feed_comment(story_fbid,story_key,comment_id,comment_count,newsfeed){if(typeof comment_count=='undefined'){comment_count=feed_comments_get_count(story_fbid)-1;}
feed_comment_update_count(story_fbid,story_key,comment_count+1,comment_count,newsfeed);var comment_box=ge('comments_box_'+story_fbid);if(comment_box){var comment=ge('comment_'+story_fbid+"_"+comment_id);if(comment){comment.parentNode.removeChild(comment);}}}
function toggle_feedcomments_box(story_fbid,story_key,newsfeed){var story=feedcomments_get_story_div(story_fbid,story_key,newsfeed);if(story){CSS.toggleClass(story,'expanded_comments');CSS.toggleClass(story,'collapsed_comments');if(CSS.hasClass(story,'story_ff')){CSS.toggleClass(story,'ff_expanded_comments');CSS.toggleClass(story,'ff_collapsed_comments');}
if(ge('add_comment_text_'+story_fbid)){ge('add_comment_text_'+story_fbid).focus();}}}
function feedcomments_get_story_div(story_fbid,story_key,newsfeed){var story;if(newsfeed){story=ge('div_story_'+story_key+'_'+story_fbid);if(!story){story=ge('div_story_'+story_key);}}else{story=ge('minifeed_'+story_key);}
return story;}
if (window.Bootloader) { Bootloader.done(["js\/feedcomment.js"]); }