/*       Source:  Global Cache                                                                */
/*     Location:  js/feedform.js r118934                                                      */
/*      Machine:  10.16.140.108                                                               */
/*    Generated:  September 13th 2008 1:22:05 AM PDT                                          */
/*    HTTP Host:  static.ak.fbcdn.net                                                         */
/*       Locale:  nu_ll                                                                       */


function FeedFormBase(){this._storyType=63;this._feedData=null;this._uri='/fbml/ajax/prompt_feed.php';};FeedFormBase.SIZES={"small":1,"medium":2,"large":4};FeedFormBase.prototype.setStoryType=function(storyType){this._storyType=storyType;return this;};FeedFormBase.prototype.setForm=function(id){this._form=$(id);return this;};FeedFormBase.prototype.setFeedData=function(feedData){this._feedData=feedData;return this;};FeedFormBase.prototype.setAppId=function(appId){this._appid=appId;return this;};FeedFormBase.prototype.setURI=function(uri){this._uri=uri;return this;};FeedFormBase.prototype.setContinuation=function(continuation){this._continuation=continuation;return this;};FeedFormBase.prototype._selectSize=function(option){var size=option['size'];if(size!=this._currentSize){CSS.removeClass(this._selectedSize,'Tabset_selected');animation($('preview_'+this._currentSize)).to('opacity',0).hide().duration(150).go();animation($('preview_'+size)).duration(150).checkpoint().show().from('opacity',0).to('opacity',1).duration(150).go();this._selectedSize=option;this._currentSize=size;CSS.addClass(this._selectedSize,'Tabset_selected');}
return false;};FeedFormBase.prototype.attachHandlers=function(dialog){this._attachSizeHandlers(dialog);return this;}
FeedFormBase.prototype._attachSizeHandlers=function(dialog){var options=this._selectorOptions;var id_prefix=this._feedformFilter;var feedform_remember=this._rememberData;for(var i=0;i<options.length;i++){var node=$(id_prefix+'_'+options[i]['size']);var size=options[i]['size'];options[i]['node']=node;if(CSS.hasClass(node,'Tabset_selected')){this._selectedSize=options[i];this._currentSize=size;}
if(feedform_remember&&feedform_remember['selector_id']){var options_elem=$(feedform_remember['selector_id']);var checkbox_elem=$(feedform_remember['checkbox_id']);var cancel_button_elem;if(this._dialog){cancel_button_elem=this._dialog.getButtonElement('cancel');this.publish_button=this._dialog.getButtonElement('publish');}else{cancel_button_elem=$('cancel');this.publish_button=$('publish');}
this.is_never_publish=false;this.remember_options=options_elem.childNodes;addEventBase(options_elem,'change',this._selectRememberOption.bind(this,options_elem));checkbox_elem.onclick=function(checkbox_elem){if(checkbox_elem.checked){if(this.is_never_publish){this._setPublishButtonText(tx('sh:save-button'));}else{this._setPublishButtonText(tx('ff01'));}
CSS.removeClass(options_elem,'hidden_elem');CSS.addClass(this.publish_button,'align_bottom');CSS.addClass(cancel_button_elem,'hidden_elem');}else{this._setPublishButtonText(tx('ff02'));CSS.addClass(options_elem,'hidden_elem');CSS.removeClass(cancel_button_elem,'hidden_elem');CSS.removeClass(this.publish_button,'align_bottom');}}.bind(this,checkbox_elem);}
addEventBase(node,'click',this._selectSize.bind(this,options[i]),size);}
return true;}
FeedFormBase.prototype._finish=function(){if(this._dialog){this._dialog.hide();}
if(this._continuation){this._continuation();}};FeedFormBase.prototype.showDialog=function(async){this._dialog=new Dialog().setContentWidth(580).setClassName('interaction_form').setAsync(async).setHandler(this.handleButton.bind(this)).onloadRegister(this.attachHandlers.bind(this));return this;};FeedFormBase.prototype._confirm=function(data){new AsyncRequest().setURI(this._uri).setData(data).setHandler(this.showConfirmed.bind(this)).send();};FeedFormBase.prototype.handleButton=function(button){if(button.name=="cancel"){this._finish();}else if(button.name=="publish"){this.confirmFeed();return false;}};FeedFormBase.prototype.attachProperties=function(userData){copy_properties(this,userData);if(this._continuationJS){this._continuation=new Function(this._continuationJS);}
return this;};FeedFormBase.prototype._showBase=function(data){var async=new AsyncRequest().setURI(this._uri).setHandler(function(r){var user_data=r.getPayload().userData;this.attachProperties(user_data);if(user_data['continuation']&&this._continuation){this._continuation();}
return true;}.bind(this)).setErrorHandler(this._showApplicationError.bind(this)).setData(data);this.showDialog(async);return this;};FeedFormBase.prototype.showConfirmed=function(){var msg=this.is_never_publish?tx('ff03'):tx('fbml:publish-story');var confirmation='<div class="interim_status"><h3>'+msg+'</h3></div>';if(this._dialog){this._dialog.setBody(confirmation);}else{ge('dialog_body').innerHTML=confirmation;}
setTimeout(this._finish.bind(this),500);return false;};FeedFormBase.prototype._showApplicationError=function(response){var showError=function(showMsg){(new ErrorDialog()).showError(response.getPayload().errorTitle,showMsg?(response.getPayload().errorMessage):tx('fbml:dialog-error'));}
var err=response.getError();if(err==kError_Platform_CallbackValidationFailure){showError(true);}else if(err==kError_Platform_ApplicationResponseInvalid){if(response.getPayload().showDebug){showError(true);}else{if(this._continuation){this._continuation();}else{showError(false);}}}else{ErrorDialog.showAsyncError(response);}
return false;};function FeedForm(){this.parent.construct(this);}
FeedForm.extend(FeedFormBase);FeedForm.neverPublishConstant=2;FeedForm.prototype._selectRememberOption=function(option){var options=this._selectorOptions;if(this.remember_options&&option.selectedIndex<options.length){options[option.selectedIndex]['node'].onclick();this._selectSize(options[option.selectedIndex]);}
this.is_never_publish=(this.remember_options[option.selectedIndex].value==FeedForm.neverPublishConstant);if(this.is_never_publish){this._setPublishButtonText(tx('sh:save-button'));}else{this._setPublishButtonText(tx('ff01'));}}
FeedForm.prototype._setPublishButtonText=function(text){this.publish_button.value=text;}
FeedForm.prototype._setOptionSelector=function(selected_story_size){for(var i=0;i<this.remember_options.length;i++){this.remember_options[i].selected=this.remember_options[i].value==selected_story_size['save_preferences'];}};FeedForm.prototype.show=function(){var more={};if(this._form){more={callback:this._form.getAttribute('action'),next:this._form.getAttribute('fbnext'),elements:serialize_form(this._form)};}
var data={app_id:this._appid,feedform_type:this._storyType,feed_info:this._feedData,preview:true,multiFeed:false};copy_properties(data,more);return this._showBase(data);}
FeedForm.prototype.confirmFeed=function(){var pref_selector=$('feed_remember_options');var has_selected_option=$('feed_never_show').checked?1:0;var selected_option=pref_selector.childNodes[pref_selector.selectedIndex].value;var data={feed_info:this._feedData,feedform_type:this._storyType,has_selected_option:has_selected_option,selected_option:selected_option,preview:false,multiFeed:false,app_id:this._appid,size:FeedFormBase.SIZES[this._currentSize]};this._confirm(data);};function MultiFeedForm(){this.parent.construct(this);}
MultiFeedForm.extend(FeedFormBase);MultiFeedForm.prototype.setPrefillId=function(prefillId){if(prefillId>0){this._prefillId=prefillId;}else{this._prefillId=null;}
return this;};MultiFeedForm.prototype.removeRecipient=function(user){this._toIds=this._toIds.filter(function(u){return u!=user;});if(this._toIds.length==0){this._finish();}else{DOM.remove('sp'+user);}
return false;};MultiFeedForm.prototype.confirmFeed=function(){var data={feed_info:this._feedData,feedform_type:this._storyType,to_ids:this._toIds,preview:false,multiFeed:true,app_id:this._appid,size:FeedFormBase.SIZES[this._currentSize]};this._confirm(data);};MultiFeedForm.prototype.show=function(){var ids=[];if(this._prefillId){ids.push(this._prefillId);}else{var inputs=this._form.getElementsByTagName('input');for(var i=0;i<inputs.length;i++){if(inputs[i].getAttribute('fb_protected')=='true'&&(inputs[i].name=='ids[]'||inputs[i].name=='friend_selector_id')&&(inputs[i].type!='checkbox'||inputs[i].checked)){ids.push(inputs[i].value);}}}
this._toIds=ids;var data={app_id:this._appid,to_ids:this._toIds,callback:this._form.action,preview:true,form_id:this._form.id,next:this._form.getAttribute('fbnext'),prefill:(this.prefillId>0),elements:serialize_form(this._form),multiFeed:true};return this._showBase(data);};MultiFeedForm.prototype.attachHandlers=function(dialog){for(var i=0;i<this._toIds.length;i++){var person_link=ge('spl_'+this._toIds[i]);if(person_link){person_link.onclick=this.removeRecipient.bind(this,this._toIds[i]);}}
this.parent.attachHandlers(dialog);};
if (window.Bootloader) { Bootloader.done(["js\/feedform.js"]); }