function OAS_RICH(position) {
if (position == 'PageCounter') {
document.write ('<A HREF="http://www.weather.com/RealMedia/ads/click_lx.ads/www.weather.com/f/r/p/home/1002995385/PageCounter/default/empty.gif/64356563643031363438376466613430?pdsrch=300x235" target="_blank"><IMG BORDER="0" SRC="weather.com_files/empty.gif"  WIDTH=2 HEIGHT=2 ALT="" BORDER=0></A><IMG BORDER="0" SRC="weather.com_files/blank.gif" />');
}
if (position == 'HeaderSpon') {
document.write ('<A HREF="http://www.weather.com/RealMedia/ads/click_lx.ads/www.weather.com/f/r/p/home/31579026/HeaderSpon/default/empty.gif/64356563643031363438376466613430?pdsrch=300x235" target="_blank"><IMG BORDER="0" SRC="weather.com_files/empty.gif"  WIDTH=2 HEIGHT=2 ALT="" BORDER=0></A><IMG BORDER="0" SRC="weather.com_files/blank.gif" style="position:absolute;top:0px;left:0px;width:0px;height:0px;" />');
}
if (position == 'WindowShade') {
document.write ('<script type="text/javascript" src="weather.com_files/windowshade.js" ></script>\n');
document.write ('<IMG BORDER="0" SRC="weather.com_files/blank.gif" style="position:absolute;top:0px;left:0px;width:0px;height:0px;" />');
}
if (position == 'PageSpon') {
document.write ('<!-- campaign: 14876_FORGETAWAY_29060060 page: www.weather.com/f/r/p/home position: PageSpon -->\n');
document.write ('<!-- __QUERY__ -->\n');
document.write ('<script language="JavaScript1.1">\n');
document.write ('var TFSMFlash_VERSION=7;\n');
document.write ('var TFSMFlash_WMODE="opaque";\n');
document.write ('var TFSMFlash_OASCLICK="http://www.weather.com/RealMedia/ads/click_lx.ads/www.weather.com/f/r/p/home/1900783663/PageSpon/14876_FORGETAWAY_29060060/11763_300x250_WishWC_062607.html/64356563643031363438376466613430?http://forgetaway.weather.com/index.html?cm_ven=vac_rental%26cm_cat=pop_dest%26cm_pla=sc%26cm_ite=see_all";\n');
document.write ('var TFSMFlash_SWFCLICKVARIABLE="?clickTAG1=http://www.weather.com/RealMedia/ads/click_lx.ads/www.weather.com/f/r/p/home/1900783663/PageSpon/14876_FORGETAWAY_29060060/11763_300x250_WishWC_062607.html/64356563643031363438376466613430?http://forgetaway.weather.com/vacationrentals/search/properties/?locId=29926&clickTAG2=http://www.weather.com/RealMedia/ads/click_lx.ads/www.weather.com/f/r/p/home/1900783663/PageSpon/14876_FORGETAWAY_29060060/11763_300x250_WishWC_062607.html/64356563643031363438376466613430?http://forgetaway.weather.com/vacationrentals/search/properties/?locId=29451&clickTAG3=http://www.weather.com/RealMedia/ads/click_lx.ads/www.weather.com/f/r/p/home/1900783663/PageSpon/14876_FORGETAWAY_29060060/11763_300x250_WishWC_062607.html/64356563643031363438376466613430?http://forgetaway.weather.com/vacationrentals/search/properties/?locId=29577&clickTAG4=http://www.weather.com/RealMedia/ads/click_lx.ads/www.weather.com/f/r/p/home/1900783663/PageSpon/14876_FORGETAWAY_29060060/11763_300x250_WishWC_062607.html/64356563643031363438376466613430?http://forgetaway.weather.com/vacationrentals/search/properties/?locId=USSC0115&clickTAG5=http://www.weather.com/RealMedia/ads/click_lx.ads/www.weather.com/f/r/p/home/1900783663/PageSpon/14876_FORGETAWAY_29060060/11763_300x250_WishWC_062607.html/64356563643031363438376466613430?http://forgetaway.weather.com/vacationrentals/search/properties/?locId=29920&clickTAG6=http://www.weather.com/RealMedia/ads/click_lx.ads/www.weather.com/f/r/p/home/1900783663/PageSpon/14876_FORGETAWAY_29060060/11763_300x250_WishWC_062607.html/64356563643031363438376466613430?http://forgetaway.weather.com/vacationrentals/search/properties/?locId=USSC0264&clickTAG7=http://www.weather.com/RealMedia/ads/click_lx.ads/www.weather.com/f/r/p/home/1900783663/PageSpon/14876_FORGETAWAY_29060060/11763_300x250_WishWC_062607.html/64356563643031363438376466613430?http://forgetaway.weather.com/index.html?cm_ven=vac_rental%26cm_cat=pop_dest%26cm_pla=sc%26cm_ite=see_all";\n');
document.write ('var TFSMFlash_SWFFILE="weather.com_files/11763_300x250_WishWC_062607.swf"+TFSMFlash_SWFCLICKVARIABLE;\n');
document.write ('var TFSMFlash_IMAGEALTERNATE="weather.com_files/11763_300x250_WishWC_062607.gif";\n');
document.write ('var TFSMFlash_OASALTTEXT="Click Here";\n');
document.write ('var TFSMFlash_OASTARGET="_blank";\n');
document.write ('var TFSMFlash_OASPROTOCOL="http://";\n');
document.write ('var TFSMFlash_OASDIM="WIDTH=');
document.write ("'");
document.write ('300');
document.write ("'");
document.write (' HEIGHT=');
document.write ("'");
document.write ('250');
document.write ("'");
document.write ('";\n');
document.write ('var TFSMFlash_OASADID="ad_banner";\n');
document.write ('document.write(');
document.write ("'");
document.write ('<scr');
document.write ("'");
document.write ('+');
document.write ("'");
document.write ('ipt src="weather.com_files/TFSMFlashWrapper201.js"></scr');
document.write ("'");
document.write ('+');
document.write ("'");
document.write ('ipt>');
document.write ("'");
document.write (');\n');
document.write ('</script><IMG BORDER="0" SRC="weather.com_files/blank.gif" style="position:absolute;top:0px;left:0px;width:0px;height:0px;" />');
}
if (position == 'PdSearch') {
document.write ('<script language="Javascript">\n');
document.write ('\n');
document.write ('if (!window.wxtools) wxtools = {};\n');
document.write ('\n');
document.write ('var pulseid="89199145";var too=0;var cgroup="";var urlSrc="";var temp="";var humidity="";var dec="";var md="";var dma="";var cs="";var zip="";var rmid="";var refParameter="";var urlSrc2="";var localSev="";var title="";var hyperLocal="";var sev="";var dmaTemp=parent.OAS_spoof.match(');
document.write ("'");
document.write ('[0-9][0-9][0-9]');
document.write ("'");
document.write (');var countryT="";\n');
document.write ('var moduleSize = ""; \n');
document.write ('\n');
document.write ('\n');
document.write ('function sponsAd() {\n');
document.write ('	wxtools.SearchLink.writeListFrame();\n');
document.write ('}\n');
document.write ('wxtools.SearchLink_AdFrameURL 	= "weather.com_files/includePulseNoBeaconCalls.html";\n');
document.write ('wxtools.SearchLink = new function() {		\n');
document.write ('		var _name = "searchListings";\n');
document.write ('		var allowed = true;\n');
document.write ('		var t = null;\n');
document.write ('		// For FormatSize\n');
document.write ('		var OASQry = parent.OAS_query;\n');
document.write ('		if(OASQry.indexOf("pdsrch=") > 0) {\n');
document.write ('			theIndex = parent.OAS_query.indexOf("pdsrch=");\n');
document.write ('			tempper = parent.OAS_query.substring(theIndex, theIndex+14);\n');
document.write ('			tempperM = tempper.split("=");\n');
document.write ('			moduleSize = tempperM[1];\n');
document.write ('		} else {\n');
document.write ('			moduleSize = "300x235"; // Default if none in the qry\n');
document.write ('		}\n');
document.write ('		var moduleWidth = moduleSize.substring(0,3)*1+10;\n');
document.write ('		var moduleHeight = moduleSize.substring(4)*1+10;\n');
document.write ('		this.writeListFrame = function() {\n');
document.write ('				document.write([\n');
document.write ('					');
document.write ("'");
document.write ('<iframe ');
document.write ("'");
document.write (',\n');
document.write ('						');
document.write ("'");
document.write ('id="');
document.write ("'");
document.write (',_name,');
document.write ("'");
document.write ('_frame" ');
document.write ("'");
document.write (',\n');
document.write ('						');
document.write ("'");
document.write ('name="');
document.write ("'");
document.write (',_name,');
document.write ("'");
document.write ('_frame" ');
document.write ("'");
document.write (',\n');
document.write ('						');
document.write ("'");
document.write ('src="');
document.write ("'");
document.write (',wxtools.SearchLink_AdFrameURL,');
document.write ("'");
document.write ('?position=');
document.write ("'");
document.write (',_name,');
document.write ("'");
document.write ('&pulseid=');
document.write ("'");
document.write (',pulseid,');
document.write ("'");
document.write ('&cgroup=');
document.write ("'");
document.write (',cgroup, ');
document.write ("'");
document.write ('&format=');
document.write ("'");
document.write (',moduleSize,');
document.write ("'");
document.write ('&dma=');
document.write ("'");
document.write (',dmaTemp,');
document.write ("'");
document.write ('&temp=');
document.write ("'");
document.write (',temp,');
document.write ("'");
document.write ('&humd=');
document.write ("'");
document.write (',humidity,');
document.write ("'");
document.write ('&dec=');
document.write ("'");
document.write (',dec,');
document.write ("'");
document.write ('&md=');
document.write ("'");
document.write (',md,');
document.write ("'");
document.write ('&cs=');
document.write ("'");
document.write (',cs,');
document.write ("'");
document.write ('&zip=');
document.write ("'");
document.write (',zip,');
document.write ("'");
document.write ('&rmid=');
document.write ("'");
document.write (',rmid,');
document.write ("'");
document.write ('" ');
document.write ("'");
document.write (',\n');
document.write ('						');
document.write ("'");
document.write ('frameBorder="0" ');
document.write ("'");
document.write (',\n');
document.write ('						');
document.write ("'");
document.write ('scrolling="no" ');
document.write ("'");
document.write (',\n');
document.write ('						');
document.write ("'");
document.write ('width="');
document.write ("'");
document.write ('+moduleWidth+');
document.write ("'");
document.write ('" height="');
document.write ("'");
document.write ('+moduleHeight+');
document.write ("'");
document.write ('"');
document.write ("'");
document.write (',\n');
document.write ('						');
document.write ("'");
document.write ('style="margin-left: -2px;" ');
document.write ("'");
document.write (',\n');
document.write ('						');
document.write ("'");
document.write ('></iframe>');
document.write ("'");
document.write ('].join(');
document.write ("'");
document.write ('');
document.write ("'");
document.write ('));\n');
document.write ('		}				\n');
document.write ('				\n');
document.write ('		\n');
document.write ('}\n');
document.write ('\n');
document.write ('\n');
document.write ('\n');
document.write ('// Function to strip the necessary info from OAS Qry\n');
document.write ('function stripOASQuery() {\n');
document.write ('	//createSevArray();\n');
document.write ('	var OASQry = parent.OAS_query;\n');
document.write ('		\n');
document.write ('\n');
document.write ('if(OASQry.indexOf("&temp=")>0){theleft=OASQry.indexOf("&temp=")+1;theright=OASQry.lastIndexOf("&");temp=OASQry.substring(theleft,theright);theMain=temp.indexOf("&");temp=OASQry.substring(theleft,theMain+theleft).indexOf("=")+1;temp=OASQry.substring(temp+theleft,theMain+theleft);}\n');
document.write ('if(OASQry.indexOf("&humid=")>0){theleft2=OASQry.indexOf("&humid=")+1;theright2=OASQry.lastIndexOf("&");temp2=OASQry.substring(theleft2,theright2);theMain2=temp2.indexOf("&");tempNew=OASQry.substring(theleft2,theMain2+theleft2).indexOf("=")+1;humidity=OASQry.substring(tempNew+theleft2,theMain2+theleft2);}\n');
document.write ('if(temp.length>3)temp="";if(humidity.length>3)humidity="";if(OASQry.indexOf("&severe=")>0){theleft3=OASQry.indexOf("&severe=")+1;theright3=OASQry.lastIndexOf("&");temp3=OASQry.substring(theleft3,theright3);theMain3=temp3.indexOf("&");tempNew2=OASQry.substring(theleft3,theMain3+theleft3).indexOf("=")+1;localSev=OASQry.substring(tempNew2+theleft3,theMain3+theleft3);\n');
document.write ('		\n');
document.write ('	}\n');
document.write ('}\n');
document.write ('function getCGroup(){var CM_tag = parent.CM_tag;if(CM_tag==');
document.write ("'");
document.write ('recr_boat_pif');
document.write ("'");
document.write ('){cgroup="cprecbb";dec="BB";}else if(CM_tag==');
document.write ("'");
document.write ('hlth_pain_pif');
document.write ("'");
document.write ('){cgroup="cphthap";dec="AP";}else if(CM_tag==');
document.write ("'");
document.write ('hlth_brth_pif');
document.write ("'");
document.write ('){cgroup="cphthaqp";dec="AQ";}else if(CM_tag==');
document.write ("'");
document.write ('hlth_algy_pif');
document.write ("'");
document.write ('){cgroup="cphthalp";dec="AL";}else if(CM_tag==');
document.write ("'");
document.write ('hlth_flu_pif');
document.write ("'");
document.write ('){cgroup="cphthcf";dec="CF";}else if(CM_tag==');
document.write ("'");
document.write ('hlth_fit_pif');
document.write ("'");
document.write ('){cgroup="cphthfe";dec="FE";}else if(CM_tag==');
document.write ("'");
document.write ('trvl_btrav_pif');
document.write ("'");
document.write ('){cgroup="cptrvflb";dec="FB";}else if(CM_tag==');
document.write ("'");
document.write ('recr_golf_pif');
document.write ("'");
document.write ('){cgroup="cprecglf";dec="GW";}else if(CM_tag==');
document.write ("'");
document.write ('hlth_genhlth_pif');
document.write ("'");
document.write ('){if(title!=""){cgroup="cphthghlim";}else{cgroup="cphthgh";dec="HE";}}else if(CM_tag==');
document.write ("'");
document.write ('hng_h_pif');
document.write ("'");
document.write ('){cgroup="cphghi";dec="HI";}else if(CM_tag==');
document.write ("'");
document.write ('drv_intst_pif');
document.write ("'");
document.write ('){cgroup="cpdrvidf";dec="ID";}else if(CM_tag==');
document.write ("'");
document.write ('hng_g_pif');
document.write ("'");
document.write ('){cgroup="cphglg";dec="LG";}else if(CM_tag==');
document.write ("'");
document.write ('recr_outd_pif');
document.write ("'");
document.write ('){cgroup="cprecorc";dec="OR";}else if(CM_tag==');
document.write ("'");
document.write ('hng_pets_pif');
document.write ("'");
document.write ('){cgroup="cphgpet";dec="PE";}else if(CM_tag==');
document.write ("'");
document.write ('hng_schdy_pif');
document.write ("'");
document.write ('){cgroup="cphgsd";dec="SW";}else if(CM_tag==');
document.write ("'");
document.write ('recr_ski_pif');
document.write ("'");
document.write ('){cgroup="cprecski";dec="SC";}else if(CM_tag==');
document.write ("'");
document.write ('hlth_skin_pif');
document.write ("'");
document.write ('){cgroup="cphthskn";dec="SP";}else if(CM_tag==');
document.write ("'");
document.write ('evt_sprt_pif');
document.write ("'");
document.write ('){cgroup="cpevtsprt";dec="SE";}else if(CM_tag==');
document.write ("'");
document.write ('trvl_vac_pif');
document.write ("'");
document.write ('){cgroup="cptrvvca";dec="VT";}else if(CM_tag==');
document.write ("'");
document.write ('evt_wed_pif');
document.write ("'");
document.write ('){cgroup="cpevtwed";dec="WP";}else if(CM_tag=="undcl_pif"){cgroup="cplocund";dec="undeclared";}else if(CM_tag==');
document.write ("'");
document.write ('hp');
document.write ("'");
document.write ('){cgroup="hp";}else if(CM_tag==');
document.write ("'");
document.write ('local_guides_index');
document.write ("'");
document.write ('){cgroup="cploclgi";}else if(CM_tag.substring(0,12)==');
document.write ("'");
document.write ('local_guides');
document.write ("'");
document.write ('){cgroup="cploclg";}else if(CM_tag==');
document.write ("'");
document.write ('trvl_av_map');
document.write ("'");
document.write ('){cgroup="mmcl";}else if(CM_tag==');
document.write ("'");
document.write ('interactive_map');
document.write ("'");
document.write ('){cgroup="cplocundlim";}\n');
document.write ('var refParameter="";try{refParameter=paramValue(');
document.write ("'");
document.write ('ref');
document.write ("'");
document.write (');}catch(Exception){refParameter=null;}\n');
document.write ('if(cgroup==""){if(refParameter!=undefined){if(title!=""){if(CM_tag==');
document.write ("'");
document.write ('hlth_pain_map');
document.write ("'");
document.write ('){cgroup="cphthaplim";}else if(CM_tag==');
document.write ("'");
document.write ('hlth_algy_map');
document.write ("'");
document.write ('){cgroup="cphthalplim";}else if(CM_tag==');
document.write ("'");
document.write ('hlth_skin_map');
document.write ("'");
document.write ('){cgroup="cphthsknlim";}else if(CM_tag==');
document.write ("'");
document.write ('hlth_brth_map');
document.write ("'");
document.write ('){cgroup="cphthaqplim";}else if(CM_tag==');
document.write ("'");
document.write ('hlth_flu_map');
document.write ("'");
document.write ('){cgroup="cphthcflim";}else if(CM_tag==');
document.write ("'");
document.write ('hlth_fit_map');
document.write ("'");
document.write ('){cgroup="cphthfelim";}else if(CM_tag==');
document.write ("'");
document.write ('gen_map');
document.write ("'");
document.write ('){cgroup="cplocundlim";}else if(CM_tag==');
document.write ("'");
document.write ('hng_schdy_map');
document.write ("'");
document.write ('){cgroup="cphgsdlim";}else if(CM_tag==');
document.write ("'");
document.write ('recr_boat_map');
document.write ("'");
document.write ('){cgroup="cprecbblim";}else if(CM_tag==');
document.write ("'");
document.write ('hng_g_map');
document.write ("'");
document.write ('){cgroup="cphglglim";}else if(CM_tag==');
document.write ("'");
document.write ('recr_golf_map');
document.write ("'");
document.write ('){cgroup="cprecglflim";}else if(CM_tag==');
document.write ("'");
document.write ('recr_outd_map');
document.write ("'");
document.write ('){cgroup="cprecorclim";}else if(CM_tag==');
document.write ("'");
document.write ('recr_ski_map');
document.write ("'");
document.write ('){cgroup="cprecskilim";}else if(CM_tag==');
document.write ("'");
document.write ('trvl_btrav_map');
document.write ("'");
document.write ('){cgroup="cptrvflblim";}else if(CM_tag==');
document.write ("'");
document.write ('trvl_vac_map');
document.write ("'");
document.write ('){cgroup="cptrvvcalim";}else if(CM_tag==');
document.write ("'");
document.write ('hng_h_map');
document.write ("'");
document.write ('){cgroup="cphghilim";}else if(CM_tag==');
document.write ("'");
document.write ('hng_pets_map');
document.write ("'");
document.write ('){cgroup="cphgpetlim";}else if(CM_tag==');
document.write ("'");
document.write ('drv_intst_map');
document.write ("'");
document.write ('){cgroup="cpdrvidflim";}else if(CM_tag==');
document.write ("'");
document.write ('evt_sprt_map');
document.write ("'");
document.write ('){cgroup="cpevtsprtlim";}else if(CM_tag==');
document.write ("'");
document.write ('evt_wed_map');
document.write ("'");
document.write ('){cgroup="cpevtwedlim";}}else{if(CM_tag==');
document.write ("'");
document.write ('hlth_pain_map');
document.write ("'");
document.write ('){cgroup="cphthapllm";}else if(CM_tag==');
document.write ("'");
document.write ('hlth_algy_map');
document.write ("'");
document.write ('){cgroup="cphthalpllm";}else if(CM_tag==');
document.write ("'");
document.write ('hlth_skin_map');
document.write ("'");
document.write ('){cgroup="cphthsknllm";}else if(CM_tag==');
document.write ("'");
document.write ('hlth_brth_map');
document.write ("'");
document.write ('){cgroup="cphthaqpllm";}else if(CM_tag==');
document.write ("'");
document.write ('hlth_flu_map');
document.write ("'");
document.write ('){cgroup="cphthcfllm";}else if(CM_tag==');
document.write ("'");
document.write ('hlth_fit_map');
document.write ("'");
document.write ('){cgroup="cphthfellm";}else if(CM_tag==');
document.write ("'");
document.write ('gen_map');
document.write ("'");
document.write ('){cgroup="cplocundllm";}else if(CM_tag==');
document.write ("'");
document.write ('hng_schdy_map');
document.write ("'");
document.write ('){cgroup="cphgsdllm";}else if(CM_tag==');
document.write ("'");
document.write ('recr_boat_map');
document.write ("'");
document.write ('){cgroup="cprecbbllm";}else if(CM_tag==');
document.write ("'");
document.write ('hng_g_map');
document.write ("'");
document.write ('){cgroup="cphglgllm";}else if(CM_tag==');
document.write ("'");
document.write ('recr_golf_map');
document.write ("'");
document.write ('){cgroup="cprecglfllm";}else if(CM_tag==');
document.write ("'");
document.write ('recr_outd_map');
document.write ("'");
document.write ('){cgroup="cprecorcllm";}else if(CM_tag==');
document.write ("'");
document.write ('recr_ski_map');
document.write ("'");
document.write ('){cgroup="cprecskillm";}else if(CM_tag==');
document.write ("'");
document.write ('trvl_btrav_map');
document.write ("'");
document.write ('){cgroup="cptrvflbllm";}else if(CM_tag==');
document.write ("'");
document.write ('trvl_vac_map');
document.write ("'");
document.write ('){cgroup="cptrvvcallm";}else if(CM_tag==');
document.write ("'");
document.write ('hng_h_map');
document.write ("'");
document.write ('){cgroup="cphghillm";}else if(CM_tag==');
document.write ("'");
document.write ('hng_pets_map');
document.write ("'");
document.write ('){cgroup="cphgpetllm";}else if(CM_tag==');
document.write ("'");
document.write ('drv_intst_map');
document.write ("'");
document.write ('){cgroup="cpdrvidfllm";}else if(CM_tag==');
document.write ("'");
document.write ('evt_sprt_map');
document.write ("'");
document.write ('){cgroup="cpevtsprtllm";}else if(CM_tag==');
document.write ("'");
document.write ('evt_wed_map');
document.write ("'");
document.write ('){cgroup="cpevtwedllm";}}}else{if(title.length>5){if(CM_tag==');
document.write ("'");
document.write ('hlth_pain_map');
document.write ("'");
document.write ('){cgroup="cphthaplim";}else if(CM_tag==');
document.write ("'");
document.write ('hlth_algy_map');
document.write ("'");
document.write ('){cgroup="cphthalplim";}else if(CM_tag==');
document.write ("'");
document.write ('hlth_skin_map');
document.write ("'");
document.write ('){cgroup="cphthsknlim";}else if(CM_tag==');
document.write ("'");
document.write ('hlth_brth_map');
document.write ("'");
document.write ('){cgroup="cphthaqplim";}else if(CM_tag==');
document.write ("'");
document.write ('hlth_flu_map');
document.write ("'");
document.write ('){cgroup="cphthcflim";}else if(CM_tag==');
document.write ("'");
document.write ('hlth_fit_map');
document.write ("'");
document.write ('){cgroup="cphthfelim";}else if(CM_tag==');
document.write ("'");
document.write ('gen_map');
document.write ("'");
document.write ('){cgroup="cplocundlim";}else if(CM_tag==');
document.write ("'");
document.write ('hng_schdy_map');
document.write ("'");
document.write ('){cgroup="cphgsdlim";}else if(CM_tag==');
document.write ("'");
document.write ('recr_boat_map');
document.write ("'");
document.write ('){cgroup="cprecbblim";}else if(CM_tag==');
document.write ("'");
document.write ('hng_g_map');
document.write ("'");
document.write ('){cgroup="cphglglim";}else if(CM_tag==');
document.write ("'");
document.write ('recr_golf_map');
document.write ("'");
document.write ('){cgroup="cprecglflim";}else if(CM_tag==');
document.write ("'");
document.write ('recr_outd_map');
document.write ("'");
document.write ('){cgroup="cprecorclim";}else if(CM_tag==');
document.write ("'");
document.write ('recr_ski_map');
document.write ("'");
document.write ('){cgroup="cprecskilim";}else if(CM_tag==');
document.write ("'");
document.write ('trvl_btrav_map');
document.write ("'");
document.write ('){cgroup="cptrvflblim";}else if(CM_tag==');
document.write ("'");
document.write ('trvl_vac_map');
document.write ("'");
document.write ('){cgroup="cptrvvcalim";}else if(CM_tag==');
document.write ("'");
document.write ('hng_h_map');
document.write ("'");
document.write ('){cgroup="cphghilim";}else if(CM_tag==');
document.write ("'");
document.write ('hng_pets_map');
document.write ("'");
document.write ('){cgroup="cphgpetlim";}else if(CM_tag==');
document.write ("'");
document.write ('drv_intst_map');
document.write ("'");
document.write ('){cgroup="cpdrvidflim";}else if(CM_tag==');
document.write ("'");
document.write ('evt_sprt_map');
document.write ("'");
document.write ('){cgroup="cpevtsprtlim";}else if(CM_tag==');
document.write ("'");
document.write ('evt_wed_map');
document.write ("'");
document.write ('){cgroup="cpevtwedlim";}}else{cgroup="mmcl";}}}}\n');
document.write ('function getSiteMode(){try{if(localSev==""){if(gnSiteMode=="normal"){tempMD="N";}else if(gnSiteMode=="severe"){tempMD="S"}else if(gnSiteMode=="alert"){tempMD="A";}else{tempMD="N";}\n');
document.write ('md=tempMD;}else{md="L";}}catch(Exception){md="N";}}\n');
document.write ('function getHyperLoc(){try{if(typeInfo==');
document.write ("'");
document.write ('1');
document.write ("'");
document.write ('||typeInfo==');
document.write ("'");
document.write ('4');
document.write ("'");
document.write ('){hyperLocal="";}else if((newLocID!=undefined&&newLocID.length>0)&&(typeInfo==');
document.write ("'");
document.write ('18');
document.write ("'");
document.write ('||typeInfo==');
document.write ("'");
document.write ('19');
document.write ("'");
document.write ('||typeInfo==');
document.write ("'");
document.write ('20');
document.write ("'");
document.write ('||typeInfo==');
document.write ("'");
document.write ('21');
document.write ("'");
document.write ('||typeInfo==');
document.write ("'");
document.write ('17');
document.write ("'");
document.write ('||typeInfo==');
document.write ("'");
document.write ('16');
document.write ("'");
document.write ('||typeInfo==');
document.write ("'");
document.write ('13');
document.write ("'");
document.write ('||typeInfo==');
document.write ("'");
document.write ('11');
document.write ("'");
document.write ('||typeInfo==');
document.write ("'");
document.write ('10');
document.write ("'");
document.write ('||typeInfo==');
document.write ("'");
document.write ('9');
document.write ("'");
document.write ('||typeInfo==');
document.write ("'");
document.write ('5');
document.write ("'");
document.write (')){hyperLocal=newLocID+":"+typeInfo;cs="";}}catch(Exception){hyperLocal="";}}\n');
document.write ('\n');
document.write ('\n');
document.write ('\n');
document.write ('function dataBuilder() {\n');
document.write ('	stripOASQuery();\n');
document.write ('	getCGroup();\n');
document.write ('	getSiteMode();\n');
document.write ('	\n');
document.write ('	rmid = parent.CM_rmid;\n');
document.write ('	if(rmid == undefined) rmid = "";\n');
document.write ('\n');
document.write ('	// Added logic to see if it really is a Zip\n');
document.write ('	try{if(newLocID!=undefined){if(newLocID!=null&&newLocID.length>5){cs=newLocID;zip="";dma="";}else{zip=newLocID;dma=dmaTemp;if(dma==null){dma="";zip="";}\n');
document.write ('	if(countryT==""){cs="";}else{cs=countryT;}}}else{zip="";dma="";cs="";}}catch(Exception){zip="";dma="";cs="";}\n');
document.write ('\n');
document.write ('	// Get Hyper Local Location\n');
document.write ('	getHyperLoc();\n');
document.write ('	sponsAd();\n');
document.write ('}\n');
document.write ('\n');
document.write ('dataBuilder()\n');
document.write ('\n');
document.write ('</script><IMG BORDER="0" SRC="weather.com_files/blank.gif" style="position:absolute;top:0px;left:0px;width:0px;height:0px;" />');
}
if (position == 'WXPartner1') {
document.write ('<!-- campaign: 13561_NATIONWIDE_WEAT_28255101 page: www.weather.com/f/r/p/home position: WXPartner1 -->\n');
document.write ('<!-- __QUERY__ -->\n');
document.write ('\n');
document.write ('<style type="text/css">\n');
document.write ('<!--\n');
document.write ('.ad_partPosition{\n');
document.write ('	margin:0;\n');
document.write ('	padding:0;\n');
document.write ('}\n');
document.write ('\n');
document.write ('.ad_spLink, .ad_spText, .ad_spName, .ad_spTitle {\n');
document.write ('	font-size: 10px;\n');
document.write ('	font-weight: normal;\n');
document.write ('	padding:0;\n');
document.write ('	margin:0;\n');
document.write ('	color: #666666;\n');
document.write ('}\n');
document.write ('\n');
document.write ('.ad_spTitle, .ad_spName { font-weight: bold; }\n');
document.write ('\n');
document.write ('.ad_spText, .ad_spName { font-style: italic; }\n');
document.write ('\n');
document.write ('.ad_spName { color: #888888; }\n');
document.write ('-->\n');
document.write ('</style>\n');
document.write ('<!-- Make Changes Here -->\n');
document.write ('<div class="ad_partPosition">\n');
document.write ('    <p class="ad_spTitle">WeatherREADY Severe</p>\n');
document.write ('    <p class="ad_spLink"><a href="http://www.weather.com/RealMedia/ads/click_lx.ads/www.weather.com/f/r/p/home/890670220/WXPartner1/13561_NATIONWIDE_WEAT_28255101/WxPart1_Nationwide_012308.html/64356563643031363438376466613430?http://www.weather.com/ready/severeweatherprep.html?from=homepage_pp">Be prepared in the event severe weather hits your area</a></p>\n');
document.write ('    <p class="ad_spText">in partnership with</p>\n');
document.write ('    <p class="ad_spName">Nationwide Insurance</p>\n');
document.write ('</div><IMG BORDER="0" SRC="weather.com_files/blank.gif" style="position:absolute;top:0px;left:0px;width:0px;height:0px;" />');
}
if (position == 'WXPartner2') {
document.write ('<!-- campaign: 13673_HOME_DEPOT_TRAC_28232537 page: www.weather.com/f/r/p/home position: WXPartner2 -->\n');
document.write ('<!-- __QUERY__ -->\n');
document.write ('\n');
document.write ('<style type="text/css">\n');
document.write ('<!--\n');
document.write ('.ad_partPosition{\n');
document.write ('	margin:0;\n');
document.write ('	padding:0;\n');
document.write ('}\n');
document.write ('\n');
document.write ('.ad_spLink, .ad_spText, .ad_spName, .ad_spTitle {\n');
document.write ('	font-size: 10px;\n');
document.write ('	font-weight: normal;\n');
document.write ('	padding:0;\n');
document.write ('	margin:0;\n');
document.write ('	color: #666666;\n');
document.write ('}\n');
document.write ('\n');
document.write ('.ad_spTitle, .ad_spName { font-weight: bold; }\n');
document.write ('\n');
document.write ('.ad_spText, .ad_spName { font-style: italic; }\n');
document.write ('\n');
document.write ('.ad_spName { color: #888888; }\n');
document.write ('-->\n');
document.write ('</style>\n');
document.write ('<!-- Make Changes Here -->\n');
document.write ('<div class="ad_partPosition">\n');
document.write ('    <p class="ad_spTitle">Project of the Week</p>\n');
document.write ('    <p class="ad_spLink"><a href="http://www.weather.com/RealMedia/ads/click_lx.ads/www.weather.com/f/r/p/home/985911608/WXPartner2/13673_HOME_DEPOT_TRAC_28232537/WxPart2_HomeDepot_012308.html/64356563643031363438376466613430?http://www.weather.com/partnerships/homedepot/?from=homepage_pp">Get step-by-step guides to improve your home</a></p>\n');
document.write ('    <p class="ad_spText">in partnership with</p>\n');
document.write ('    <p class="ad_spName">The Home Depot</p>\n');
document.write ('</div><IMG BORDER="0" SRC="weather.com_files/blank.gif" style="position:absolute;top:0px;left:0px;width:0px;height:0px;" />');
}
if (position == 'WXPartner3') {
document.write ('<!-- campaign: 13893_CISCO_Q408_28831185 page: www.weather.com/f/r/p/home position: WXPartner3 -->\n');
document.write ('<!-- __QUERY__ -->\n');
document.write ('\n');
document.write ('<style type="text/css">\n');
document.write ('<!--\n');
document.write ('.ad_partPosition{\n');
document.write ('	margin:0;\n');
document.write ('	padding:0;\n');
document.write ('}\n');
document.write ('\n');
document.write ('.ad_spLink, .ad_spText, .ad_spName, .ad_spTitle {\n');
document.write ('	font-size: 10px;\n');
document.write ('	font-weight: normal;\n');
document.write ('	padding:0;\n');
document.write ('	margin:0;\n');
document.write ('	color: #666666;\n');
document.write ('}\n');
document.write ('\n');
document.write ('.ad_spTitle, .ad_spName { font-weight: bold; }\n');
document.write ('\n');
document.write ('.ad_spText, .ad_spName { font-style: italic; }\n');
document.write ('\n');
document.write ('.ad_spName { color: #888888; }\n');
document.write ('-->\n');
document.write ('</style>\n');
document.write ('<!-- Make Changes Here -->\n');
document.write ('<div class="ad_partPosition">\n');
document.write ('    <p class="ad_spTitle">Studio of the Future</p>\n');
document.write ('    <p class="ad_spLink"><a href="http://www.weather.com/RealMedia/ads/click_lx.ads/www.weather.com/f/r/p/home/368030820/WXPartner3/13893_CISCO_Q408_28831185/13893_WxPart_Cisco_050108.html/64356563643031363438376466613430?http://www.weather.com/tv/studio/index.html?from=homepage_pp">The Weather Channel is going HD. Get an inside look.</a></p>\n');
document.write ('    <p class="ad_spText">in partnership with</p>\n');
document.write ('    <p class="ad_spName">Cisco</p>\n');
document.write ('</div><IMG BORDER="0" SRC="weather.com_files/blank.gif" style="position:absolute;top:0px;left:0px;width:0px;height:0px;" />');
}
if (position == 'Hidden1') {
document.write ('<A HREF="http://www.weather.com/RealMedia/ads/click_lx.ads/www.weather.com/f/r/p/home/1147850196/Hidden1/13673_HOME_DEPOT_TRAC_29086242/13673_HOMEDEPOT_track39_1X1.gif/64356563643031363438376466613430?pdsrch=300x235" target="_blank"><IMG BORDER="0" SRC="weather.com_files/blank.gif"  ALT="" ></A><IMG BORDER="0" SRC="weather.com_files/blank.gif" style="position:absolute;top:0px;left:0px;width:0px;height:0px;" />');
}
if (position == 'Hidden2') {
document.write ('<A HREF="http://www.weather.com/RealMedia/ads/click_lx.ads/www.weather.com/f/r/p/home/692644183/Hidden2/default/empty.gif/64356563643031363438376466613430?pdsrch=300x235" target="_blank"><IMG BORDER="0" SRC="weather.com_files/blank.gif"  WIDTH=2 HEIGHT=2 ALT="" BORDER=0></A><IMG BORDER="0" SRC="weather.com_files/blank.gif" style="position:absolute;top:0px;left:0px;width:0px;height:0px;" />');
}
}
