if(!a10){var a10={};
}var param="";
a10.ajax={};
a10.anim={};
a10.browser={};
a10.event={};
a10.util={};
a10.array={};
a10.simulate={};
a10.element={};
a10.form={};
a10.logToNativeConsole=false;
a10.logToDebugPane=false;
a10.debugPaneId="_ask_debug";
function $(A){return(typeof A=="string")?document.getElementById(A):A;
}function $F(B){var A=document.getElementsByName(B);
if(A&&A.length>0){return A[0].value;
}return"";
}a10.initDebugPane=function(){if((typeof (window)!="undefined"&&window.console&&window.console.log)||(typeof (opera)!="undefined"&&opera.postError)){a10.printToNativeConsole=true;
}var A="document.getElementById('"+a10.debugPaneId+"').style.display='none'";
if(a10.browser.isIE6()){document.write('<div id="'+a10.debugPaneId+'" style="position:absolute;left:0px;bottom:0px;width:100%;z-index:10;height:130px;color:green;overflow:auto;background-color:#FFF;border-top:solid 5px #000"><input type="button" name="close" value="Close" style="right:0px;top:0px;position:absolute;width:100px" onclick="'+A+'"></div>');
}else{document.write('<div id="'+a10.debugPaneId+'" style="position:fixed;bottom:0px;left:0px;width:100%;height:130px;color:green;overflow:auto;background-color:#FFF;border-top:solid 5px #000"><input type="button" name="close" value="Close" style="right:0px;top:0px;position:absolute;width:100px" onclick="'+A+'"></div>');
}a10.logToDebugPane=true;
};
a10.debug=function(B){if(a10.logToDebugPane){var A=document.createElement("span");
A.innerHTML="DEBUG: "+B;
$(a10.debugPaneId).appendChild(A);
$(a10.debugPaneId).appendChild(document.createElement("br"));
}if(a10.printToNativeConsole){B="DEBUG: "+B;
if(typeof (window)!="undefined"&&window.console&&window.console.log){window.console.log(B.replace(/%/g,"\uFF05"));
}else{if(typeof (opera)!="undefined"&&opera.postError){opera.postError(B);
}}}};
a10.anim.fadeIn=function(D,C,B){var A=$(D);
if(A){a10.anim.fadeLoop(A,0,1,C,B);
}};
a10.anim.fadeOut=function(D,C,B){var A=$(D);
if(A){a10.anim.fadeLoop(A,1,0,C,B);
}};
a10.anim.fadeOutToOpacity=function(E,D,A,C){var B=$(E);
if(B){a10.anim.fadeLoop(B,1,A,D,C);
}};
a10.anim.fadeLoop=function(C,G,B,F,E){var D=(F/4)*1000;
var A=((B-G)/4);
a10.element.setOpacity(C,G);
if(C.style.display=="none"&&A>0){C.style.display="";
}a10.anim.fadeLoop.step(C,A,B,D,E);
};
a10.anim.fadeLoop.step=function(C,A,B,E,F){var D=a10.element.getOpacity(C);
if((A>0&&D>=B)||(A<0&&D<=B)){a10.element.setOpacity(C,B);
if(B==0){C.style.display="none";
}if(F){F();
}}else{a10.element.setOpacity(C,(D+A));
setTimeout(function(){a10.anim.fadeLoop.step(C,A,B,E,F);
},E);
}};
a10.anim.slideX=function(E,D,B,C){var A=$(E);
if(A){a10.anim.slideLoop(A,parseInt(A.style.left),B,D,C);
}};
a10.anim.slideLoop=function(C,G,B,F,E){var D=(F/10)*1000;
var A=((B-G)/10);
a10.anim.slideLoop.step(C,A,B,D,E);
};
a10.anim.slideLoop.step=function(C,A,B,E,F){var D=parseInt(C.style.left);
if((A>0&&D>=B)||(A<0&&D<=B)){C.style.left=B+"px";
if(F){F();
}}else{C.style.left=(D+A)+"px";
setTimeout(function(){a10.anim.slideLoop.step(C,A,B,E,F);
},E);
}};
a10.anim.shake=function(G,B,F,E){var A=$(G);
if(A){var C=parseInt(A.style.left);
var D=(F/25)*1000;
a10.anim.shake.step(A,B,isNaN(C)?0:C,D,E);
}};
a10.anim.shake.step=function(B,A,F,D,E){var C=parseInt(B.style.left);
C=isNaN(C)?0:C;
if(A==0){B.style.left=F+"px";
if(E){E();
}}else{if(C==F){B.style.left=(C+A)+"px";
}else{B.style.left=(C+A*2)+"px";
}if(A>0){A=A*-1;
}else{A=(A*-1)-5;
}setTimeout(function(){a10.anim.shake.step(B,A,F,D,E);
},D);
}};
a10.ajax.getRequestObj=function(){if(window.XMLHttpRequest){return new XMLHttpRequest();
}else{if(window.ActiveXObject){try{return new ActiveXObject("Msxml2.XMLHTTP");
}catch(B){try{return new ActiveXObject("Microsoft.XMLHTTP");
}catch(A){return null;
}}}else{return null;
}}};
a10.ajax.get=function(C,B,A){a10.debug("[a10.ajax.get()]:"+C);
var D=a10.ajax.getRequestObj();
if(D){D.onreadystatechange=function(){if(D.readyState==4){if(D.status==200&&typeof (B)=="function"){B(D);
}else{if(typeof (A)=="function"){A(D);
}}try{delete D["onreadystatechange"];
}catch(E){}}};
if(param!=""){if(C.indexOf("?")!=-1){C=C+"&"+param;
}else{C=C+"?"+param;
}}param="";
D.open("GET",C,true,"","");
D.send(null);
return D;
}else{if(A){A("Error creating XHR");
}else{a10.debug("Error creating XHR");
}return null;
}};
a10.ajax.abort=function(A){if(A){A.abort();
}};
a10.browser.buildParamString=function(E){var D="";
if(!(typeof (E)=="undefined"||E===null)){var C=a10.util.sortProperties(E);
var B=true;
for(prop in C){var A=encodeURIComponent(C[prop]);
A=A.replace(/'/g,"%27");
if(A!=null&&A!=""){if(!B){D+="&";
}else{B=false;
}D+=prop+"="+A;
}}}return D;
};
a10.browser.isIE=function(){return navigator.userAgent.toLowerCase().indexOf("msie")!=-1;
};
a10.browser.isIE6=function(){return navigator.userAgent.toLowerCase().indexOf("msie 6.")!=-1;
};
a10.browser.isIE7=function(){return navigator.userAgent.toLowerCase().indexOf("msie 7.")!=-1;
};
a10.browser.isOpera=function(){return navigator.userAgent.toLowerCase().indexOf("opera")!=-1;
};
a10.browser.version=function(){if(!a10.browser._version){if(a10.browser.isIE()){a10.browser._version=a10.browser.parseVersionStr("msie");
}if(a10.browser.isFirefox()){a10.browser._version=a10.browser.parseVersionStr("firefox");
}if(a10.browser.isNetscape()){a10.browser._version=a10.browser.parseVersionStr("netscape");
}if(a10.browser.isOpera()){a10.browser._version=a10.browser.parseVersionStr("opera");
}if(a10.browser.isSafari()){var A=a10.browser.parseVersionStr("safari");
if(A>521){A=3;
}else{if(A>412){A=2;
}else{A=1;
}}a10.browser._version=A;
}}return a10.browser._version;
};
a10.browser.isFirefox=function(){return navigator.userAgent.toLowerCase().indexOf("firefox")!=-1;
};
a10.browser.isNetscape=function(){return navigator.userAgent.toLowerCase().indexOf("netscape")!=-1;
};
a10.browser.isSafari=function(){return navigator.userAgent.toLowerCase().indexOf("safari")!=-1;
};
a10.browser.parseVersionStr=function(G,A){var D="";
if(G||A){var I=navigator.userAgent.toLowerCase();
var C=(!A)?(I.indexOf(G)+G.length+1):A;
if(C>=0){var H=I.substring(C);
for(var E=0;
E<H.length;
E++){var F=H.substring(E,E+1);
if(!isNaN(F)&&F!=" "){D+=F;
}else{if(F=="."){D+=F;
}else{break;
}}}}}var B=D.indexOf(".");
if(B!=-1){var J=D.indexOf(".",B+1);
if(J!=-1){D=D.substring(0,J);
}}return D;
};
a10.browser.innerDimension=function(){var A,B;
if(self.innerHeight){A=self.innerWidth;
B=self.innerHeight;
}else{if(document.documentElement&&document.documentElement.clientHeight){A=document.documentElement.clientWidth;
B=document.documentElement.clientHeight;
}else{if(document.body){A=document.body.clientWidth;
B=document.body.clientHeight;
}}}return[A,B];
};
a10.util.sortProperties=function(F){var G=[];
var E;
for(var H in F){var B;
try{B=F[H];
}catch(E){continue;
}G.push([H,B]);
}var A={};
var D=[];
G.sort();
for(var C=0;
C<G.length;
C++){D=G[C];
A[D[0]]=D[1];
}return A;
};
a10.util.findPos=function(A){var B=curtop=0;
if(A&&A.offsetParent){B=A.offsetLeft;
curtop=A.offsetTop;
while(A=A.offsetParent){B+=A.offsetLeft;
curtop+=A.offsetTop;
}}return[B,curtop];
};
a10.util.scrollLeft=function(){return window.pageXOffset||document.documentElement.scrollLeft||document.body.scrollLeft||0;
};
a10.util.scrollTop=function(){return window.pageYOffset||document.documentElement.scrollTop||document.body.scrollTop||0;
};
a10.util.trim=function(A){return A.replace(/^\s+/g,"").replace(/\s+$/g,"");
};
a10.util.htmlEncode=function(A){return A.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
};
a10.util.isEmpty=function(A){if(A){return A.match(/^\s*$/)!=null;
}else{return true;
}};
a10.util.ie6PNGSpriteHack=function(H){if(a10.browser.isIE6()){var G=H.style.backgroundImage.substr(4,H.style.backgroundImage.length-5);
var B=H.style.backgroundPosition.split(" ");
var F=B.length>=1?parseInt(B[0]):0;
var C=B.length>=2?parseInt(B[1]):0;
F=isNaN(F)?0:F;
C=isNaN(C)?0:C;
var E=parseInt(H.style.width);
var A=parseInt(H.style.height);
E=isNaN(E)?0:E;
A=isNaN(A)?0:A;
H.style.backgroundImage="none";
H.style.overflow="hidden";
var D=document.createElement("div");
D.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+G+"', sizingMethod='crop')";
D.style.position="relative";
D.style.left=F+"px";
D.style.top=C+"px";
D.style.width=-F+E+"px";
D.style.height=-C+A+"px";
H.appendChild(D);
}};
a10.util.truncate=function(B,C){if(B==null){return null;
}C=C||30;
var A="...";
return B.length>C?B.slice(0,C-A.length)+A:B;
};
if(!!document.evaluate){a10.util._getElementsByXPath=function(F,A){var C=[];
var E=document.evaluate(F,$(A)||document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);
for(var B=0,D=E.snapshotLength;
B<D;
B++){C.push(E.snapshotItem(B));
}return C;
};
a10.util.getElementsByClassName=function(B,A){var C=".//*[contains(concat(' ', @class, ' '), ' "+B+" ')]";
return a10.util._getElementsByXPath(C,A);
};
}else{a10.util.getElementsByClassName=function(G,I){var D=($(I)||document.body).getElementsByTagName("*");
var A=[],B,F=new RegExp("(^|\\s)"+G+"(\\s|$)");
for(var E=0,C=D.length;
E<C;
E++){B=D[E];
var H=B.className;
if(H.length==0){continue;
}if(H==G||H.match(F)){A.push(B);
}}return A;
};
}a10.util.extend=function(A,C){for(var B in C){A[B]=C[B];
}return A;
};
a10.util.subclass=function(C,A){function B(){}B.prototype=A.prototype;
C.prototype=new B();
C.prototype.constructor=C;
C.baseConstructor=A;
C.superClass=A.prototype;
};
a10.util.getComputedStyle=function(A){A=$(A);
return A.currentStyle||document.defaultView.getComputedStyle(A,null)||window.getComputedStyle(A,null);
};
a10.util.generatePagingStrip=function(F,E,S,J,T,M){var O=1;
var L=10;
var H="";
var P=1;
var B="";
var R="";
var K=1;
var N=10;
var Q=0;
var G=Math.ceil(J/S);
var U=(S>E)?0:(E%S);
O=(U==0)?Math.round((E+S)/S):Math.ceil(E/S);
if(G==1&&E!=0){G+=1;
O=G;
}else{if((E+S)>=J){if(O<G){G=O;
}}}var C=E+((G-O)*S);
if(C>=J){C=J-1;
}if(((E%S)!=0)&&((C+S)<J)){G+=1;
}if(G>10){K=O-5;
N=O+4;
if(K<1){Q=Math.abs(K)+1;
K=K+Q;
N=N+Q;
}if(N>G){Q=N-G;
K=K-Q;
N=N-Q;
}}else{if(G<N){N=G;
}}var A=$("ps");
if(A){if(N==1){H="";
}else{if(O>1){B="&pstart="+(E-S);
R="&page="+(O-1);
H+='&#160;&#160;<a class="L7" style="text-decoration:none" href="'+F+B+R+'">'+T+"</a>";
}else{H+='&#160;&#160;<span class="disabled">'+T+"</span>";
}H+="<ul>";
for(P=K;
P<=N;
P++){if(P==O){H+='<li id="cur" class="T13 b">&#160;&#160;'+P+"&#160;&#160;</li>";
}else{var I=P-O;
var D=(E+(I*S));
if(D<0){D=0;
}if(D>J){D=J-1;
}B="&pstart="+D;
R="&page="+(O+I);
H+='<li><a class="pl L7 b" style="text-decoration:none" href="'+F+B+R+'">&#160;&#160;'+P+"&#160;&#160;</a></li>";
}}H+="</ul>";
if(O!=G){B="&pstart="+(E+S);
R="&page="+(O+1);
H+='<a class="L7" style="text-decoration:none" href="'+F+B+R+'">&#160;'+M+"</a>";
}else{H+='<span class="disabled">'+M+"</span>";
}}A.innerHTML=H;
}};
a10.util.uniqueID=(function(){var A=0;
return function(){return A++;
};
})();
a10.util.insertStyleSheet=function(B,D){var C=document.getElementsByTagName("head")[0];
var A=document.createElement("link");
A.type="text/css";
A.rel="stylesheet";
A.href=B;
A.media="screen";
A.className=D;
C.appendChild(A);
};
a10.util.insertScript=function(B,D){var C=document.getElementsByTagName("head")[0];
var A=document.createElement("script");
A.type="text/javascript";
A.src=B;
A.className=D;
C.appendChild(A);
};
a10.util.removeElementsWithClass=function(C){var B=document.getElementsByTagName("head")[0];
var D=a10.util.getElementsByClassName(C,B);
D=D.concat(a10.util.getElementsByClassName(C,document.body));
for(var A=0;
A<D.length;
A++){var E=D[A];
E.parentNode.removeChild(E);
}};
a10.util.getMyStuffTitle=function(D,E,B,A){var C=D;
var F=B+"'s Stuff";
if(B!=""){if(A=="en_US"||A=="en_GB"||A=="nl_NL"){if(B.toLowerCase().charAt(B.length)=="s"||B.toLowerCase().charAt(B.length)=="z"){C=E;
}}else{if(A=="fr_FR"){if(B.toLowerCase().charAt(0)=="a"||B.toLowerCase().charAt(0)=="e"||B.toLowerCase().charAt(0)=="i"||B.toLowerCase().charAt(0)=="o"||B.toLowerCase().charAt(0)=="u"||B.toLowerCase().charAt(0)=="y"||B.toLowerCase().charAt(0)=="h"){C=E;
}}}if(C.indexOf("{0}")!=-1){F=C.replace("{0}",B);
}}return F;
};
a10.array.removeElementAtIndex=function(A,B){if(A<0||A>=B.length){return null;
}return B.splice(A,1)[0];
};
a10.array.indexOf=function(A,C){for(var B=0;
B<C.length;
B++){if(C[B]==A){return B;
}}return -1;
};
a10.simulate.click=function(A){this._mouseEvent(A,"click");
};
a10.simulate.mousedown=function(A){this._mouseEvent(A,"mousedown");
};
a10.simulate._mouseEvent=function(C,B){C=$(C);
if(document.createEvent){var A=document.createEvent("MouseEvents");
A.initEvent(B,true,true);
C.dispatchEvent(A);
}else{if(document.createEventObject){var A=document.createEventObject();
C.fireEvent("on"+B,A);
}}};
a10.event.addListener=function(D,B,A){D=$(D);
if(D){if(D.addEventListener){D.addEventListener(B,A,false);
}else{if(D.attachEvent){if(!A["_addListenerID"]){A["_addListenerID"]=a10.util.uniqueID();
}var C=B+A["_addListenerID"];
if(D[C]){return ;
}D["fn"+C]=A;
D[C]=function(){D["fn"+C](window.event);
};
D.attachEvent("on"+B,D[C]);
}}}};
a10.event.removeListener=function(D,B,A){D=$(D);
if(D.removeEventListener){D.removeEventListener(B,A,false);
}else{if(D.detachEvent){var C=B+A["_addListenerID"];
D.detachEvent("on"+B,D[C]);
D[C]=null;
D["fn"+C]=null;
}}};
a10.event.element=function(A){return A.target||A.srcElement;
};
a10.event.cancelDefaultAction=function(A){if(A.preventDefault){A.preventDefault();
}else{A.returnValue=false;
}};
a10.element.visible=function(B){var A=$(B);
if(A){return A.style.display!="none";
}return false;
};
a10.element.toggle=function(A){A=$(A);
a10.element[a10.element.visible(A)?"hide":"show"](A);
return A;
};
a10.element.hide=function(B){var A=$(B);
if(A){A.style.display="none";
}return B;
};
a10.element.show=function(B){var A=$(B);
if(A){A.style.display="";
}return B;
};
a10.element.containsPoint=function(C,A,E,B){if(C){var D=a10.util.findPos(C);
if(B){D[1]-=a10.util.scrollTop();
}else{if(a10.browser.isIE6()){D[0]-=document.body.scrollLeft;
D[1]-=document.body.scrollTop;
}}return A>=D[0]&&A<(D[0]+C.offsetWidth)&&E>=D[1]&&E<(D[1]+C.offsetHeight);
}};
a10.element.setOpacity=function(A,D){A=$(A);
if(!A){return ;
}if(a10.browser.isIE()){var C=A.style.filter;
var B=A.style;
if(D==1||D===""){B.filter=C.replace(/alpha\([^\)]*\)/gi,"");
return ;
}else{if(D<0.00001){D=0;
}}B.filter=C.replace(/alpha\([^\)]*\)/gi,"")+"alpha(opacity="+(D*100)+")";
}else{A.style.opacity=(D==1||D==="")?"":(D<0.00001)?0:D;
}};
a10.element.getOpacity=function(A){A=$(A);
if(A){if(a10.browser.isIE()){var B=(A.style.filter||"").match(/alpha\(opacity=(.*)\)/);
if(B&&B[1]){return parseFloat(B[1])/100;
}else{return 1;
}}else{var B=A.style.opacity;
return B?parseFloat(B):1;
}}return null;
};
a10.element.getHeight=function(A){return this.getDimensions(A).height;
};
a10.element.getWidth=function(A){return this.getDimensions(A).width;
};
a10.element.getDimensions=function(C){C=$(C);
if(!C){return{width:null,height:null};
}var B=C.style;
var F=B.visibility;
var D=B.position;
var A=B.display;
B.visibility="hidden";
B.position="absolute";
B.display="block";
var G=C.offsetWidth;
var E=C.clientHeight;
B.display=A;
B.position=D;
B.visibility=F;
return{width:G,height:E};
};
a10.IFrameCover=function(A,B){this.element=$(A);
this.iframe=null;
if(B){this.leftOffset=B.left||0;
this.topOffset=B.top||0;
this.widthOffset=B.width||0;
this.heightOffset=B.height||0;
}else{this.leftOffset=this.topOffset=this.widthOffset=this.heightOffset=0;
}};
a10.IFrameCover.prototype={show:function(){this.iframe=document.createElement("iframe");
this.iframe.src="about:blank";
this.iframe.scrolling="no";
this.iframe.frameBorder=0;
this.iframe.style.position="absolute";
this.iframe.style.zIndex=0;
this.iframe.id=this.element.id+"_IFrameCover";
document.body.appendChild(this.iframe);
this.reposition();
},hide:function(){if(this.iframe==null){return ;
}document.body.removeChild(this.iframe);
this.iframe=null;
},reposition:function(){if(this.iframe==null){return ;
}var B=a10.util.findPos(this.element);
var A=a10.element.getDimensions(this.element);
this.iframe.style.left=B[0]+this.leftOffset+"px";
this.iframe.style.top=B[1]+this.topOffset+"px";
this.iframe.style.width=A.width+this.widthOffset+"px";
this.iframe.style.height=A.height+this.heightOffset+"px";
}};
a10.form.serialize=function(A){return this.serializeElements(this.getElements(A));
};
a10.form.getElements=function(C){var D=[];
var B=$(C).getElementsByTagName("*");
for(var A=0;
A<B.length;
A++){if(this.serializers[B[A].tagName.toLowerCase()]){D.push(B[A]);
}}return D;
};
a10.form.serializeElements=function(F){var A="";
for(var C=0;
C<F.length;
C++){var G=F[C];
if(!G.disabled&&G.name){var B=G.name;
var E=this.getValue(G);
if(E!=undefined){var D=B+"="+encodeURIComponent(E);
if(A==""){A=D;
}else{A+="&"+D;
}}}}return A;
};
a10.form.getValue=function(A){A=$(A);
var B=A.tagName.toLowerCase();
return this.serializers[B](A);
};
a10.form.serializers={input:function(A){switch(A.type.toLowerCase()){case"checkbox":case"radio":return this.inputSelector(A);
default:return this.textarea(A);
}},inputSelector:function(A){return A.checked?A.value:null;
},textarea:function(A){return A.value;
},select:function(A){return this[A.type=="select-one"?"selectOne":"selectMany"](A);
},selectOne:function(B){var A=B.selectedIndex;
return A>=0?this.optionValue(B.options[A]):null;
},selectMany:function(D){var A,E=D.length;
if(!E){return null;
}for(var C=0,A=[];
C<E;
C++){var B=D.options[C];
if(B.selected){A.push(this.optionValue(B));
}}return A;
},optionValue:function(A){return A.value;
}};

JSONscriptRequest.scriptCounter=1;
JSONscriptRequest.idPrefix="JscriptId";
function JSONscriptRequest(A){this.fullUrl=A;
this.noCacheIE="&noCacheIE="+(new Date()).getTime();
this.headLoc=document.getElementsByTagName("head").item(0);
this.scriptId=JSONscriptRequest.idPrefix+JSONscriptRequest.scriptCounter++;
}JSONscriptRequest.prototype.makeRequest=function(){this.scriptObj=document.createElement("script");
this.scriptObj.setAttribute("type","text/javascript");
this.scriptObj.setAttribute("charset","utf-8");
this.scriptObj.setAttribute("id",this.scriptId);
if(this.fullUrl.indexOf("?")==-1){this.scriptObj.setAttribute("src",this.fullUrl+"?"+this.noCacheIE);
}else{this.scriptObj.setAttribute("src",this.fullUrl+this.noCacheIE);
}a10.debug("Making Json request: "+this.fullUrl);
this.headLoc.appendChild(this.scriptObj);
};
JSONscriptRequest.prototype.removeScriptTag=function(){this.headLoc.removeChild(this.scriptObj);
};
JSONscriptRequest.removeAllScriptTags=function(){var C=document.getElementsByTagName("head").item(0);
var B;
if(C){var A=C.childNodes;
for(B=0;
B<A.length;
B++){if(A[B].nodeType==1&&A[B].tagName=="SCRIPT"&&A[B].id.indexOf(JSONscriptRequest.idPrefix)==0){C.removeChild(A[B]);
}}}};

var Cookie={};
Cookie.isEnabled=function(){return window.navigator.cookieEnabled;
};
Cookie.getCookie=function(D,C){var E=document.cookie;
var F=E.indexOf(D+"=");
var A=F+D.length+1;
if((!F)&&(D!=E.substring(0,D.length))){return null;
}if(F==-1){return null;
}var B=E.indexOf(";",A);
if(B==-1){B=E.length;
}return C?E.substring(A,B):unescape(E.substring(A,B));
};
Cookie.deleteCookie=function(A,C,B){if(Cookie.getCookie(A)){document.cookie=A+"="+((C)?"; path="+C:"")+((B)?"; domain="+B:"")+"; expires=Thu, 01-Jan-70 00:00:01 GMT";
}};
Cookie.setCookie=function(B,D,A,F,C,E){document.cookie=B+"="+escape(D)+((A)?"; expires="+A.toGMTString():"")+((F)?"; path="+F:"")+((C)?"; domain="+C:"")+((E)?"; secure":"");
};

if(!a10){var a10={};
}a10.ss={};
a10.ss.lastSuccessfulQuery=null;
a10.ss.currentQuery=null;
a10.ss.currentResults=new Array();
a10.ss.pauseTimeoutID=null;
a10.ss.selectedIndex=-1;
a10.ss.pageHasMadeRequest=false;
a10.ss.formSubmitted=false;
a10.ss.hidden=true;
a10.ss.PAUSE_PERIOD=201;
a10.ss.FADE_SPEED=0.07;
a10.ss.skipNextArrowKeyEvent=false;
a10.ss.inputId="";
a10.ss.uiId="";
a10.ss.uiBodyId="";
a10.ss.offsetLeft=10;
a10.ss.ssQsrcDefault="2352";
a10.ss.ssQsrcHP="178";
a10.ss.qsrc=a10.ss.ssQsrcDefault;
a10.ss.init=function(D,A,B,C){a10.ss.inputId=D;
a10.ss.uiId=A;
a10.ss.uiBodyId=B;
if("event" in a10){a10.event.addListener(document.getElementById(D),"keyup",a10.ss.searchSuggestion);
a10.event.addListener(document.documentElement,"click",a10.ss.closePopup);
}if(C){a10.ss.PAUSE_PERIOD=C;
}};
a10.ss.closePopup=function(){var A=$(a10.ss.uiId);
if(A){A.style.display="none";
}};
a10.ss.searchSuggestion=function(B){var A=Cookie.getCookie("gset");
if(a10.ss.hp=="true"){a10.ss.qsrc=a10.ss.ssQsrcHP;
}if((!A)||(A.indexOf("ss=0")==-1)){if(!B){B=window.event;
}switch(B.keyCode){case 38:if((navigator.userAgent.indexOf("AppleWebKit")!=-1)&&(navigator.appVersion.indexOf("Version/")==-1)){if(a10.ss.skipNextArrowKeyEvent){a10.ss.skipNextArrowKeyEvent=false;
return ;
}else{a10.ss.skipNextArrowKeyEvent=true;
}}a10.ss.handleKey(38);
return ;
case 40:if((navigator.userAgent.indexOf("AppleWebKit")!=-1)&&(navigator.appVersion.indexOf("Version/")==-1)){if(a10.ss.skipNextArrowKeyEvent){a10.ss.skipNextArrowKeyEvent=false;
return ;
}else{a10.ss.skipNextArrowKeyEvent=true;
}}a10.ss.handleKey(40);
return ;
case 13:a10.ss.formSubmitted=true;
$(a10.ss.uiId).style.display="none";
return ;
case 9:case 18:return ;
}if(a10.ss.currentQuery==$(a10.ss.inputId).value){return ;
}a10.ss.currentQuery=$(a10.ss.inputId).value;
if(a10.ss.pauseTimeoutID){clearTimeout(a10.ss.pauseTimeoutID);
a10.ss.pauseTimeoutID=null;
}a10.ss.pauseTimeoutID=setTimeout(function(){a10.ss.pauseTimeoutID=null;
a10.ss.searchSuggestHandler();
},a10.ss.PAUSE_PERIOD);
}};
a10.ss.updateQsrc=function(){if(a10.ss.selectedIndex!=-1){var A=document.getElementById("qsrc");
if(A){A.value=a10.ss.qsrc;
}}};
a10.ss.select=function(C){var A=a10.ss.currentResults.length;
function D(E){if(E>=0&&E<A){el=a10.ss.currentResults[E];
el.className="";
}}D(a10.ss.selectedIndex);
var B=a10.ss.lastSuccessfulQuery;
if(C>=0&&C<A){el=a10.ss.currentResults[C];
links=el.getElementsByTagName("a");
if(links.length==0){return 0;
}el.className="selected";
}else{a10.ss.setValue($(a10.ss.inputId),B);
}a10.ss.selectedIndex=C;
return 1;
};
a10.ss.handleKey=function(F){var B=38;
var C=40;
var A=a10.ss.currentResults.length;
function D(G){if(G<-1){return A-1;
}else{if(G>=A){return -1;
}else{return G;
}}}if($(a10.ss.uiId).style.display!="none"&&A>0){var E=a10.ss.selectedIndex;
if(F==B){delta=-1;
}else{if(F==C){delta=+1;
}}E+=delta;
E=D(E);
if(!a10.ss.select(E)){E+=delta;
E=D(E);
a10.ss.select(E);
}a10.ss.copyToInput(E);
}};
a10.ss.copyToInput=function(A){if(A<0){return ;
}el=a10.ss.currentResults[A];
link=el.getElementsByTagName("a")[0];
query=link.innerText||link.textContent;
a10.ss.setValue($(a10.ss.inputId),query);
a10.ss.currentQuery=query;
};
a10.ss.searchSuggestHandler=function(){function D(G,F){for(var E=0;
E<F.length;
E++){if(F[E].innerHTML.toLowerCase().indexOf(G.toLowerCase())!=0){return false;
}}return true;
}var C=$(a10.ss.inputId).value;
var B;
if(a10.ss.currentResults.length>0&&((C==a10.ss.lastSuccessfulQuery)||(C.length>a10.ss.lastSuccessfulQuery.length&&D(C,a10.ss.currentResults)))){return ;
}var A=a10.ss.lastSuccessfulQuery?a10.ss.lastSuccessfulQuery.toLowerCase():null;
if(a10.ss.currentResults.length==0&&C.toLowerCase().indexOf(A)==0){return ;
}if(C.length>1){a10.ss.pageHasMadeRequest=true;
a10.ss2.execute(C,_country,_language);
}else{a10.ss.lastSuccessfulQuery=null;
a10.ss.currentResults=new Array();
if($(a10.ss.uiId).style.display!="none"){a10.ss.transitionSuggestion(true);
}}};
function suggestCallBack(C){if(a10.ss.formSubmitted){return ;
}if(!a10.ss.pageHasMadeRequest){return ;
}var E=a10.ss2.getQuery(C);
if(E!=$(a10.ss.inputId).value.toLowerCase()){return ;
}a10.ss.selectedIndex=-1;
a10.ss.lastSuccessfulQuery=E;
var A=a10.ss2.getSuggestions(C);
if(A.length>0){var D="";
_origin=$F("o");
if(_origin==""){_origin=0;
}_partnerID=$F("l");
if(_partnerID==""){_partnerID="dir";
}_siteID=$F("siteid");
if(_siteID==""){_siteID="";
}else{_siteID="&siteid="+$F("siteid");
}D+=a10.ss2.createSuggestions(A,a10.ss.qsrc,_origin,_partnerID,_siteID,a10.ss.getCountry());
if(typeof _disableSSApplicable=="undefined"){_disableSSApplicable=true;
}if(_disableSSApplicable){if(GlobalNav.Variables._isEraser||GlobalNav.Variables._isEraserOptOutEligible){D+="<div id='disablediv'><a id='ssdisable' href='#' onclick='askerasersuppressDialog.show();return false;' class='L3'>"+_disableSSMsg+"</a></div>";
}else{var B=Cookie.getCookie("gset");
if((!B)||(B.indexOf("ss=0")==-1)){D+="<div id='disablediv'><a id='ssdisable' href='#'  onclick='a10.ss.turnOffSS()' class='L3'>"+_disableSSMsg+"</a></div>";
}}}$(a10.ss.uiBodyId).innerHTML=D;
a10.ss.currentResults=$("suggestlist").getElementsByTagName("li");
if($(a10.ss.uiId).style.display=="none"){a10.ss.transitionSuggestion(false);
}}else{a10.ss.clearSuggestions();
}a10.ss2.postRender();
}a10.ss.getCountry=function(){var B=$("alltop")||$("all");
var A=$("ctrytop")||$("ctry");
var D=$("langtop")||$("lang");
if(!B||!A||!D){return"";
}var C="all";
if(B.checked){C="all";
}else{if(A.checked){C="ctry";
}else{if(D.checked){C="lang";
}}}return C;
};
a10.ss.clearSuggestions=function(){a10.ss.currentResults=new Array();
$(a10.ss.uiBodyId).innerHTML='<div class="lh18"><span style="color:gray;padding-left:6px;">'+_noSSFoundMsg+'</span></div><div class="pb20" />';
};
a10.ss.reset=function(){a10.ss.currentResults=new Array();
if(a10.ss.pauseTimeoutID){clearTimeout(a10.ss.pauseTimeoutID);
a10.ss.pauseTimeoutID=null;
}a10.ss.pageHasMadeRequest=false;
a10.ss.lastSuccessfulQuery=null;
a10.ss.hidden=true;
};
a10.ss.transitionSuggestion=function(A){a10.ss.hidden=A;
if(A){$(a10.ss.uiId).style.display="none";
a10.ss.transitionSuggestionDone();
}else{a10.ss.transitionSuggestionDone();
}};
a10.ss.setValue=function(A,B){A.value=B;
if(navigator.userAgent.indexOf("AppleWebKit")&&A.setSelectionRange){A.setSelectionRange(A.value.length,A.value.length);
}};
a10.ss.transitionSuggestionDone=function(){if(!a10.ss.hidden){$(a10.ss.uiId).style.display="";
}};
a10.ss.turnOffSS=function(){var C=Cookie.getCookie("gset");
var A=new Date();
A.setFullYear(A.getFullYear()+2);
var E="ss=0";
if((C)){if(C.indexOf("&ss=1")!=-1){var B=C.split("&ss=1");
E=B.join("");
}else{if(C.indexOf("&ss=0")!=-1){var B=C.split("&ss=0");
E=B.join("");
}}E+="&ss=0";
}Cookie.deleteCookie("gset","/");
document.cookie="gset="+E+"; expires="+A.toGMTString()+"; path=/; domain=.ask.com";
var D=$("q");
if(D){D.focus();
}};
if(typeof ssloaded!="undefined"){ssloaded();
}
if(!a10){var a10={};
}a10.nb={};
a10.nb.navBubble=null;
a10.nb.clicked=false;
a10.nb.srcElement=null;
a10.nb.offsetTop=20;
a10.nb.offsetLeft=-15;
a10.nb.position="fixed";
a10.nb.bodyWidth="";
a10.nb.repositionBubble=function(){if(a10.nb.srcElement&&a10.nb.navBubble&&a10.nb.navBubble.style.display!="none"){var A=a10.util.findPos(a10.nb.srcElement);
a10.nb.navBubble.style.top=(A[1]+a10.nb.offsetTop)+"px";
a10.nb.navBubble.style.left=(A[0]+a10.nb.offsetLeft)+"px";
}};
a10.nb.md=function(H,G){var B=-1;
var A=($F("bizWhatFld")=="")?$F("a"):$F("bizWhatFld");
var I=null;
var E=H.href.indexOf("siteid=");
if(E!=-1){I=H.href.substr(E+7,H.href.length);
}var F=null;
var C=H.href.indexOf("dm=");
if(C!=-1){var D=H.href.indexOf("&",C+1);
if(D!=-1){F=H.href.substr(C+3,D-(C+3));
}else{F=H.href.substr(C+3);
}}if(A==""){A=$F("q");
}if(H.md){return true;
}if(G){H.href=G.replace("{0}",enc(A));
}else{if(H.href.indexOf("&q")>0){B=H.href.indexOf("&q");
H.href=H.href.substr(0,B+3)+enc(A);
}else{H.href=H.href+"&q="+enc(A);
}}if(F){H.href=H.href+"&dm="+F;
}if(I!=null){H.href=H.href+"&siteid="+I;
}if(H.href.indexOf("&o=")==-1&&$F("o")!=""){H.href=H.href+"&o="+enc($F("o"));
}if(H.href.indexOf("&l=")==-1&&$F("l")!=""){H.href=H.href+"&l="+enc($F("l"));
}if(H.href.indexOf("&dm=")==-1&&$F("dm")!=""){H.href=H.href+"&dm="+enc($F("dm"));
}if(H.href.indexOf("&siteid=")==-1&&$F("siteid")!=""){H.href=H.href+"&siteid="+enc($F("siteid"));
}H.md=1;
};
a10.nb.mde=function(A,D,C){var B=$F("q");
if(B){B=B.replace(/^\s+/g,"").replace(/\s+$/g,"");
if(B==""){A.href=C;
}else{a10.nb.md(A,D);
}}};
a10.nb.toggle=function(A){if(!A){A=window.event;
}var K;
var B=181;
var G=40;
var F=20;
var C=23;
var D=a10.nb.bodyWidth!=""?a10.nb.bodyWidth:190;
if(a10.nb.navBubble){if(a10.nb.navBubble.style.display==""){a10.nb.navBubble.style.display="none";
}else{var H=a10.util.findPos(a10.nb.srcElement);
a10.nb.navBubble.style.top=(H[1]+a10.nb.offsetTop)+"px";
a10.nb.navBubble.style.left=(H[0]+a10.nb.offsetLeft)+"px";
a10.nb.navBubble.style.display="";
a10.nb.clicked=true;
}return ;
}var J=A.target||A.srcElement;
if(J.tagName.toLowerCase()!="a"){J=J.parentNode;
}a10.nb.srcElement=J;
var H=a10.util.findPos(J);
a10.nb.navBubble=document.createElement("div");
a10.nb.navBubble.style.width="20px";
a10.nb.navBubble.style.height="20px";
a10.nb.navBubble.style.zIndex=14;
var L=(H[1]+a10.nb.offsetTop);
if(a10.browser.isIE6()){a10.nb.navBubble.style.position="absolute";
a10.nb.navBubble.style.setExpression("top","eval(document.body.scrollTop + "+(L-document.body.scrollTop)+")");
}else{a10.nb.navBubble.style.position=a10.nb.position;
a10.nb.navBubble.style.top=L+"px";
}a10.nb.navBubble.style.left=(H[0]+a10.nb.offsetLeft)+"px";
document.body.appendChild(a10.nb.navBubble);
var I=document.getElementById("navBubbleBody");
I.style.display="";
a10.nb.navBubble.appendChild(I);
K=I.offsetHeight;
if(K>=G&&K<=B){I.style.height=K+"px";
}else{I.style.height=((K>B)?B:G)+"px";
}new a10.Bubble(a10.nb.navBubble,I,D+15,0,"up",true,a10.nb.toggle);
$("navFocusAnchor").focus();
function E(){a10.nb.clicked=true;
}a10.nb.clicked=true;
};
a10.nb.close=function(){if(!a10.nb.clicked&&a10.nb.navBubble){a10.nb.navBubble.style.display="none";
}a10.nb.clicked=false;
};
if(typeof nbloaded!="undefined"){nbloaded();
}
if(!a10){var a10={};
}a10.bubble={};
a10.bubble.BORDER_WIDTH=25;
a10.bubble.SPRITE_WIDTH=554;
a10.bubble.SPRITE_HEIGHT=543;
a10.bubble.SPRITE_URL=_sharedSprite;
a10.Bubble=function(B,G,D,J,H,I,K,A,F){this.direction=H;
this.content=G;
this.container=B;
if(A){this.heightOffset=A;
}if(I){this.closeButton=document.createElement("div");
this.closeButton.title="Close";
this.closeButton.style.backgroundImage="url("+a10.bubble.SPRITE_URL+")";
this.closeButton.style.backgroundPosition="-95px -398px";
this.closeButton.style.position="absolute";
this.closeButton.style.left=(D-4)+"px";
this.closeButton.style.top="18px";
this.closeButton.style.width="11px";
this.closeButton.style.height="11px";
this.closeButton.style.cursor="pointer";
this.closeButton.style.overflow="hidden";
this.closeButton.style.zIndex=5;
this.closeButton.onclick=K;
this.container.appendChild(this.closeButton);
a10.util.ie6PNGSpriteHack(this.closeButton);
}this.bubbleTop=document.createElement("div");
this.bubbleTop.style.backgroundImage="url("+a10.bubble.SPRITE_URL+")";
this.bubbleTop.style.height=a10.bubble.BORDER_WIDTH+"px";
if(D==0){D=parseInt(G.style.width);
}this.bubbleTop.style.width=D+"px";
this.bubbleTop.style.position="absolute";
this.bubbleTop.style.top="0px";
this.bubbleTop.style.left="0px";
this.bubbleTop.style.backgroundPosition="0px 0px";
this.container.appendChild(this.bubbleTop);
a10.util.ie6PNGSpriteHack(this.bubbleTop);
this.bubbleRight=document.createElement("div");
this.bubbleRight.style.backgroundImage="url("+a10.bubble.SPRITE_URL+")";
this.bubbleRight.style.backgroundPosition="-"+(a10.bubble.SPRITE_WIDTH-a10.bubble.BORDER_WIDTH)+"px 0px";
if(J==0){if(this.content.style.height){J=parseInt(this.content.style.height)+a10.bubble.BORDER_WIDTH-10+(A?A:0);
}else{J=parseInt(this.content.offsetHeight)+(A?A:0);
}}else{J+=a10.bubble.BORDER_WIDTH-10+(A?A:0);
}this.bubbleRight.style.height=J+"px";
this.bubbleRight.style.width=a10.bubble.BORDER_WIDTH+"px";
this.bubbleRight.style.position="absolute";
this.bubbleRight.style.left=D+"px";
this.bubbleRight.style.top="0px";
this.container.appendChild(this.bubbleRight);
a10.util.ie6PNGSpriteHack(this.bubbleRight);
this.bubbleBottom=document.createElement("div");
this.bubbleBottom.style.backgroundImage="url("+a10.bubble.SPRITE_URL+")";
this.bubbleBottom.style.backgroundPosition="-"+(a10.bubble.SPRITE_WIDTH-D)+"px -"+(a10.bubble.SPRITE_HEIGHT-a10.bubble.BORDER_WIDTH)+"px";
this.bubbleBottom.style.height=a10.bubble.BORDER_WIDTH+"px";
this.bubbleBottom.style.width=D+"px";
this.bubbleBottom.style.position="absolute";
this.bubbleBottom.style.top=(parseInt(this.bubbleRight.style.height))+"px";
this.bubbleBottom.style.left=a10.bubble.BORDER_WIDTH+"px";
this.container.appendChild(this.bubbleBottom);
a10.util.ie6PNGSpriteHack(this.bubbleBottom);
this.bubbleLeft=document.createElement("div");
this.bubbleLeft.style.backgroundImage="url("+a10.bubble.SPRITE_URL+")";
this.bubbleLeft.style.backgroundPosition="0px -"+(a10.bubble.SPRITE_HEIGHT-J)+"px";
this.bubbleLeft.style.height=J+"px";
this.bubbleLeft.style.width=a10.bubble.BORDER_WIDTH+"px";
this.bubbleLeft.style.position="absolute";
this.bubbleLeft.style.top=a10.bubble.BORDER_WIDTH+"px";
this.bubbleLeft.style.left="0px";
this.container.appendChild(this.bubbleLeft);
a10.util.ie6PNGSpriteHack(this.bubbleLeft);
this.bubbleConn=document.createElement("div");
this.bubbleConn.style.backgroundImage="url("+a10.bubble.SPRITE_URL+")";
if(this.direction=="up"){this.bubbleConn.style.backgroundPosition="-50px -328px";
this.bubbleConn.style.top="-7px";
var C=34;
if(F){C+=F;
}this.bubbleConn.style.left=C+"px";
this.bubbleConn.style.height="22px";
this.bubbleConn.style.width="23px";
}else{if(this.direction.indexOf("left")==0){this.bubbleConn.style.backgroundPosition="-33px -360px";
var C=-8;
if(F){C+=F;
}this.bubbleConn.style.left=C+"px";
this.bubbleConn.style.height="23px";
this.bubbleConn.style.width="22px";
if(this.direction.indexOf("-high")>0){this.bubbleConn.style.top=30+"px";
}else{this.bubbleConn.style.top=(J-25)+"px";
}}else{if(this.direction.indexOf("right")==0){this.bubbleConn.style.backgroundPosition="-63px -360px";
var C=-8;
if(F){C+=F;
}this.bubbleConn.style.left=(D+C+15)+"px";
this.bubbleConn.style.height="23px";
this.bubbleConn.style.width="22px";
if(this.direction.indexOf("-high")>0){this.bubbleConn.style.top=30+"px";
}else{this.bubbleConn.style.top=(J-25)+"px";
}}else{if(this.direction=="down"){this.bubbleConn.style.backgroundPosition="-50px -397px";
this.bubbleConn.style.top=(J+14)+"px";
var C=34;
if(F){C+=F;
}this.bubbleConn.style.left=C+"px";
this.bubbleConn.style.height="20px";
this.bubbleConn.style.width="23px";
}else{this.bubbleConn.style.height="0px";
this.bubbleConn.style.width="0px";
}}}}this.bubbleConn.style.position="absolute";
this.container.appendChild(this.bubbleConn);
a10.util.ie6PNGSpriteHack(this.bubbleConn);
var E=function(L){L=L||window.event;
L.cancelBubble=true;
return false;
};
this.bubbleBottom.onclick=this.bubbleLeft.onclick=this.bubbleRight.onclick=this.bubbleTop.onclick=this.bubbleConn.onclick=E;
if(a10.browser.isIE6()){this.cover=new a10.IFrameCover(this.content,{width:parseInt(a10.bubble.BORDER_WIDTH/2)+1});
}};
a10.Bubble.prototype.container;
a10.Bubble.prototype.content;
a10.Bubble.prototype.bubbleLeft;
a10.Bubble.prototype.bubbleTop;
a10.Bubble.prototype.bubbleRight;
a10.Bubble.prototype.bubbleBottom;
a10.Bubble.prototype.bubbleConn;
a10.Bubble.prototype.closeButton;
a10.Bubble.prototype.direction;
a10.Bubble.prototype.heightOffset;
a10.Bubble.prototype.redraw=function(){var A=this.content.offsetHeight;
if(!A){A=220;
}if(this.heightOffset){A+=this.heightOffset;
}if(a10.browser.isIE6()){this.bubbleRight.style.height=A+"px";
this.bubbleRight.innerHTML="";
this.bubbleTop.innerHTML="";
this.bubbleRight.style.backgroundImage="url("+a10.bubble.SPRITE_URL+")";
this.bubbleTop.style.backgroundImage="url("+a10.bubble.SPRITE_URL+")";
a10.util.ie6PNGSpriteHack(this.bubbleRight);
a10.util.ie6PNGSpriteHack(this.bubbleTop);
}if(a10.browser.isIE6()){this.bubbleLeft.style.height=A+"px";
this.bubbleLeft.innerHTML="";
this.bubbleLeft.style.backgroundImage="url("+a10.bubble.SPRITE_URL+")";
a10.util.ie6PNGSpriteHack(this.bubbleLeft);
this.bubbleLeft.getElementsByTagName("div")[0].style.height=a10.bubble.SPRITE_HEIGHT+"px";
this.bubbleLeft.getElementsByTagName("div")[0].style.top="-"+(a10.bubble.SPRITE_HEIGHT-A)+"px";
this.bubbleRight.getElementsByTagName("div")[0].style.height=a10.bubble.SPRITE_HEIGHT+"px";
this.bubbleBottom.style.top=A+"px";
}else{this.bubbleLeft.style.height=A+"px";
this.bubbleLeft.style.backgroundPosition="0px -"+(a10.bubble.SPRITE_HEIGHT-A)+"px";
this.bubbleRight.style.height=A+"px";
this.bubbleBottom.style.top=(parseInt(this.bubbleRight.style.height))+"px";
}};

if(!a10.skins){a10.skins={};
}a10.skins.uploadTimeout=3*60*1000;
a10.skins.apiTimeout=20*1000;
a10.skins.timeoutHandler=null;
a10.skins.tempMetaInfo="";
a10.skins.uploading=false;
a10.skins.fromSignup=false;
a10.skins.fromSignin=false;
a10.skins.skinCheck=false;
if(window.opera){window.document.addEventListener("message",function(ev){eval(ev.data);
},false);
}a10.skins.clearTimeout=function(){if(a10.skins.timeoutHandler){clearTimeout(a10.skins.timeoutHandler);
a10.skins.timeoutHandler=null;
}};
a10.skins.uploadHandler=function(B){a10.skins.uploading=false;
a10.skins.clearTimeout();
if(B.status=="success"){$("skinPreview1").src=B.element.thumbnailUrl;
$("skinPreview2").src=B.element.thumbnailUrl;
a10.skins.tempMetaInfo=B.element;
$("skinId").value=B.element.id;
var A=(B.element.filesize/1024>0)?Math.round(B.element.filesize/1024)+"KB":"1KB";
$("skinInfoLabel").innerHTML=B.element.width+"x"+B.element.height+", "+A;
$("skinInfoSpan").innerHTML=B.element.width+"x"+B.element.height+", "+A;
$("skinname").value=B.element.name;
if(B.element.uid&&_skinUserId==""){_skinUserId=B.element.uid;
a10.skins.setPUID(B.element.uid);
}a10.skins.uploadStep3();
}else{a10.skins.uploadStep1(true);
a10.skins.resetErrorLabels();
a10.skins.showErrorMessage("uploadErrorLabel",B.element.errMsg);
}};
a10.skins.setPUID=function(B){_skinUserId="";
var A=new Date();
A.setTime(A.getTime()+31536000000);
document.cookie="PUID="+B+"; expires="+A.toGMTString()+"; path=/; domain=ask.com";
myStuffMenu.updateStatus();
};
a10.skins.metaInfoHandler=function(A){a10.skins.clearTimeout();
if(A.status=="success"){a10.skins.uploadStep4();
}else{a10.skins.uploadStep3();
a10.skins.resetErrorLabels();
a10.skins.showErrorMessage("uploadNameErrorLabel",A.element.errMsg);
}};
a10.skins.showError=function(A){if($(A).type!="checkbox"){$(A).style.border="solid 1px #cc0000";
}var B=$(A+"Label").innerHTML.toLowerCase();
if(B.indexOf("<img")==-1){$(A+"Label").innerHTML='<img src="'+a10.strings.skins_errorurl+'" style="padding-right:5px;padding-left:0;margin-left:0">'+$(A+"Label").innerHTML;
}};
a10.skins.clearError=function(A){if($(A).type!="checkbox"){$(A).style.border="solid 1px #9699A2";
}var B=$(A+"Label").innerHTML.toLowerCase();
if(B.indexOf("<img")!=-1){$(A+"Label").innerHTML=$(A+"Label").innerHTML.substring(B.indexOf(">")+1);
}};
a10.skins.setAlign=function(B,C,A){$("skinposition").value=B+" "+C;
a10.skins.drawAlign(A,false,"skinposition");
};
a10.skins.setEditAlign=function(B,C,A){$("skinEditPosition").value=B+" "+C;
a10.skins.drawAlign(A,true,"skinEditPosition");
};
a10.skins.setTextColor=function(A){$("skincolor").value=A;
a10.skins.drawTextColor(false);
};
a10.skins.setEditTextColor=function(A){$("skinEditColor").value=A;
a10.skins.drawTextColor(true);
};
a10.skins.drawTextColor=function(B){var A=$(!B?"skincolor":"skinEditColor").value;
if(A=="dark"){$(!B?"text1":"editText1").style.border="solid 1px #ff0004";
$(!B?"text2":"editText2").style.border="solid 1px #fff";
$(!B?"skinTextColorLabel":"skinEditTextColorLabel").innerHTML=a10.strings.skins_lighttext;
}else{$(!B?"text1":"editText1").style.border="solid 1px #fff";
$(!B?"text2":"editText2").style.border="solid 1px #ff0004";
$(!B?"skinTextColorLabel":"skinEditTextColorLabel").innerHTML=a10.strings.skins_darktext;
}if(!B){$("skinTextSpan").innerHTML=$("skinTextColorLabel").innerHTML;
}};
a10.skins.drawPreview=function(C,A,B){var D=$(C);
if(A=="top left"){D.style.left=B[0]-B[2]+"px";
D.style.top=B[1]-B[3]+"px";
}else{if(A=="bottom left"){D.style.left=B[0]-B[2]+"px";
D.style.top="0";
}else{if(A=="center center"){D.style.left=((B[0]-B[2])/2)+"px";
D.style.top=((B[1]-B[3])/2)+"px";
}else{if(A=="top center"){D.style.left=((B[0]-B[2])/2)+"px";
D.style.top=B[1]-B[3]+"px";
}else{if(A=="bottom center"){D.style.left=((B[0]-B[2])/2)+"px";
D.style.top="0";
}else{if(A=="top right"){D.style.left="0";
D.style.top=B[1]-B[3]+"px";
}else{if(A=="bottom right"){D.style.left="0";
D.style.top="0";
}else{if(A=="center right"){D.style.left="0";
D.style.top=((B[1]-B[3])/2)+"px";
}else{if(A=="center left"){D.style.left=B[0]-B[2]+"px";
D.style.top=((B[1]-B[3])/2)+"px";
}}}}}}}}}D.style.display="";
};
a10.skins.drawAlign=function(F,E,C){var A=$(C).value;
var D="align";
if(E){D="editAlign";
}for(var B=1;
B<10;
B++){$(D+B).style.border="solid 1px #fff";
}if(!E){$("skinAlignDiv").className=F.className;
a10.skins.drawPreview("skinBoundary",A,[200,130,255,161]);
a10.skins.drawPreview("skinBoundary2",A,[130,85,164,104]);
}else{a10.skins.drawPreview("skinEditBoundary",A,[200,130,255,161]);
}if(F!=null){F.style.border="solid 1px #ff0004";
}};
a10.skins.resetErrorLabels=function(){var B=["uploadErrorLabel","uploadUrlErrorLabel","uploadTermErrorLabel"];
for(var A=0;
A<B.length;
A++){$(B[A]).style.display="none";
}};
a10.skins.checkSelectedSkin=function(){if(a10.skins.isAuthenticated()){a10.skins.prepRequest();
$("skinretrieveform").submit();
}};
a10.skins.uploadStep1=function(B){if(!Cookie.isEnabled()){window.location=_urlPrefix+"skinscookies";
return false;
}a10.skins.clearError("skinurl");
a10.skins.clearError("skinfile");
a10.skins.clearError("skinterm");
$("skinStep2").style.display="none";
$("skinStep3").style.display="none";
$("skinStep4").style.display="none";
$("skinStep1").style.display="";
a10.skins.resetErrorLabels();
window.skinUploadDialog.title=a10.strings.skins_upload+' <span style="color:#000;font-weight:normal">'+a10.strings.skins_step1+"</span>";
$("dialogTitle").innerHTML=a10.strings.skins_upload+' <span style="color:#000;font-weight:normal">'+a10.strings.skins_step1+"</span>";
if(!B){$("skinurl").value="";
try{$("skinfile").value="";
}catch(C){}$("skinname").value="";
$("skinposition").value="center center";
$("skincolor").value="light";
$("skinterm").checked=false;
}a10.skins.fromSignup=false;
if(a10.browser.isIE6()){var D=$("skinPreview1").src;
var A=$("skinBoundary");
if(A.src.indexOf("pixl.gif")==-1){A.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled='true',src='"+A.src+"')";
A.src=D;
}A=$("skinBoundary2");
if(A.src.indexOf("pixl.gif")==-1){A.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled='true',src='"+A.src+"', sizingMethod='scale')";
A.src=D;
}}};
a10.skins.uploadStep2=function(){$("skinStep1").style.display="none";
$("skinStep3").style.display="none";
$("skinStep4").style.display="none";
$("skinStep2").style.display="";
};
a10.skins.uploadStep3=function(){a10.skins.clearError("skinname");
$("skinStep1").style.display="none";
$("skinStep2").style.display="none";
$("skinStep4").style.display="none";
$("skinStep3").style.display="";
$("dialogTitle").innerHTML=a10.strings.skins_upload+' <span style="color:#000;font-weight:normal">'+a10.strings.skins_step2+"</span>";
$("uploadNameErrorLabel").style.display="none";
a10.skins.drawAlign($("align5"),false,"skinposition");
a10.skins.drawTextColor();
$("skinname").focus();
};
a10.skins.uploadStep4=function(){$("skinStep1").style.display="none";
$("skinStep2").style.display="none";
$("skinStep3").style.display="none";
$("skinStep4").style.display="";
a10.skins.fromSignup=false;
if(!a10.skins.isAuthenticated()){$("signinPane").style.display="";
}else{$("signinPane").style.display="none";
}$("dialogTitle").innerHTML=a10.strings.skins_upload+' <span style="color:#000;font-weight:normal">'+a10.strings.skins_step3+"</span>";
var A=$("skinname").value;
$("skinTitleSpan").innerHTML=A.substr(0,Math.min(50,A.length))+(A.length>50?"...":"");
if(window._mystuffSignInCallback){window.mystuffSignInCallback=window._mystuffSignInCallback;
}$("skinUseNow").focus();
};
a10.skins.showErrorMessage=function(C,B){a10.skins.shaking=true;
var A=$(C);
A.style.display="";
A.innerHTML=B;
a10.anim.shake("dialog",20,1,function(){a10.skins.shaking=false;
});
};
a10.skins.startUpload=function(){if(a10.skins.shaking){return ;
}var A=a10.util.trim($("skinurl").value);
if(A==""&&a10.util.trim($("skinfile").value)==""){a10.skins.resetErrorLabels();
a10.skins.showErrorMessage("uploadErrorLabel",a10.strings.skins_emptyselection);
a10.skins.showError("skinfile");
a10.skins.showError("skinurl");
a10.skins.clearError("skinterm");
}else{if(A!=""&&!/^http:\/\//i.test(A)){a10.skins.resetErrorLabels();
a10.skins.showErrorMessage("uploadUrlErrorLabel",a10.strings.skins_urlinvalid);
a10.skins.clearError("skinfile");
a10.skins.showError("skinurl");
a10.skins.clearError("skinterm");
}else{if(A!=""&&$("skinfile").value!=""){a10.skins.resetErrorLabels();
a10.skins.showErrorMessage("uploadErrorLabel",a10.strings.skins_urlfile);
a10.skins.showError("skinfile");
a10.skins.showError("skinurl");
a10.skins.clearError("skinterm");
}else{if(!$("skinterm").checked){a10.skins.resetErrorLabels();
a10.skins.showErrorMessage("uploadTermErrorLabel",a10.strings.skins_tos);
a10.skins.showError("skinterm");
a10.skins.clearError("skinfile");
a10.skins.clearError("skinurl");
}else{a10.skins.uploadStep2();
if(!a10.skins.isAuthenticated()){$("skinuid").value=_skinUserId;
}a10.skins.prepRequest();
a10.skins.uploading=true;
try{$("skinform").submit();
var B=function(){a10.skins.cancelUpload();
if(_impressionUrl){new Image().src=_impressionUrl+"&rnd="+new Date().getTime();
}a10.skins.uploadHandler({status:"error",element:{errMsg:a10.strings.skins_error}});
};
a10.skins.timeoutHandler=setTimeout(B,a10.skins.uploadTimeout);
}catch(C){a10.skins.uploadStep1(true);
a10.skins.resetErrorLabels();
a10.skins.showErrorMessage("uploadErrorLabel",a10.strings.skins_badfile);
a10.skins.showError("skinfile");
a10.skins.clearError("skinurl");
a10.skins.clearError("skinterm");
}}}}}return false;
};
a10.skins.setAttrs=function(){if(a10.skins.shaking){return false;
}if(a10.util.trim($("skinname").value)!=""){a10.skins.uploadStep2();
if(!a10.skins.isAuthenticated()){$("skinuid2").value=_skinUserId;
}a10.skins.prepRequest();
a10.skins.submitWithTimeout("skinattrform",a10.skins.metaInfoHandler);
}else{$("uploadNameErrorLabel").style.display="";
$("uploadNameErrorLabel").innerHTML=a10.strings.skins_namerequired;
a10.skins.showError("skinname");
a10.skins.shaking=true;
a10.anim.shake("dialog",20,1,function(){a10.skins.shaking=false;
});
}return false;
};
a10.skins.applyCurrentSkin=function(A){a10.skins.setSkinCookie(A.id,A.url,A.width,A.height,A.color,A.position);
if($("skinCredit")){a10.skins.applySkin(A.url,A.width,A.height,A.color,A.position,A.credit,true);
}};
a10.skins.saveAndUseSkin=function(){var A=a10.skins.tempMetaInfo;
a10.skins.setSkinCookie(A.id,A.url,A.width,A.height,$("skincolor").value,$("skinposition").value);
a10.skins.prepRequest();
$("selectedSkinId").value=A.id;
if(!a10.skins.isAuthenticated()){$("skinuid3").value=_skinUserId;
}$("selectfn").value="a10.skins.selectHandler";
a10.skins.submitWithTimeout("skinselectform",a10.skins.selectHandler);
a10.skins.uploadStep2();
a10.skins.tempMetaInfo=null;
};
a10.skins.isAuthenticated=function(){var A=Cookie.getCookie("AUID");
return A!=null&&A!="";
};
a10.skins.getColors=function(C){var B,D;
if(C=="light"){B="#FFFFFF";
D="#CC0000";
}else{if(C=="dark"||C==null||a10.util.trim(C)==""){B="#666666";
D="#CC0000";
}else{var A=C.split(" ");
B=A[0];
D=A[1];
}}return[B,D];
};
a10.skins.setSkinCookie=function(H,C,E,J,I,F){var A=a10.skins.getColors(I);
var G=A[0];
var B=A[1];
var D="id="+H+"&su="+escape(C)+"&w="+E+"&h="+J+"&lc="+G+"&sc="+B+"&sa="+escape(F);
var K=new Date();
K.setTime(K.getTime()+31536000000);
document.cookie="sk2="+D+"; expires="+K.toGMTString()+"; path=/; domain=ask.com";
if(H==""&&Cookie.getCookie("skm")=="1"){Cookie.setCookie("skm","2",K,"/","ask.com");
}};
a10.skins.getCurrentSkin=function(){var E=Cookie.getCookie("sk2",true);
var C={};
if(E!=null&&E!=""){var B=E.split("&");
for(var A=0;
A<B.length;
A++){var D=B[A].split("=");
C[D[0]]=D[1];
}}C["su"]=unescape(C["su"]);
return C;
};
a10.skins.currentSkinHandler=function(C){a10.skins.clearTimeout();
if(C.status=="success"){if(C.element.id!=""){var F=a10.skins.getCurrentSkin();
var A=a10.skins.getColors(C.element.color);
if(F["id"]==C.element.id){return ;
}}a10.skins.setSkinCookie(C.element.id,C.element.url,C.element.width,C.element.height,C.element.color?C.element.color:"",C.element.position?C.element.position:"");
a10.skins.applySkin(C.element.url,C.element.width,C.element.height,C.element.color?C.element.color:"",C.element.position?C.element.position:"",null,true);
}else{var E=$("peelPromo");
a10.skins.setSkinCookie("","","","","","");
var D=Cookie.getCookie("user");
var B=(D!=null)?D.indexOf("o=10198"):false;
if(!E&&!B){a10.skins.applySkin("",null,null,null,null,null,true);
}}};
a10.skins.toggleDownArrows=function(A){var C=$("oli").getElementsByTagName("span");
for(var B=0;
B<C.length;
B++){if(C[B].className=="darrow"){C[B].style.display=A?"":"none";
}}C=$("mli").getElementsByTagName("span");
for(var B=0;
B<C.length;
B++){if(C[B].className=="darrow"){C[B].style.display=A?"":"none";
}}};
a10.skins.updateLinkStyles=function(B){var E=$("wrapper");
if(E!=null){var A=a10.skins.getColors(B);
window.navColor=A[0];
window.navSelectedColor=A[1];
$("footerCopyright").style.color=navColor;
$("footerLinks").style.color=navColor;
$("mslabel").style.color=navColor;
$("mli").style.color=navColor;
$("oli").style.color=navColor;
if($("eli")){$("eli").style.color=navColor;
}$("skinCredit").style.color=navColor;
var D=$("tnav").getElementsByTagName("a");
for(var C=0;
C<D.length;
C++){if(D[C].className=="navSelected"){D[C].style.color=navSelectedColor;
}else{D[C].style.color=navColor;
}}D=$("footerLinks").getElementsByTagName("a");
for(var C=0;
C<D.length;
C++){D[C].style.color=navColor;
}}};
a10.skins.updateSkinPosition=function(A){var B=$("wrapper");
if(B!=null){B.style.backgroundRepeat="no-repeat";
if(A!=""&&A!="undefined"&&A!=null){B.style.backgroundPosition=A;
}else{B.style.backgroundPosition="bottom center";
}}};
a10.skins.applySkin=function(B,C,J,F,H,E,K,I){var A=$("wrapper");
if(A!=null){if(B==""){A.style.backgroundImage="none";
a10.skins.toggleDownArrows(true);
setTimeout(function(){if($(window.skinApplyingDialog.id).style.display!="none"){window.skinApplyingDialog.hide();
}if(!K){a10.hp.showSkinsMakeHomepage();
}},2000);
a10.skins.updateSkinPosition(H);
}else{var G=new Image();
_startTime=new Date().getTime();
var D=function(){a10.skins.updateSkinPosition(H);
$("wrapper").style.backgroundImage="url("+B+")";
if(E){$("skinCredit").innerHTML=a10.strings.skins_credit+" "+E;
}else{$("skinCredit").innerHTML="";
}if($(window.skinApplyingDialog.id).style.display!="none"){window.skinApplyingDialog.hide();
}if(!K){a10.hp.showSkinsMakeHomepage();
}};
G.onload=function(){var L=new Date().getTime();
var M=L-_startTime;
if(M<2000&&!I){setTimeout(D,2000-M);
}else{D();
}};
G.src=B;
a10.skins.toggleDownArrows(false);
A.style.minHeight=0;
}a10.skins.updateLinkStyles(F);
if(C!=null&&C!=""){_maxHeight=J;
A.style.maxWidth=C+"px";
A.style.maxHeight=J+"px";
if(a10.browser.isIE6()){A.style.setExpression("width","(document.body.clientWidth > "+C+' ? "'+C+'px" : "auto")');
A.style.setExpression("height","(document.body.clientHeight > "+J+' ? "'+J+'px" : "100%")');
}windowSizeChanged();
a10.hp.repositionSkinDialog();
}else{_maxHeight=0;
$("wrapper").style.top="0";
A.style.maxWidth="none";
A.style.maxHeight="none";
if(a10.browser.isIE6()){A.style.setExpression("width",'(document.body.clientWidth < 800 ? "798px" : "auto")');
A.style.setExpression("height",'(document.body.clientHeight < 600 ? "598px" : "100%")');
}}a10.skins.updateCurrentSkinStatus();
if($("promo")){$("promo").innerHTML="";
}}};
a10.skins.selectHandler=function(A){a10.skins.clearTimeout();
if(A.status=="success"){if(A.element.uid){_skinUserId=A.element.uid;
a10.skins.setPUID(A.element.uid);
}}else{alert(A.element.errMsg);
}if($("origin")&&$("origin").value=="10579"){var B=window.location.toString();
var C=B.indexOf("guaid");
if(C!=-1){var D=B.substring(C+6,B.indexOf("&",C));
_reloadUrl+="&guaid="+D;
}}window.location.replace(_reloadUrl+"&sknr=1");
};
a10.skins.saveSkin=function(){a10.skins.tempMetaInfo=null;
window.skinUploadDialog.hide();
if(!a10.hp){a10.skins.refreshPage();
}};
a10.skins.closeUploadDialog=function(){if(a10.skins.fromSignup){a10.skins.fromSignup=false;
return true;
}if(a10.skins.fromSignin){a10.skins.fromSignin=false;
return true;
}a10.skins.cancelUpload();
if(a10.skins.tempMetaInfo){a10.skins.prepRequest();
$("deleteSkinId").value=a10.skins.tempMetaInfo.id;
if(!a10.skins.isAuthenticated()){$("skinuid4").value=_skinUserId;
}$("skindeleteform").submit();
a10.skins.tempMetaInfo="";
}return true;
};
a10.skins.cancelUpload=function(){if(a10.skins.uploading){$("hif").src="about:blank";
a10.skins.uploading=false;
}};
a10.skins.cancelUploadDialog=function(A){a10.skins.cancelUpload();
if(a10.skins.tempMetaInfo){a10.skins.prepRequest();
$("deleteSkinId").value=a10.skins.tempMetaInfo.id;
if(!a10.skins.isAuthenticated()){$("skinuid4").value=_skinUserId;
}$("skindeleteform").submit();
a10.skins.tempMetaInfo="";
}if(A){window.skinUploadDialog.hide();
}return false;
};
a10.skins.deleteHandler=function(A){a10.skins.clearTimeout();
if(A.status=="error"){alert(A.element.errMsg);
}};
a10.skins.keyDownHandler=function(C,D){var B=window.event?window.event:C;
var A=B.keyCode;
if(A==13){a10.event.cancelDefaultAction(C);
D();
return false;
}};
a10.skins.signupStep1=function(){a10.skins.fromSignup=true;
window.skinUploadDialog.hide();
window.mystuffSignUpCallback=function(){a10.skins.setPUID("");
window.skinUploadDialog.show();
a10.skins.uploadStep4();
window.mystuffSignUpCallback=null;
};
ask.mystuff.SignUp.step1();
ask.mystuff.SignUp.onClose=function(){window.skinUploadDialog.show();
a10.skins.uploadStep4();
ask.mystuff.SignUp.onClose=null;
};
window.signupDialog.show();
};
a10.skins.signin=function(){a10.skins.fromSignin=true;
window.skinUploadDialog.hide();
window._mystuffSignInCallback=window.mystuffSignInCallback;
window.mystuffSignInCallback=function(A){if(A.status=="success"){if(a10.skins.tempMetaInfo&&A.element.elementmap){a10.skins.tempMetaInfo.url=A.element.urlmap[a10.skins.tempMetaInfo.id];
a10.skins.tempMetaInfo.id=A.element.elementmap[a10.skins.tempMetaInfo.id];
}window.skinUploadDialog.show();
a10.skins.uploadStep4();
a10.skins.setPUID("");
if(A.element&&A.element.selectedskin){a10.skins.applyCurrentSkin(A.element.selectedskin);
}}else{alert(A.element.errMsg);
}};
window.signinDialog.show();
};
a10.skins.copySaveHandler=function(A){a10.skins.clearTimeout();
if(A.status=="success"){a10.skins.useSkin($("skincopyid").value,_copyMetaInfo.url,_copyMetaInfo.width,_copyMetaInfo.height,$("skincopycolor").value,$("skincopyposition").value,true);
a10.skins.applySkin(_copyMetaInfo.url,_copyMetaInfo.width,_copyMetaInfo.height,$("skincopycolor").value,$("skincopyposition").value);
}else{alert(A.element.errMsg);
}};
a10.skins.copyUploadHandler=function(A){a10.skins.clearTimeout();
if(A.status=="success"){if(A.element.uid&&_skinUserId==""){_skinUserId=A.element.uid;
a10.skins.setPUID(A.element.uid);
}if(!a10.skins.isAuthenticated()){$("skincopyuid").value=_skinUserId;
}_copyMetaInfo=A.element;
$("skincopyid").value=A.element.id;
a10.skins.prepRequest();
$("skinemailsaveform").submit();
}else{alert(A.element.errMsg);
}};
a10.skins.showDeleteDialog=function(A,B){if(!Cookie.isEnabled()){window.location=_urlPrefix+"skinscookies";
return false;
}$("skinDeleteId").value=A;
$("skinDeletePreview").src=$("skt_"+B).src;
$("skinDeleteName").innerHTML=$("skn_"+B).innerHTML;
window.skinDeleteDialog.show();
$("deleteButton").focus();
};
a10.skins.deleteSkin=function(){if(!a10.skins.isAuthenticated()){$("skinDeleteUid").value=_skinUserId;
}a10.skins.prepRequest();
a10.skins.submitWithTimeout("skindeletedialogform",a10.skins.deleteSkinHandler);
};
a10.skins.deleteSkinHandler=function(B){a10.skins.clearTimeout();
if(B.status=="success"){if($("skinDeleteId").value==a10.skins.getCurrentSkin()["id"]){var A=new Date();
A.setTime(A.getTime()+31536000000);
document.cookie="sk2=; expires="+A.toGMTString()+"; path=/; domain=ask.com";
}window.skinDeleteDialog.hide();
a10.skins.refreshPage();
}else{alert(B.element.errMsg);
}};
a10.skins.showEditDialog=function(H,B,I,F,A,C){if(!Cookie.isEnabled()){window.location=_urlPrefix+"skinscookies";
return false;
}if(a10.browser.isIE6()){var G=$("skinEditPreview").src;
var E=$("skinEditBoundary");
if(E.src.indexOf("pixl.gif")==-1){E.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled='true',src='"+E.src+"')";
E.src=G;
}}if(B!=null){$("skineditname").value=$("skn_"+B).innerHTML;
$("skinEditPreview").src=$("skt_"+B).src;
}else{$("skineditname").value=A;
$("skinEditPreview").src=C;
}$("skinEditId").value=H;
$("skinEditColor").value=I;
$("editStep1").style.display="";
$("editStep2").style.display="none";
$("saveNameErrorLabel").style.display="none";
a10.skins.clearError("skineditname");
if(F==""){a10.skins.setEditAlign("center","center",$("editAlign5"));
}else{var D=F.indexOf(" ");
var J={"top left":1,"top center":2,"top right":3,"center left":4,"center center":5,"center right":6,"bottom left":7,"bottom center":8,"bottom right":9};
a10.skins.setEditAlign(F.substr(0,D),F.substr(D+1),$("editAlign"+J[F]));
}a10.skins.drawTextColor(true);
window.skinEditDialog.show();
$("skineditname").focus();
};
a10.skins.saveAttrs=function(){if($("skineditname").value==""){a10.skins.showErrorMessage("saveNameErrorLabel",a10.strings.skins_namerequired);
a10.skins.showError("skineditname");
return false;
}$("editStep1").style.display="none";
$("editStep2").style.display="";
if(!a10.skins.isAuthenticated()){$("skinEditUid").value=_skinUserId;
}a10.skins.prepRequest();
a10.skins.submitWithTimeout("skineditform",a10.skins.editInfoHandler);
};
a10.skins.refreshPage=function(){var B=window.location.toString();
if(B.indexOf("#")!=-1){B=B.substring(0,B.indexOf("#"));
}if(B.indexOf("?")==-1){window.location.replace(B+"?rnd="+new Date().getTime());
}else{var A=B.indexOf("rnd=");
if(A!=-1){B=B.substring(0,A);
window.location.replace(B+"rnd="+new Date().getTime());
}else{window.location.replace(B+"&rnd="+new Date().getTime());
}}};
a10.skins.editInfoHandler=function(A){a10.skins.clearTimeout();
if(A.status=="success"){var B=a10.skins.getCurrentSkin();
if(B&&B["id"]==$("skinEditId").value){a10.skins.setSkinCookie($("skinEditId").value,B["su"],B["w"],B["h"],$("skinEditColor").value,$("skinEditPosition").value);
}window.skinEditDialog.hide();
a10.skins.refreshPage();
}else{$("editStep2").style.display="none";
$("editStep1").style.display="";
a10.skins.showErrorMessage("saveNameErrorLabel",A.element.errMsg);
}};
a10.skins.closeSignIn=function(){if(a10.skins.fromSignup){a10.skins.fromSignup=false;
setTimeout(function(){window.skinUploadDialog.show();
},100);
}return true;
};
a10.skins.editCurrent=function(){if(!a10.skins.isAuthenticated()){$("currentskinuid").value=_skinUserId;
}a10.skins.prepRequest();
a10.skins.submitWithTimeout("skineditcurrentform",a10.skins.editCurrentSkinHandler);
$("editStep1").style.display="none";
$("editStep2").style.display="";
window.skinEditDialog.show();
};
a10.skins.editCurrentSkinHandler=function(A){a10.skins.clearTimeout();
if(A.status=="success"){window.skinEditDialog.hide();
$("editStep1").style.display="";
$("editStep2").style.display="none";
$("skinEditHandler").value="a10.skins.editCurrentSkinCompleteHandler";
if(A.element.id){a10.skins.showEditDialog(A.element.id,null,A.element.color,A.element.position,A.element.name,A.element.thumbnailUrl);
}}else{alert(A.element.errMsg);
window.skinEditDialog.hide();
}};
a10.skins.editCurrentSkinCompleteHandler=function(A){a10.skins.clearTimeout();
if(A.status=="success"){a10.skins.updateLinkStyles($("skinEditColor").value);
a10.skins.updateSkinPosition($("skinEditPosition").value);
var B=a10.skins.getCurrentSkin();
a10.skins.setSkinCookie(B["id"],B["su"],B["w"],B["h"],$("skinEditColor").value,$("skinEditPosition").value);
window.skinEditDialog.hide();
}};
a10.skins.emptyHandler=function(A){a10.skins.clearTimeout();
if(A.status=="success"){if(A.element.uid){_skinUserId=A.element.uid;
a10.skins.setPUID(A.element.uid);
}}else{alert(A.element.errMsg);
}};
a10.skins.updateCurrentSkinStatus=function(){if(!$("editLink")){return ;
}var A=a10.skins.getCurrentSkin();
if(A["id"]!=null&&A["id"].length>31){$("editLink").style.display="";
$("skinCredit").style.display="none";
}else{$("editLink").style.display="none";
$("skinCredit").style.display=(A["id"]||Cookie.getCookie("skm")=="1")?"":"none";
}};
a10.skins.emailSkin=function(H,E,F,A,D){var C=a10.skins.getColors(F);
var G="id="+H+"&su="+escape(E)+"&lc="+C[0]+"&sc="+C[1]+"&sa="+escape(A)+"&sn="+escape($("skn_"+D).innerHTML);
var B=_urlPrefix+"?sknd="+(escape(G));
window.location="mailto:?body="+escape(B);
};
a10.skins.submitWithTimeout=function(A,B){var C=function(){$("hif").src="about:blank";
if(_impressionUrl){new Image().src=_impressionUrl+"&rnd="+new Date().getTime();
}B({status:"error",element:{errMsg:a10.strings.skins_error}});
};
$(A).submit();
a10.skins.timeoutHandler=setTimeout(C,a10.skins.apiTimeout);
};
a10.skins.prepRequest=function(){if(a10.browser.isIE()){window.frames["hif"].name="hif";
}document.domain="ask.com";
};
a10.skins.showUploadDialog=function(){if(!Cookie.isEnabled()){setTimeout(function(){window.location=_urlPrefix+"skinscookies";
},10);
return ;
}a10.skins.uploadStep1();
window.skinUploadDialog.show();
};
a10.skins.useSkin=function(F,C,D,B,E,A,G){if(!Cookie.isEnabled()){setTimeout(function(){window.location=_urlPrefix+"skinscookies";
},10);
return false;
}if(F=="ask999999"){F="";
}a10.skins.setSkinCookie(F,C,D,B,E,A);
if(F.indexOf("ss30009")==0){return ;
}a10.skins.prepRequest();
$("selectedSkinId").value=F;
if(G){$("selectfn").value="a10.skins.emptyHandler";
}else{$("selectfn").value="a10.skins.selectHandler";
}if(!a10.skins.isAuthenticated()){$("skinuid3").value=_skinUserId;
}$("skinselectform").submit();
};

if(!ask){var ask={};
}if(!a10){var a10={};
}a10.hp={};
a10.hp.linkClicked=false;
a10.hp.skinBubbleCreated=false;
a10.hp.webAdvancedBound=false;
a10.hp.blogAdvancedBound=false;
a10.hp.sliding=false;
a10.hp.shaking=false;
a10.hp.currentSkinPage=1;
if(a10.ss){a10.ss.hp="true";
}a10.hp.repositionSkinDialog=function(){var A=document.getElementById("skinPop");
if(A.style.display!="none"){var B=a10.util.findPos(document.getElementById("ska"));
A.style.left=(B[0]-27)+"px";
A.style.top=(B[1]+20)+"px";
}};
a10.hp.updateSkinButtonState=function(){if(!$("skinStrip")){return ;
}var A=1;
while(true){if($("skinPg"+A)){var B=$("skinPg"+A).src;
if(A==a10.hp.currentSkinPage){$("skinPg"+A).className="adot";
}else{$("skinPg"+A).className="ddot";
}A++;
}else{break;
}}if(a10.hp.currentSkinPage==1){$("skinRight").style.visibility="visible";
$("skinRight").style.cursor="pointer";
$("skinLeft").style.visibility="hidden";
$("skinLeft").style.cursor="default";
}else{if(a10.hp.currentSkinPage==A-1){$("skinRight").style.visibility="hidden";
$("skinRight").style.cursor="default";
$("skinLeft").style.visibility="visible";
$("skinLeft").style.cursor="pointer";
}else{$("skinRight").style.visibility="visible";
$("skinRight").style.cursor="pointer";
$("skinLeft").style.visibility="visible";
$("skinLeft").style.cursor="pointer";
}}a10.hp.sliding=false;
};
a10.hp.skinPage=function(A){if(a10.hp.sliding||A==a10.hp.currentSkinPage){return ;
}a10.hp.currentSkinPage=A;
$("skinStrip").style.left=-((A-1)*388)+"px";
a10.hp.updateSkinButtonState();
};
a10.hp.slideLeft=function(B,A){if(a10.hp.sliding){return ;
}a10.hp.currentSkinPage--;
B=window.event||B;
if(a10.hp.currentSkinPage>=0){a10.anim.slideX("skinStrip",0.3,(parseInt($("skinStrip").style.left)+388),a10.hp.updateSkinButtonState);
a10.event.cancelDefaultAction(B);
a10.hp.sliding=true;
}a10.hp.linkClicked=true;
};
a10.hp.slideRight=function(B,A){if(a10.hp.sliding){return ;
}a10.hp.currentSkinPage++;
B=window.event||B;
var C=parseInt($("skinStrip").style.left);
if(a10.hp.currentSkinPage<=A){if(isNaN(C)){$("skinStrip").style.left="0px";
}a10.anim.slideX("skinStrip",0.3,(isNaN(C)?-388:C-388),a10.hp.updateSkinButtonState);
a10.event.cancelDefaultAction(B);
a10.hp.sliding=true;
}a10.hp.linkClicked=true;
};
a10.hp.getSkinId=function(){var C="sk";
var D=document.cookie;
var E=D.indexOf(C+"=");
var A=E+C.length+1;
if((!E)&&(C!=D.substring(0,C.length))){return null;
}if(E==-1){return null;
}var B=D.indexOf(";",A);
if(B==-1){B=D.length;
}return unescape(D.substring(A,B));
};
a10.hp.showSkin=function(){var B=a10.util.findPos(document.getElementById("ska"));
var A=document.getElementById("skinPop");
if(A.style.display=="block"){A.style.display="none";
return ;
}a10.skins.checkSelectedSkin();
a10.hp.skinPage(1);
A.style.left=(B[0]-31)+"px";
A.style.top=(B[1]+20)+"px";
A.style.display="block";
if(!a10.hp.skinBubbleCreated){a10.hp.createSkinBubble(A);
}a10.hp.linkClicked=true;
if(typeof a10.nb.close!="undefined"){a10.nb.close();
}if(typeof a10.ss.closePopup!="undefined"){a10.ss.closePopup();
}a10.hp.updateSkinButtonState();
};
a10.hp.createSkinBubble=function(C){var A=$("skinDiv");
var B=new a10.Bubble(C,A,423,parseInt(A.offsetHeight)+50,"up",true,a10.hp.hideSkinDialog,0,26);
var D=function(E){if(!a10.hp.linkClicked){E=E||window.event;
E.cancelBubble=true;
return false;
}};
C.onclick=D;
a10.hp.skinBubbleCreated=true;
};
a10.hp.hideSkinDialog=function(){if(a10.hp.linkClicked){a10.hp.linkClicked=false;
return ;
}if(document.getElementById("skinPop").style.display!="none"){document.getElementById("skinPop").style.display="none";
}};
a10.hp.skh=function(A){};
a10.hp.shs=function(L,C,A,D,N,G,B,F,H,E){if(C==a10.hp.getSkinId()&&C!=""){return false;
}if(!Cookie.isEnabled()){window.location=_urlPrefix+"skinscookies";
return false;
}sct(H);
var K=A!=""?"http://"+_staticUrl+A:"";
var J=B==""?"":B+" "+F;
var O=G==""?"center center":G;
a10.skins.useSkin(C,K,D,N,J,O,true);
a10.hp.hideSkinDialog();
window.skinApplyingDialog.show();
a10.skins.applySkin(K,D,N,J,O,E);
var I=$("peelPromo");
if(I){I.style.display="none";
}var M=$("promo");
if(M){M.style.display="none";
}return false;
};
a10.hp.chDef={c_web:{color:"#82ABBA",bcolor:"#608695",clickId:43652,type:0,qsrc:0,dest:"web"},c_img:{color:"#6F8F4C",bcolor:"#526938",clickId:43466,type:0,qsrc:2072,dest:"pictures"},c_loc:{color:"#A5180D",bcolor:"#6C1009",clickId:43553,type:1,qsrc:0,dest:"http://city.ask.com/city?"},c_new:{color:"#787F7B",bcolor:"#4E5350",clickId:43465,type:1,qsrc:2087,dest:_urlNews},c_blg:{color:"#E28117",bcolor:"#B06412",clickId:45101,type:0,qsrc:2102,dest:"blogsearch"},c_vid:{color:"#D36843",bcolor:"#B05738",clickId:43461,type:0,qsrc:179,dest:"video"},c_shp:{color:"#0A6FA7",bcolor:"#074e76",clickId:43464,type:1,qsrc:2088,dest:_urlShopping},c_map:{color:"#A5180D",bcolor:"#6C1009",clickId:43552,type:1,qsrc:265,dest:_mapsLocale},c_shpUK:{color:"#0A6FA7",bcolor:"#074e76",clickId:43464,type:1,qsrc:2088,dest:_urlShopping}};
a10.hp.ch=function(A,H,I){var G=document.getElementById("q").value;
_channel=A;
a10.ss.hp="true";
if(a10.hp.chDef["c_"+A]["type"]==1){if(G!=""){var F=a10.hp.chDef["c_"+A]["dest"];
F=F.replace("{0}",G);
F=F+_urlSuffix;
I.href=F;
}ct(I,a10.hp.chDef["c_"+A]["clickId"]);
window.location=I.href;
return false;
}if(G!=""){I.href=_urlPrefix+a10.hp.chDef["c_"+A]["dest"]+"?q="+G+"&qsrc="+a10.hp.chDef["c_"+A]["qsrc"]+_urlSuffix;
ct(I,a10.hp.chDef["c_"+A]["clickId"]);
window.location=I.href;
return false;
}sct(a10.hp.chDef["c_"+A]["clickId"]);
var B=document.getElementById("sform");
B.action=a10.hp.chDef["c_"+A]["dest"];
_path=a10.hp.chDef["c_"+A]["dest"];
var K=document.getElementById("tnav").getElementsByTagName("a");
for(var E=0;
E<K.length;
E++){K[E].className="nav";
K[E].style.color=navColor;
}var J=document.getElementById("n_"+A);
if(H==-1){J=document.getElementById("more");
J.getElementsByTagName("a")[0].className="navSelected";
J.getElementsByTagName("a")[0].style.color=navSelectedColor;
document.getElementById("qconn").style.left=(J.offsetLeft+3)+"px";
}else{J.getElementsByTagName("a")[0].className="navSelected";
J.getElementsByTagName("a")[0].style.color=navSelectedColor;
document.getElementById("qconn").style.left=(J.offsetLeft+20)+"px";
}if(H!=-1){document.getElementById("moreLabel").innerHTML="&nbsp;";
}else{if(A=="vid"){document.getElementById("moreLabel").innerHTML="Video";
H=5;
}else{if(A=="blg"){document.getElementById("moreLabel").innerHTML="Blogs";
H=4;
}}}if(a10.browser.isIE6()){document.getElementById("qconn6").style.left="-"+(102+(H*19))+"px";
document.getElementById("qconn6").style.width=(102+(H*19)+19)+"px";
document.getElementById("qcornr6").style.left="-"+(115+(H*28))+"px";
document.getElementById("qcornr6").style.width=(115+(H*28)+28)+"px";
document.getElementById("qcornl6").style.left="-"+(101+(H*28))+"px";
document.getElementById("qcornl6").style.width=(101+(H*28)+28)+"px";
}else{document.getElementById("qconn").style.backgroundPosition="-"+(102+(H*19))+"px -393px";
document.getElementById("qcornr").style.backgroundPosition="-"+(115+(H*28))+"px -297px";
document.getElementById("qcornl").style.backgroundPosition="-"+(101+(H*28))+"px -297px";
}if(A=="web"||A=="blg"){document.getElementById("advlink").style.display="";
document.getElementById("advlink").href=_advPath[A];
document.getElementById("sep").style.display="";
}else{document.getElementById("advlink").style.display="none";
document.getElementById("sep").style.display="none";
}var C=document.getElementById("qradio");
if(C){C.style.display=(A=="web"?"block":"none");
}var D=document.getElementById("bradio");
if(D){D.style.display=(A=="blg"?"block":"none");
}document.getElementById("qbox").style.border="solid 1px "+a10.hp.chDef["c_"+A]["bcolor"];
document.getElementById("qbox").style.backgroundColor=a10.hp.chDef["c_"+A]["color"];
document.getElementById("q").focus();
return false;
};
var li=document.getElementById("skspan");
if(li&&_theme==""){li.style.display="";
}if("event" in a10){a10.event.addListener(document.documentElement,"click",a10.hp.hideSkinDialog);
a10.event.addListener(window,"resize",a10.hp.repositionSkinDialog);
}a10.hp.loadStatic=function(){var A=$("hif");
if(!A){A=document.createElement("iframe");
A.id="hif";
A.name="hif";
A.width=1;
A.height=1;
A.style.visibility="hidden";
A.style.display="block";
document.getElementById("fcon").appendChild(A);
}var C;
if(A.contentWindow){C=A.contentWindow;
}else{if(A.contentDocument){C=A.contentDocument.defaultView;
}else{if(A.Document){C=A.Document.parentWindow;
}}}var B="";
if(typeof (B)!="undefined"){if(C){C.location.replace(B);
}else{A.src=B;
}}if(window.frames["hif"].name!="hif"){window.frames["hif"].name="hif";
}};
function syncAdvSearchParams(C){var B=$F("o");
var E=$F("l");
var D=$F("siteid");
var A=document.getElementById(C);
if(A.o.value!=B){A.o.value=B;
}if(A.l.value!=E){A.l.value=E;
}if("siteid" in A&&A.siteid.value!=D){A.siteid.value=D;
}}a10.hp.staticLoaded=function(B,A){if(A){if(a10.browser.isIE()){var C=document.createStyleSheet("");
C.cssText=A;
}else{var D=document.createElement("style");
document.getElementsByTagName("head")[0].appendChild(D);
D.appendChild(document.createTextNode(A));
}}$("placeholder").innerHTML=B;
_ll(_jsPaths["mystuff"],"mstuf");
if(_jsPaths["dialog"]){_ll(_jsPaths["dialog"],"diag");
}if(_jsPaths["nav"]){_ll(_jsPaths["nav"],"gnav");
}};
function navloaded(){window.optionsMenu=new ask.nav.Menu("oli","settingsMenu",15);
window.myStuffMenu=new ask.nav.MyStuffMenu("mli","myStuffMenu",15);
}function dialogLoaded(){window.signinDialog=new ask.ui.AjaxDialog("signin",GlobalNav.Messages.msSignIn,335,{js:[GlobalNav.Constants.myStuffJsUrl],focusOn:"loginForm",onClose:a10.skins.closeSignIn});
window.optionsDialog=new ask.ui.AjaxDialog("settings","Options",GlobalNav.Variables._optionsDialogWidth,{disableCache:true,noDefaultPadding:true});
window.advSearchDialog=new ask.ui.Dialog("adv_search",GlobalNav.Messages.advSearchTitle,628,{focusOn:"adv_form"});
window.blogsAdvSearchDialog=new ask.ui.Dialog("blogsadvsearch",GlobalNav.Messages.advSearchTitle,651,{focusOn:"blogsadvform"});
window.skinUploadDialog=new ask.ui.Dialog("skinupload",a10.strings.skins_upload+' <span style="color:#000;font-weight:normal">'+a10.strings.skins_step1+"</span>",410,{focusOn:"skinform",onClose:a10.skins.closeUploadDialog});
window.skinApplyingDialog=new ask.ui.Dialog("skinapply","&nbsp;",230);
window.signupDialog=new ask.ui.Dialog("mystuffsignup",a10.strings.signup,410,{focusOn:"registerForm"});
window.skinEditDialog=new ask.ui.Dialog("skinedit",a10.strings.skins_edit,410);
window.skinHPDialog=new ask.ui.Dialog("skinmakehp",a10.strings.skins_hp,220);
window.skinTBDialog=new ask.ui.Dialog("skintoolbar",a10.strings.skins_tb,220);
window.askeraserDialog=new ask.ui.AjaxDialog("askeraser",GlobalNav.Messages.askeraserin,400);
window.askeraseroffDialog=new ask.ui.AjaxDialog("askeraser_off",GlobalNav.Messages.askeraserin,400);
window.askerasercookieDialog=new ask.ui.AjaxDialog("askeraser_cookie",GlobalNav.Messages.askeraserin,400);
window.askerasersuppressDialog=new ask.ui.AjaxDialog("askeraser_suppress",GlobalNav.Messages.askeraserin,400);
var A=$("advlink");
A.onmousedown=null;
A.onclick=a10.hp.showAdvSearch;
if(window["_cssPaths"]){for(var B in _cssPaths){a10.util.insertStyleSheet(_cssPaths[B],B);
}}if(_applySkin&&_bgImg!=""){a10.hp.applySkin();
}if(_openBubble){a10.hp.showSkin();
}if(_openUploadDialog){a10.skins.showUploadDialog();
}if(_skinMetaInfo!=""){a10.hp.copySkin();
}a10.skins.updateCurrentSkinStatus();
}a10.hp.copySkin=function(){window.skinApplyingDialog.show();
var D=_skinMetaInfo.split("&");
var B=[];
for(var A=0;
A<D.length;
A++){var C=D[A].split("=");
B[C[0]]=unescape(C[1]);
}if(B["id"]<1000){a10.skins.useSkin(B["id"],unescape(B["su"]),B["w"],B["h"],B["lc"]+" "+B["sc"],unescape(B["sa"]),true);
a10.skins.applySkin(unescape(B["su"]),B["w"],B["h"],B["lc"]+" "+B["sc"],unescape(B["sa"]));
return ;
}if(_skinUserId){$("skincopyuid").value=_skinUserId;
}$("skincopyurl").value=unescape(B["su"]);
$("skincopyname").value=unescape(B["sn"]);
$("skincopyposition").value=unescape(B["sa"]);
$("skincopycolor").value=B["lc"]+" "+B["sc"];
a10.skins.prepRequest();
$("skinemailcopyform").submit();
};
a10.hp.applySkin=function(){window.skinApplyingDialog.show();
var A=new Image();
var B=function(){$("wrapper").style.backgroundImage="url("+_bgImg+")";
window.skinApplyingDialog.hide();
if(_openHpDialog){a10.hp.showSkinsMakeHomepage();
}_openHpDialog=true;
};
A.onload=function(){var C=new Date().getTime();
var D=C-_startTime;
if(D<2000){setTimeout(B,2000-D);
}else{B();
}};
A.onerror=function(){window.skinApplyingDialog.hide();
};
A.src=_bgImg;
};
a10.hp.showAllSkins=function(A){this.href=A;
ct(this,13035);
window.location=this.href;
};
a10.hp.showSkinsMakeHomepage=function(){if(a10.browser.isIE()&&!a10.hp.isHomepage()&&(_locale=="us"||_locale=="uk")&&Cookie.getCookie("skhp")!="1"&&!(Cookie.getCookie("askeraser")!=null&&Cookie.getCookie("askeraser")!="")){sct(44146);
window.skinHPDialog.show();
}else{a10.hp.showTBDownload();
}};
a10.hp.showTBDownload=function(){var B=Cookie.getCookie("wz_tid");
var A=(B==null||B=="");
if(a10.browser.isIE()&&_locale=="us"&&Cookie.getCookie("sktb")!="1"&&A){new Image().src=_tbImpressionSrc;
window.skinTBDialog.show();
}};
a10.hp.disableToolbarDownload=function(){var A=new Date();
A.setTime(A.getTime()+31536000000);
Cookie.setCookie("sktb",1,A,"/","ask.com");
};
a10.hp.alterOriginCode=function(){if(a10.hp.isHomepage()&&$("origin").value=="0"){$("origin").value="20036";
}if(Cookie.getCookie("sks")=="1"&&$("origin").value=="0"){$("origin").value="10198";
}};
a10.hp.isHomepage=function(){if(a10.browser.isIE()){var A=$("wrapper");
A.style.behavior="url(#default#homepage)";
if(_locale=="uk"){return(A.isHomePage("http://uk.ask.com/")||A.isHomePage("http://uk.ask.com/?&o=0&l=dir&siteid="));
}else{return(A.isHomePage("http://www.ask.com/")||A.isHomePage("http://www.ask.com/?o=0&l=dir"));
}}return false;
};
a10.hp.alterOriginCode();
a10.hp.makeHomepage=function(B){if($("origin").value=="10579"){var A=window.location.toString();
var C=A.indexOf("guaid");
if(C!=-1){var D=A.substring(C+6,A.indexOf("&",C));
new Image().src="http://www.live-conversion.com/conversion.gif?GUAID="+D;
}}B.style.behavior="url(#default#homepage)";
if(_locale=="uk"){B.setHomePage("http://uk.ask.com");
}else{B.setHomePage("http://www.ask.com");
}if($("origin").value=="0"&&a10.hp.isHomepage()){$("origin").value="20036";
}};
a10.hp.disableMakeHomepage=function(){var A=new Date();
A.setTime(A.getTime()+31536000000);
Cookie.setCookie("skhp",1,A,"/","ask.com");
};
a10.hp.showAdvSearch=function(D){D=D||window.event;
sct(43264,this);
var E=a10.browser.innerDimension();
if(E[0]<=800&&E[1]<=600){return true;
}else{if(_channel=="web"){if(a10.browser.isIE()&&!a10.hp.webAdvancedBound){var C=$("adv_form");
var A=C.getElementsByTagName("input");
for(var B=0;
B<A.length;
B++){addInputSubmitEvent(C,A[B]);
}a10.hp.webAdvancedBound=true;
}advSearchDialog.show();
}else{if(a10.browser.isIE()&&!a10.hp.blogAdvancedBound){var C=$("adv_form");
var A=C.getElementsByTagName("input");
for(var B=0;
B<A.length;
B++){addInputSubmitEvent(C,A[B]);
}a10.hp.blogAdvancedBound=true;
}blogsAdvSearchDialog.show();
}a10.event.cancelDefaultAction(D);
return false;
}};
function validateASQuery(){for(var A=0;
A<4;
A++){var B=document.getElementsByName("q"+A);
if(B[0]&&B[0].value.replace(/^\s+|\s+$/,"")!=""){return true;
}}return false;
}function setASParams(){}function addInputSubmitEvent(B,A){A.onkeydown=function(C){C=C||window.event;
if(C.keyCode==13){if(B.onsubmit&&!B.onsubmit()){return false;
}B.submit();
return false;
}};
}ask.closeAllPopUps=function(){if(typeof myStuffMenu!="undefined"){myStuffMenu.hide();
optionsMenu.hide();
}};
a10.hp.loadStatic();
var BlogsAdvSearch={};
BlogsAdvSearch.toggleSearch=function(){var C="";
if(document.getElementById("type_feeds").checked){C="none";
}var D=document.getElementById("sortDiv");
if(D&&D.style){D.style.display=C;
}var A=document.getElementById("dateDiv");
if(A&&A.style){A.style.display=C;
}var B=C=="none"?568:651;
if(a10.browser.isIE6()){$("dialog").style.width=B+"px";
}centerLightbox();
};
window.onresize=windowSizeChanged;
function windowSizeChanged(){if(_maxHeight>0){var A=a10.browser.innerDimension()[1];
if(A>_maxHeight){$("wrapper").style.top=(A-_maxHeight)/2+"px";
}else{$("wrapper").style.top="0";
}}}windowSizeChanged();
if("skins" in a10){window.mystuffSignInCallback=function(A){if(A.status=="success"){a10.skins.setPUID("");
_skinUserId="";
if(A.element&&A.element.selectedskin){a10.skins.applyCurrentSkin(A.element.selectedskin);
}}else{alert(A.element.errMsg);
}};
window.mystuffLogoutCallback=function(){Cookie.deleteCookie("sk2","/",".ask.com");
var A=$("peelPromo");
if(!A){a10.skins.applySkin("",null,null,null,null,null,true);
}else{a10.skins.applySkin(_bgImg,1600,1050,null,"top left","",true,true);
}};
}document.getElementById("wrapper").style.display="";

