if(!ask){var ask={};
}if(!ask.mystuff){ask.mystuff={};
}ask.mystuff.FoldersList=function(B){this.button=$(B);
this.positionHelper=document.createElement("div");
this.menu=document.createElement("div");
this.selectedFID="_root";
this.foldersLookup={};
this.button.parentNode.insertBefore(this.positionHelper,this.button);
this.positionHelper.appendChild(this.button);
this.positionHelper.appendChild(this.menu);
this.button.className="foldersButton";
this.positionHelper.className="positionHelper";
this.menu.className="foldersMenu";
var A=this;
this.button.onclick=function(){A._buttonClicked();
};
this.menu.style.display="none";
this._buildEmptyMenu();
};
a10.util.extend(ask.mystuff.FoldersList,{INDENT:20,ICON_WIDTH:30,activeInstance:null});
ask.mystuff.FoldersList.prototype={loadFolders:function(){this.menu.innerHTML="";
if(ask.mystuff.API.isLoggedInUser()||ask.mystuff.API.isGuestUser()){ask.mystuff.FoldersList.activeInstance=this;
var A=new JSONscriptRequest(ask.mystuff.API.buildRequest("getfolder","ask.mystuff.FoldersList.activeInstance._buildMenu","depth=50"));
A.makeRequest();
}else{this._buildEmptyMenu();
}},selectedID:function(){return this.selectedFID;
},closeMenu:function(){if(a10.element.visible(this.menu)){a10.element.hide(this.menu);
}},_selectItem:function(B){var A;
if(this.selectedFID){A=this.foldersLookup[this.selectedFID];
if(A){A.className="";
}}A=this.foldersLookup[B];
if(!A){A=this.foldersLookup["_root"];
}A.className="selected";
this.selectedFID=B;
this.button.innerHTML=A.innerHTML;
},_updateMenuHeight:function(){if(!a10.browser.isIE6()){return ;
}this.menu.style.height="auto";
var A=a10.element.getHeight(this.menu);
if(A>180){this.menu.style.height="180px";
}},_buttonClicked:function(A){if(a10.element.visible(this.menu)){this.closeMenu();
}else{this.loadFolders();
if(this.menu.style.display=="none"){this.menu.style.left="0";
this.menu.style.top=a10.element.getHeight(this.button)-1+"px";
}a10.element.show(this.menu);
}},_buildEmptyMenu:function(){this._buildMenu({status:"success",element:{foldtree:[]}});
},_buildMenu:function(B){this.foldersLookup={};
if(B.status=="error"){alert("Error while retrieving folders: "+B.element.errMsg);
return ;
}var A=B.element.foldtree||[];
A.splice(0,0,{folderName:"["+GlobalNav.Messages.msSavedResults+"]",guid:"_root"});
this._buildMenuRecursively(A,1);
this._selectItem(this.selectedFID);
this._updateMenuHeight();
},_buildMenuRecursively:function(D,F){if(D.length==0){return ;
}else{for(var C=0;
C<D.length;
C++){var E;
if(F==1){E=30;
}else{E=F*ask.mystuff.FoldersList.INDENT;
}var B=document.createElement("a");
B.innerHTML=a10.util.truncate(D[C].folderName,20);
B.style.paddingLeft=E+"px";
B.style.backgroundPosition=(E-ask.mystuff.FoldersList.ICON_WIDTH)+"px center";
B.guid=D[C].guid;
this.menu.appendChild(B);
var A=this;
B.onclick=function(G){if(!G){G=window.event;
}A._selectItem(a10.event.element(G).guid);
A._buttonClicked(null);
};
this.foldersLookup[D[C].guid]=B;
if(D[C].folders){this._buildMenuRecursively(D[C].folders,F+1);
}}}}};
ask.mystuff.SaveDialogController={init:function(){var I=this;
a10.element.hide("newFolderPane");
a10.element.show("savePane");
var J=$("greeting");
J.innerHTML="";
if(ask.mystuff.API.isLoggedInUser()){var G=document.createTextNode(GlobalNav.Messages.msLoggedInAs+" "+ask.mystuff.API.nickname()+" (");
var A=document.createElement("a");
A.style.fontSize="1em";
A.href="#";
A.onclick=function(){ask.mystuff.API.logout();
myStuffMenu.updateStatus();
I.cancelSave();
};
A.innerHTML=GlobalNav.Messages.msSignOut;
var E=document.createTextNode(")");
J.appendChild(G);
J.appendChild(A);
J.appendChild(E);
}else{var D=document.createTextNode(GlobalNav.Messages.msWelcome+" (");
var C=document.createTextNode(" "+GlobalNav.Messages.msOr+" ");
var B=document.createTextNode(".)");
var H=document.createElement("a");
H.style.fontSize="1em";
H.innerHTML=GlobalNav.Messages.msSignIn;
H.href="#";
H.onclick=function(){I.cancelSave();
signinDialog.show();
return false;
};
var F=document.createElement("a");
F.style.fontSize="1em";
F.innerHTML=GlobalNav.Messages.msCreateAcct;
F.href=GlobalNav.Links.msCreateAcct;
F.onclick=function(){I.cancelSave();
};
J.appendChild(D);
J.appendChild(H);
J.appendChild(C);
J.appendChild(F);
J.appendChild(B);
}if(ask.mystuff.API.isNobody()){a10.element.hide("newFolderLink");
a10.element.hide("diableSaveCheckbox");
}else{a10.element.show("newFolderLink");
a10.element.show("diableSaveCheckbox");
}$("tagCheckbox").checked=false;
foldersDD.closeMenu();
createFolderDD.closeMenu();
},save:function(){ask.mystuff.SaveController.data.title=$("saveDialogTitle").value;
ask.mystuff.SaveController.data.url=$("saveDialogURL").value;
ask.mystuff.SaveController.data.text=$("saveDialogDescription").value;
var B=foldersDD.selectedID();
if(B!="_root"){ask.mystuff.SaveController.data.folderID=B;
}ask.mystuff.SaveController.data.tags=this.parseTags($("saveDialogTags").value);
if(ask.mystuff.SaveController.data.tags==null){alert("Tags contains invalid characters");
return ;
}var A=this.validate();
if(A.status=="error"){alert(A.message);
return ;
}ask.mystuff.SaveController.submitSaveRequest(ask.mystuff.SaveController.data,ask.mystuff.SaveController.saveButton);
this.checkboxChanged($("tagCheckbox"));
saveDialog.hide();
},cancelSave:function(){ask.mystuff.SaveController.updateSaveButtonState(ask.mystuff.SaveController.saveButton,"initial");
saveDialog.hide();
},checkboxChanged:function(B){if(B.checked){var A=B.checked?"on":"off";
var C=new JSONscriptRequest(ask.mystuff.API.buildRequest("changeprofile","","en="+A));
C.makeRequest();
}},parseTags:function(C){var A=[];
C=_mtr(C);
if(C==""){return A;
}if(C.match(/[^\s\w\"\;\:\,]/)){return null;
}var E=new RegExp('".*?"',"g");
A=C.match(E)||[];
C=C.replace(E,"");
for(var D=0;
D<A.length;
D++){A[D]=A[D].substring(1,A[D].length-1);
}var B=C.split(/(\s+)|(\s*\;\s*)|(\s*\:\s*)|(\s*\,\s*)/);
for(var D=0;
D<B.length;
D++){A.push(B[D]);
}for(var D=0;
D<A.length;
D++){if(A[D]&&A[D].match(/^(\s*|\s*\:\s*|\s*\;\s*|\s*\,\s*)$/)){A.splice(D,1);
D--;
}}return A;
},switchToNewFolderPane:function(){$("newFolderName").value="";
foldersDD.closeMenu();
createFolderDD._selectItem("_root");
a10.element.hide("savePane");
a10.element.show("newFolderPane");
$("newFolderName").focus();
},createFolder:function(){var B=createFolderDD.selectedID();
B=(B=="_root")?"":"&pid="+B;
var A=new JSONscriptRequest(ask.mystuff.API.buildRequest("createfolder","ask.mystuff.SaveDialogController.createFolderCallback",a10.form.serialize("createFolder")+B));
A.makeRequest();
},createFolderCallback:function(A){if(A.status=="success"){foldersDD.selectedFID=A.element.folderPath.slice(-32);
foldersDD.loadFolders();
this.backToSavePane();
}else{if(A.element.errMsg){alert(A.element.errMsg);
}else{alert("Folder creation failed.  Please try again later. ");
this.backToSavePane();
}}},backToSavePane:function(){createFolderDD.closeMenu();
a10.element.hide("newFolderPane");
a10.element.show("savePane");
},validate:function(){var A={status:"success"};
if($("saveDialogDescription").value.length>1000){A.status="error";
A.message="Description must be less than 1000 characters";
}return A;
}};
ask.mystuff.SaveController={data:{},saveButton:null,save:function(A){this.saveButton=A.e;
if(this.saveButton.className=="s_mssaved"){return true;
}ask.mystuff.SaveController.data=ask.mystuff.SaveController.extractData(this.saveButton,A.i,A.ps,A.po,A.qu);
if(this.saveButton.className.indexOf("s_ms")!=-1){this.updateSaveButtonState(this.saveButton,"saving");
}if(ask.mystuff.API.shouldShowSaveDialog()){saveDialog.show();
}else{ask.mystuff.SaveController.submitSaveRequest(ask.mystuff.SaveController.data,this.saveButton);
}},dialogDisplayed:function(){if($("foldersDropdown")){window["foldersDD"]=new ask.mystuff.FoldersList("foldersDropdown");
window["createFolderDD"]=new ask.mystuff.FoldersList("createFolderDD");
}ask.mystuff.SaveController.updateDialogWithExtractedData();
ask.mystuff.SaveDialogController.init();
$("saveDialog").style.display="";
},updateDialogWithExtractedData:function(){$("saveDialogTitle").value=ask.mystuff.SaveController.data.title;
$("saveDialogURL").value=ask.mystuff.SaveController.data.url;
$("saveDialogDescription").value=ask.mystuff.SaveController.data.text;
$("saveDialogTags").value="";
foldersDD._selectItem("_root");
},extractData:function(E,D,F,B,H){var G={saveServiceUrl:null,title:null,text:null,url:null,iurl:null,bid:null,query:null,cat:null,kbid:null,tags:null,folderID:null};
B=B||{};
if(E.innerHTML.toLowerCase().indexOf("img")!=-1){B.pt="";
}else{B.pt=E.innerHTML;
}G.saveServiceUrl=F==5?MyStuff.linkSAMjPost:MyStuff.linkMjPost;
G.query=(H)?H:document.ft.q.value;
B.u=G.saveServiceUrl;
B.io=D;
if(F==1||F==2||F==6){var C=(F==1||F==6)?obj("r"+D).href:window.location.href;
G.title=_mext(_md(C),"fn=","&");
G.iurl=_mext(_md(C),"imagesrc=","&");
G.url=_mext(_md(C),"desturi=","&");
G.text="";
G.cat="img";
if(F==6){B.en="qm";
}}else{if(F==4){G.title=obj("r"+D+"_t").innerHTML;
G.bid=obj("r"+D+"_b").innerHTML;
G.text=_ma(D);
G.url="http://"+obj("r"+D+"_u").innerHTML;
G.cat="wb";
B.en="tp";
}else{if(F==5){G.kbid=D;
G.cat="sa";
G.iurl="";
B.en="qm";
}else{if(F==7){G.title=obj("r"+D+"_t").innerHTML;
G.text=_ma(D);
G.url=obj("r"+D+"_t").href;
G.cat="wb";
B.pt=ptxt(obj("r"+D+"_t"));
B.u=G.url;
}else{if(F==8){var A=$("picBox"+D);
G.title=a10.util.getElementsByClassName("fullTitle",A)[0].innerHTML;
G.iurl=a10.util.getElementsByClassName("thumbnailUrl",A)[0].innerHTML;
G.url=a10.util.getElementsByClassName("titleLink",A)[0].href;
G.cat="vd";
G.text="";
}else{G.title=obj("r"+D+"_t").innerHTML;
G.text=_ma(D);
G.bid=(F==0)?_mb(D):obj("r"+D+"_b").innerHTML;
G.url="http://"+obj("r"+D+"_u").innerHTML;
G.cat="wb";
B.pt=ptxt(obj("r"+D+"_t"));
B.u=G.url;
}}}}}G.text=(G.text)?_mtr(_str(G.text)):"";
G.text=_mtr(G.text.replace(/&amp;/g,"&"));
G.title=_str(G.title);
G.title=_mtr(G.title.replace(/&amp;/g,"&"));
if(!(F==2||F==3||F==4)){spk(E,B);
}else{sct(43632);
}return G;
},updateSaveButtonState:function(D,C,A){var B=D.parentNode;
D.href=A||"javascript:void(0)";
if(C=="saved"){D.className="s_mssaved";
D.title=GlobalNav.Messages.msSaved;
B.style.visibility="visible";
B.ignore=true;
}else{if(C=="initial"){D.className="s_mssave_n";
D.title=GlobalNav.Messages.msSave;
B.style.visibility="hidden";
B.ignore=false;
}else{if(C=="saving"){D.className="s_mssaving";
D.title=GlobalNav.Messages.msSaving;
B.style.visibility="visible";
B.ignore=true;
}}}},submitSaveRequest:function(C,B){if(B.sv||save!=null){return ;
}B.sv=1;
save=B;
if(B.className.indexOf("s_ms")==-1){B.innerHTML=MyStuff.msgSaving;
}var A=mjif.document.sform;
A.action=C.saveServiceUrl;
A.text.value=C.text;
A.title.value=C.title;
A.category.value=C.cat;
A.query.value=C.query;
if(C.url){A.url.value=C.url.replace(/&amp;/g,"&");
}A.iurl.value=C.iurl;
A.binoid.value=(C.bid)?C.bid:"";
A.kbid.value=(C.kbid)?C.kbid:"";
A.fid.value=(C.folderID)?C.folderID:"";
if(C.tags){ask.mystuff.SaveController.removeTagFields(A);
ask.mystuff.SaveController.addTagFields(A,C.tags);
}A.submit();
},removeTagFields:function(B){var C=B.tag;
if(C==undefined){return ;
}else{if(C.length==undefined){C=[C];
}}for(var A=0;
A<C.length;
A++){C[A].parentNode.removeChild(C[A]);
}},addTagFields:function(D,B){for(var C=0;
C<B.length;
C++){var A=mjif.document.createElement("input");
A.type="hidden";
A.name="tag";
A.value=B[C];
D.appendChild(A);
}}};
ask.mystuff.API={buildRequest:function(B,E,C){var A="http://"+GlobalNav.Constants.myStuffDomain+"/service/api/";
var D="output=json&total=30&userApp=GlobalNav&callback=";
return A+B+"?"+D+E+(C?"&"+C:"");
},isLoggedInUser:function(){return(Cookie.getCookie("AUID"));
},isGuestUser:function(){return !ask.mystuff.API.isLoggedInUser()&&Cookie.getCookie("PUID");
},isNobody:function(){return !ask.mystuff.API.isLoggedInUser()&&!ask.mystuff.API.isGuestUser();
},nickname:function(){var A=decodeURIComponent(escape(Cookie.getCookie("nname")));
if(A&&A!=""){A=A.replace(/\+/g," ");
}else{A=ask.mystuff.API.userEmail();
}return A;
},userEmail:function(){var A=ask.mystuff.API.isLoggedInUser();
if(!A){return null;
}return A.substring(A.lastIndexOf("|")+1);
},logout:function(){Cookie.deleteCookie("AUID","/",".ask.com");
if(typeof mystuffLogoutCallback!="undefined"){mystuffLogoutCallback();
}else{Cookie.deleteCookie("sk2","/",".ask.com");
}},shouldShowSaveDialog:function(){return ask.mystuff.API.isNobody()||!(Cookie.getCookie("editnote")=="on");
}};
ask.mystuff.SignUp={};
ask.mystuff.SignUp.closeDialog=function(){window.signupDialog.hide();
ask.mystuff.SignUp.close();
return false;
};
ask.mystuff.SignUp.close=function(){if(typeof ask.mystuff.SignUp.onClose!="undefined"&&ask.mystuff.SignUp.onClose!=null){ask.mystuff.SignUp.onClose();
}return true;
};
ask.mystuff.SignUp.step1=function(A){if(!A){$("skinemail").value="";
$("skinemail2").value="";
$("nick").value="";
$("pw1").value="";
$("pw2").value="";
$("skinAge").checked=false;
$("skinNewsletter").checked=true;
$("skinMigrate").checked=true;
}$("signupEmailErrorLabel").style.display="none";
_ll(GlobalNav.Constants.myStuffJsUrl,"mystuffAuth");
ask.mystuff.SignUp.clearSignupErrors();
$("signUpStep2").style.display="none";
$("signUpStep1").style.display="";
};
ask.mystuff.SignUp.step2=function(){$("signUpStep1").style.display="none";
$("signUpStep2").style.display="";
};
ask.mystuff.SignUp.checkSignUp=function(){if($("skinemail").value.length==0){ask.mystuff.SignUp.clearSignupErrors();
a10.skins.showErrorMessage("signupEmailErrorLabel",a10.strings.signup_emaillength);
a10.skins.showError("skinemail");
return ;
}if($("skinemail").value!=$("skinemail2").value){ask.mystuff.SignUp.clearSignupErrors();
a10.skins.showErrorMessage("signupEmailErrorLabel",a10.strings.signup_emailmismatch);
a10.skins.showError("skinemail");
a10.skins.showError("skinemail2");
return ;
}var C=$("pw1").value;
if(C.length<6||C.length>32){ask.mystuff.SignUp.clearSignupErrors();
a10.skins.showErrorMessage("signupEmailErrorLabel",a10.strings.signup_pwlength);
a10.skins.showError("pw1");
return ;
}if(C!=$("pw2").value){ask.mystuff.SignUp.clearSignupErrors();
a10.skins.showErrorMessage("signupEmailErrorLabel",a10.strings.signup_pwmismatch);
a10.skins.showError("pw1");
a10.skins.showError("pw2");
return ;
}var A=$("nick").value;
if(A.length<2||A.length>32){ask.mystuff.SignUp.clearSignupErrors();
a10.skins.showErrorMessage("signupEmailErrorLabel",a10.strings.signup_nicklength);
a10.skins.showError("nick");
return ;
}$("crep").value=EncodeBase64(MD5($("pw1").value));
$("crepcon").value=$("crep").value;
var B="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
$("pw1").value=B.substring(0,$("pw1").value.length);
$("pw2").value=$("pw1").value;
ask.mystuff.SignUp.clearSignupErrors();
ask.mystuff.SignUp.step2();
};
ask.mystuff.SignUp.signUpHandler=function(A){if(A.status=="success"){window.signupDialog.hide();
if(typeof mystuffSignUpCallback!="undefined"){mystuffSignUpCallback();
}}else{ask.mystuff.SignUp.step1();
ask.mystuff.SignUp.clearSignupErrors();
a10.skins.showErrorMessage("signupEmailErrorLabel",A.element.errMsg);
}};
ask.mystuff.SignUp.clearSignupErrors=function(){a10.skins.clearError("skinemail");
a10.skins.clearError("skinemail2");
a10.skins.clearError("pw1");
a10.skins.clearError("pw2");
a10.skins.clearError("nick");
};
ask.mystuff.SignUp.signup=function(){if(!$("skinAge").checked){ask.mystuff.SignUp.clearSignupErrors();
a10.skins.showErrorMessage("signupAgeErrorLabel",a10.strings.signup_tos);
a10.skins.showError("skinAge");
return ;
}document.domain="ask.com";
$("registerForm").submit();
};
if(!save){var save=null;
}function _md(A){A=decodeURIComponent(A);
return decodeURIComponent(A);
}function _mext(D,A,E){var C,B;
C=D.indexOf(A)+A.length;
B=D.indexOf(E,C);
return D.substring(C,B);
}function _ma(A){if(null==obj("r"+A+"_a")){return"";
}return _mtr(_str(obj("r"+A+"_a").innerHTML));
}function _mb(A){b=obj("r"+A+"_b");
b=(b)?b.onmouseover.toString():"";
b=b.match(/b_s\(.*['"]*(\w{32})&s=\d+['"]/);
return(b)?b[1]:"";
}function _str(A){var B=/<\/?[^>]+>/ig;
return(A)?A.replace(B,""):"";
}function _mtr(A){A=A.replace(/^\s*/,"");
return A.replace(/\s*$/,"");
}function _ms(C,B,D,A,F){var E=ask.mystuff.SaveController.extractData(C,B,D,A,F);
ask.mystuff.SaveController.submitSaveRequest(E,C);
}
if(!ask){var ask={};
}if(!ask.nav){ask.nav={};
}ask.nav.Menu=function(A,C,B){this.link=$(A);
this.menu=$(C);
this.offset=B||0;
this.hoverTimeoutID=null;
this.activityID=30735;
var D=this;
if(this.link){this.link.onclick=function(){D.toggle();
return false;
};
}a10.event.addListener(document,"click",function(E){D._documentClicked(E);
});
if(a10.browser.isIE6()){if(!this.cover&&this.menu){this.cover=new a10.IFrameCover(this.menu.id,{left:3,width:-6,height:-4});
}}};
ask.nav.Menu.prototype={toggle:function(){if(!a10.element.visible(this.menu)){this.show();
}else{this.hide();
}},show:function(){if(this.activityID){sct(this.activityID);
}if(a10.element.visible(this.menu)){return ;
}if(ask.closeAllPopUps){ask.closeAllPopUps();
}var B=a10.util.findPos(this.link);
if(a10.browser.isFirefox()){this.menu.style.right=a10.browser.innerDimension()[0]-B[0]-this.link.offsetWidth-18+"px";
}else{if(!a10.browser.isIE6()){this.menu.style.right=a10.browser.innerDimension()[0]-B[0]-this.link.offsetWidth-1+"px";
}else{this.menu.style.right=a10.browser.innerDimension()[0]-B[0]-this.link.offsetWidth-2+"px";
}}if(document.getElementById("ask_header")){var A=$("header_promo")?$("header_promo").offsetHeight:0;
if(!a10.browser.isIE6()){this.menu.style.top=this.link.offsetTop+$("ask_header").offsetHeight+(a10.browser.isIE()?-1:-4)-A+1+"px";
}else{this.menu.style.top=this.link.offsetTop+$("ask_header").offsetHeight-A+"px";
}}else{this.menu.style.top=B[1]+this.offset+"px";
}a10.element.show(this.menu);
if(a10.browser.isIE6()){this.cover.show();
}},hide:function(){if(!a10.element.visible(this.menu)){return ;
}if(a10.browser.isIE6()){this.cover.hide();
}a10.element.hide(this.menu);
},_documentClicked:function(B){var A=B.clientX;
var C=B.clientY;
if(!a10.element.containsPoint(this.menu,A,C,false)&&!a10.element.containsPoint(this.link,A,C,false)){this.hide();
if(this.link&&(this.link.id=="optionsLink")&&this.link.className&&(GlobalNav.Messages.msLocale!="fr_FR")){this.link.className="ask_header_item";
}}},_startHoverTimeout:function(A){var B=this;
this.hoverTimeoutID=setTimeout(function(){B.hoverTimeoutID=null;
B.show();
},250);
},_clearHoverTimeout:function(A){clearTimeout(this.hoverTimeoutID);
this.hoverTimeoutID=null;
}};
ask.nav.MoreMenu=function(A,C,B){this.link=$(A);
this.menu=$(C);
this.offset=B||0;
this.hoverTimeoutID=null;
this.activityID=30735;
var D=this;
if(this.link){this.link.onclick=function(){D.toggle();
return false;
};
}a10.event.addListener(document,"click",function(E){D._documentClicked(E);
});
if(a10.browser.isIE6()){if(!this.cover&&this.menu){this.cover=new a10.IFrameCover(this.menu.id,{left:0,width:2,height:2});
}}};
a10.util.subclass(ask.nav.MoreMenu,ask.nav.Menu);
a10.util.extend(ask.nav.MoreMenu.prototype,{show:function(){if(this.activityID){sct(this.activityID);
}if(a10.element.visible(this.menu)){return ;
}if(ask.closeAllPopUps){ask.closeAllPopUps();
}this.menu.style.left=ask.nav.MoreMenu.prototype.pageX(this.link)-1+"px";
this.menu.style.display="block";
if(a10.browser.isIE6()){this.cover.show();
}},hide:function(){if(this.link){this.link.style.fontWeight="";
}ask.nav.MoreMenu.superClass.hide.call(this);
},_documentClicked:function(B){var A=B.clientX;
var C=B.clientY;
if(!a10.element.containsPoint(this.menu,A,C,false)&&!a10.element.containsPoint(this.link,A,C,false)){this.hide();
if(this.link&&(this.link.id=="ask_header_moreLink")&&this.link.className&&(GlobalNav.Messages.msLocale!="fr_FR")){this.link.className="ask_header_item";
}}},pageX:function(B){var A=B.offsetLeft;
while((B=B.offsetParent)){A+=B.offsetLeft;
}return A;
}});
ask.nav.MyStuffMenu=function(A,C,B){ask.nav.MyStuffMenu.baseConstructor.call(this,A,C,B);
this.wasClicked=false;
this.slides=new Array();
var D=this;
a10.event.addListener(this.menu,"click",function(){D.wasClicked=true;
});
if($("signOutLink")){$("signOutLink").onclick=function(){D.signOut();
return false;
};
}if($("backButton")){$("backButton").onclick=function(){D.back();
return false;
};
}};
a10.util.subclass(ask.nav.MyStuffMenu,ask.nav.Menu);
a10.util.extend(ask.nav.MyStuffMenu.prototype,{show:function(){if(a10.element.visible(this.menu)){return ;
}this.updateStatus();
ask.nav.MyStuffMenu.superClass.show.call(this);
this.updateSlideHeight(this.currentSlide());
},hide:function(){this.reset();
ask.nav.MyStuffMenu.superClass.hide.call(this);
},_documentClicked:function(B){var A=B.clientX;
var C=B.clientY;
if(!this.wasClicked&&!a10.element.containsPoint(this.link,A,C,false)){this.hide();
if(this.link&&(this.link.id=="myStuffLink")&&this.link.className&&(GlobalNav.Messages.msLocale!="fr_FR")){this.link.className="ask_header_item";
}}this.wasClicked=false;
},updateStatus:function(){a10.element.hide("userMenu");
a10.element.hide("guestMenu");
a10.element.hide("nobodyMenu");
var B;
if(ask.mystuff.API.isLoggedInUser()){var A=ask.mystuff.API.nickname();
B=a10.util.getMyStuffTitle(GlobalNav.Messages.msTitleDefault,GlobalNav.Messages.msTitleSpecial,A,GlobalNav.Messages.msLocale);
a10.element.show("userMenu");
this.activityID=51237;
}else{if(ask.mystuff.API.isGuestUser()){B=GlobalNav.Messages.msGuestTitle;
a10.element.show("guestMenu");
this.activityID=43759;
}else{B=GlobalNav.Messages.msDefaultTitle;
a10.element.show("nobodyMenu");
this.activityID=43759;
}}if($("mslabel")){$("mslabel").innerHTML=B;
}if($("myStuffTitle")){$("myStuffTitle").innerHTML=B;
}},signOut:function(){ask.mystuff.API.logout();
this.updateStatus();
if(ask.closeAllPopUps){ask.closeAllPopUps();
}},currentSlide:function(){if(this.menu){var B=this.menu.childNodes;
for(var A=0;
A<B.length;
A++){if(B[A].className=="slide"&&a10.element.visible(B[A])){return B[A];
}}}},newSlide:function(A){var C=this.currentSlide();
var B=$("backButton");
a10.element.hide(C);
this.menu.insertBefore(A,C);
a10.element.show(A);
this.slides.push(C);
if(!a10.element.visible(B)){a10.element.show(B);
}if(a10.browser.isIE6()){this.updateSlideHeight(A);
this.cover.reposition();
}},back:function(){var C=this.currentSlide();
var B=this.slides.pop();
if(!B){return ;
}this.menu.insertBefore(B,C);
this.menu.removeChild(C);
a10.element.show(B);
var A=this.slides.length==0;
if(A){a10.element.hide("backButton");
}if(a10.browser.isIE6()){this.updateSlideHeight(B);
this.cover.reposition();
}return !A;
},reset:function(){while(this.back()){}},updateSlideHeight:function(B){if(!a10.browser.isIE6()){return ;
}var C=B.getElementsByTagName("ul")[0];
C.style.height="auto";
var A=a10.element.getHeight(C);
if(A>200){C.style.height="200px";
}}});
ask.nav.MyStuffMenuSlide=function(B){this.slideDiv=document.createElement("div");
this.slideDiv.style.display="none";
this.slideDiv.className="slide";
var A=document.createElement("div");
A.className="title";
A.innerHTML=a10.util.truncate(B,ask.nav.MyStuffMenuSlide.TITLE_LENGTH);
this.slideDiv.appendChild(A);
this.contentDiv=document.createElement("ul");
this.contentDiv.className="content";
this.slideDiv.appendChild(this.contentDiv);
this.hasContent=false;
};
ask.nav.MyStuffMenuSlide.TITLE_LENGTH=29;
ask.nav.MyStuffMenuSlide.LABEL_LENGTH=35;
ask.nav.MyStuffMenuSlide.prototype={addEntry:function(F,E,D,C){var A=document.createElement("li");
A.className=F;
var B=document.createElement("a");
B.href=E;
B.className="L19";
A.appendChild(B);
if(C){B.onclick=C;
}B.onmousedown=function(){sct(51137);
};
D=a10.util.truncate(D,ask.nav.MyStuffMenuSlide.LABEL_LENGTH);
if(F=="folder"){var G=document.createElement("div");
G.innerHTML=a10.util.htmlEncode(D);
B.appendChild(G);
}else{B.innerHTML=a10.util.htmlEncode(D);
}this.contentDiv.appendChild(A);
this.hasContent=true;
},toDiv:function(){if(!this.hasContent){var A=document.createElement("li");
A.className="noResult";
A.innerHTML=GlobalNav.Messages.msNoResult;
this.contentDiv.appendChild(A);
}return this.slideDiv;
}};
ask.nav.MyStuffMenuController={show:{recentSearches:function(){var A=new JSONscriptRequest(ask.mystuff.API.buildRequest("getsavehistory","ask.nav.MyStuffMenuController.process.recentSearches"));
A.makeRequest();
},savedResults:function(){var A=new JSONscriptRequest(ask.mystuff.API.buildRequest("getfolder","ask.nav.MyStuffMenuController.process.savedResults"));
A.makeRequest();
},folders:function(){var A=new JSONscriptRequest(ask.mystuff.API.buildRequest("getfolder","ask.nav.MyStuffMenuController.process.folders"));
A.makeRequest();
},folder:function(A){var B=new JSONscriptRequest(ask.mystuff.API.buildRequest("getfolder","ask.nav.MyStuffMenuController.process.folders","folderID="+A));
B.makeRequest();
return false;
},tags:function(){var A=new JSONscriptRequest(ask.mystuff.API.buildRequest("gettag","ask.nav.MyStuffMenuController.process.tags"));
A.makeRequest();
},tag:function(A){var B=new JSONscriptRequest(ask.mystuff.API.buildRequest("gettag","ask.nav.MyStuffMenuController.process.tag","tagName="+A));
B.makeRequest();
return false;
}},process:{recentSearches:function(B){if(B.status=="success"){var A=ask.nav.MyStuffMenuController.buildSlide(B.element,GlobalNav.Messages.msRecent,"history");
myStuffMenu.newSlide(A);
}else{alert("display failure");
}},savedResults:function(B){if(B.status=="success"){var A=ask.nav.MyStuffMenuController.buildSlide(B.element,GlobalNav.Messages.msSavedResults,"savedResults");
myStuffMenu.newSlide(A);
}else{alert("display failure");
}},folders:function(C){if(C.status=="success"){var D,B;
if(!C.element.folderPath){D=GlobalNav.Messages.msFolders;
B="topFolders";
}else{D=C.element.folderName;
B="folder";
}var A=ask.nav.MyStuffMenuController.buildSlide(C.element,D,B);
myStuffMenu.newSlide(A);
}else{alert("display failure");
}},tags:function(B){if(B.status=="success"){var A=ask.nav.MyStuffMenuController.buildSlide(B.element,GlobalNav.Messages.msTags,"tag");
myStuffMenu.newSlide(A);
}else{alert("display failure");
}},tag:function(B){if(B.status=="success"){var A=ask.nav.MyStuffMenuController.buildSlide(B.element,B.element.tag,"savedResults");
myStuffMenu.newSlide(A);
}else{alert("display failure");
}}},buildSlide:function(E,K,J){var G=new ask.nav.MyStuffMenuSlide(K);
var D={"Pictures":"image","Web":"web","web":"web","image":"image","video":"video","Blog":"blogs","Video":"video"};
var I={"Pictures":GlobalNav.Constants.imageURL,"image":GlobalNav.Constants.imageURL,"Web":GlobalNav.Constants.webURL,"web":GlobalNav.Constants.webURL,"Blog":GlobalNav.Constants.blogURL,"Video":GlobalNav.Constants.videoURL};
if((!E.folders||E.folders.length==0)&&(!E.results||E.results.length==0)){return G.toDiv();
}if(J=="folder"){H(E.folders,G);
}if(J=="topFolders"){H(E.folders,G);
return G.toDiv();
}if(J=="tag"){C(E.results,G);
return G.toDiv();
}for(var F=0;
F<E.results.length;
F++){var L=E.results[F];
var B;
var A;
if(J=="history"){A=L.query;
if(I[L.type]){B=I[L.type].replace(/qsrc=\d*/,"qsrc=177")+encodeURIComponent(L.query);
}else{a10.debug("WARNING: Unexpected Recent Search type: "+L.type+".  Skipping this item.");
continue;
}}else{B=L.type=="video"?L.surl:L.url;
A=L.name||null;
}G.addEntry(D[L.type],B,A);
}return G.toDiv();
function H(Q,N){for(var P=0;
P<Q.length;
P++){var M=Q[P];
var O=function(R){return function(){return ask.nav.MyStuffMenuController.show.folder(R);
};
}(M.guid);
N.addEntry("folder","#",M.name,O);
}}function C(Q,N){for(var P=0;
P<Q.length;
P++){var M=Q[P];
var O=function(R){return function(){return ask.nav.MyStuffMenuController.show.tag(R);
};
}(M.name);
N.addEntry("folder","#",M.name,O);
}}}};
ask.nav.OptionsMenuController={showDialogWithTab:function(A){optionsDialog.tabToShow=A||"locations";
optionsDialog.show();
}};
if(typeof navloaded!="undefined"){navloaded();
}
if(!ask){var ask={};
}if(!ask.ui){ask.ui={};
}ask.ui.DialogBase=function(E,C,B,A){this.id=E;
this.title=C;
this.width=B;
this.options=A||{};
this.cover=null;
var D=this;
this.closeButtonHandler=this.options.closeButtonHandler||function(){D.hide();
};
this.windowResizedHandler=function(){D.windowResized();
};
this.windowScrolledHandler=function(){D.windowScrolled();
};
};
a10.util.extend(ask.ui.DialogBase,{JSP_PREFIX:"http://"+GlobalNav.Constants.askDomain+"/",SCRIPT_PREFIX:"inc/js/a10f/dialogs/"});
a10.util.extend(ask.ui.DialogBase.prototype,{show:function(){var A=this;
if(ask.closeAllPopUps){ask.closeAllPopUps();
}$("dialogTitle").innerHTML=this.title;
a10.event.addListener($("dialogCloseButton"),"click",this.closeButtonHandler);
a10.event.addListener(window,"resize",this.windowResizedHandler);
a10.event.addListener(window,"scroll",this.windowScrolledHandler);
$("dialogContent").style.padding=this.options.noDefaultPadding?"0":"";
},afterSwap:function(){if(a10.browser.isIE6()&&this.cover){this.cover.hide();
}if(a10.browser.isIE6()&&this.width){$("dialog").style.width=this.width+"px";
}this.centerDialog(true);
this.updateLightBoxCoverSize();
a10.element.show("lightboxCover");
a10.element.show("lightbox");
if(a10.browser.isIE6()){if(!this.cover){this.cover=new a10.IFrameCover("dialog");
}this.cover.show();
}if(this.options.focusOn){var A=a10.form.getElements(this.options.focusOn)[0];
try{A.focus();
}catch(B){}}if(this.options["onDisplay"]){this.options.onDisplay();
}},hide:function(){a10.event.removeListener($("dialogCloseButton"),"click",this.closeButtonHandler);
a10.event.removeListener(window,"resize",this.windowResizedHandler);
a10.event.removeListener(window,"scroll",this.windowScrolledHandler);
$("dialogContent").style.padding="";
$("dialog").style.width="";
if(a10.browser.isIE6()){this.cover.hide();
}a10.element.hide("lightboxCover");
a10.element.hide("lightbox");
if(this.options&&this.options.onAfterClose){this.options.onAfterClose();
}},centerDialog:function(A){var D=a10.browser.innerDimension();
var C=$("lightbox");
if(C&&(C.style.display!="none"||A)){C.style.left=((D[0]/2)-(a10.element.getWidth(C)/2))+"px";
var B=(D[1]/2)-(a10.element.getHeight(C)/2);
if(a10.browser.isIE6()){B+=a10.util.scrollTop();
}if(B<0){B=0;
}C.style.top=B+"px";
if(a10.browser.isIE6()){if(this.cover){this.cover.reposition();
}}}},updateLightBoxCoverSize:function(){if(!a10.browser.isIE6()){return ;
}var I=$("lightboxCover");
var F=$("leftRail");
var E=$("midRail");
var A=$("rightRail");
var B;
if(F){var H=F.offsetTop+F.offsetHeight;
var D=E.offsetTop+E.offsetHeight;
var G=A.offsetTop+A.offsetHeight;
B=H;
if(D>B){B=D;
}if(G>B){B=G;
}if(a10.browser.isIE6()){B+=($("ask_header")?$("ask_header").offsetHeight*2:0);
}}else{if(E){var D=E.offsetTop+E.offsetHeight;
var G=A.offsetTop+A.offsetHeight;
B=Math.max(D,G)+(a10.browser.isIE6()&&$("top_search")?$("top_search").offsetHeight:0);
if(a10.browser.isIE6()){B+=($("ask_header")?$("ask_header").offsetHeight*2:0);
}}else{B=document.body.offsetHeight;
var C=document.documentElement.clientHeight;
if(C&&C>B){B=C;
}}}I.style.height=B+"px";
},windowResized:function(){this.updateLightBoxCoverSize();
this.centerDialog();
},windowScrolled:function(){if(a10.browser.isIE6()){this.centerDialog();
}}});
ask.ui.AjaxDialog=function(D,C,B,A){ask.ui.AjaxDialog.baseConstructor.call(this,D,C,B,A);
};
a10.util.subclass(ask.ui.AjaxDialog,ask.ui.DialogBase);
a10.util.extend(ask.ui.AjaxDialog.prototype,{show:function(){var D=this;
ask.ui.AjaxDialog.superClass.show.call(this);
var B=this.options.disableCache?"?cacheBuster="+new Date().getTime():"";
a10.ajax.get(ask.ui.DialogBase.JSP_PREFIX+this.id+B,C,A);
function C(E){$("dialogContent").innerHTML=E.responseText;
if(!D.options.nojs){a10.util.insertScript(ask.ui.DialogBase.SCRIPT_PREFIX+D.id+".js","modalDialogScript");
if(D.options.js){for(var F=0;
F<D.options.js.length;
F++){a10.util.insertScript(D.options.js[F],"modalDialogScript");
}}}D.afterSwap();
}function A(E){alert("Failed to retrieve dialog contant: "+E.statusText);
}},hide:function(){if(this.options&&this.options.onClose&&!this.options.onClose()){return ;
}a10.util.removeElementsWithClass("modalDialogScript");
ask.ui.AjaxDialog.superClass.hide.call(this);
}});
ask.ui.Dialog=function(D,C,B,A){ask.ui.Dialog.baseConstructor.call(this,D,C,B,A);
};
a10.util.subclass(ask.ui.Dialog,ask.ui.DialogBase);
a10.util.extend(ask.ui.Dialog.prototype,{show:function(){ask.ui.Dialog.superClass.show.call(this);
$("dialogContent").innerHTML="";
$("dialogContent").appendChild($(this.id));
a10.element.show(this.id);
this.afterSwap();
},hide:function(){if(this.options&&this.options.onClose&&!this.options.onClose()){return ;
}var A=$("dialogContent").firstChild;
a10.element.hide(A);
document.body.appendChild(A);
if($("videoUI_rollover")&&$("videoUI_rollover").innerHTML&&($("videoUI_rollover").innerHTML.indexOf("embed")>-1)){$("videoUI_rollover").innerHTML='<embed wmode="window"'+$("videoUI_rollover").innerHTML.substring($("videoUI_rollover").innerHTML.indexOf("embed")+5);
}ask.ui.Dialog.superClass.hide.call(this);
}});
ask.ui.VideoDialog=function(E,C,B,A){this.id=E;
this.title=C;
this.width=B;
this.options=A||{};
this.cover=null;
var D=this;
this.closeButtonHandler=this.options.closeButtonHandler||function(){D.hide();
};
this.windowResizedHandler=function(){D.windowResized();
};
this.windowScrolledHandler=function(){D.windowScrolled();
};
this.clickHandler=function(G){if($("dialog").offsetHeight>0){D.signClicked=false;
}var F=G.clientX;
var H=G.clientY;
if(!a10.element.containsPoint($("videoUI_container"),F,H,false)&&D.wasClicked&&D.signClicked){D.hide();
}D.wasClicked=true;
if($("dialog").offsetHeight==0){D.signClicked=true;
}};
};
a10.util.extend(ask.ui.VideoDialog,{JSP_PREFIX:"http://"+GlobalNav.Constants.askDomain+"/",SCRIPT_PREFIX:"inc/js/a10f/dialogs/"});
a10.util.extend(ask.ui.VideoDialog.prototype,{show:function(A,K,E,J,C,I,D,P,H,O,M,G){var F=this;
this.wasClicked=false;
this.signClicked=true;
if(ask.closeAllPopUps){ask.closeAllPopUps();
}$("videoUI_dialog").innerHTML="";
$("videoUI_dialog").appendChild($(this.id));
$("videoUI_rollover").innerHTML="";
if(I){$("videoUI_channel").innerHTML=I;
$("videoUI_dash").innerHTML="-";
}else{$("videoUI_channel").style.display="none";
$("videoUI_dash").style.display="none";
}if(C){$("videoUI_date").innerHTML=M;
}else{$("videoUI_date").style.display="none";
}if(H){$("videoUI_duration").innerHTML=" - Duration:"+Math.floor(parseInt(H)/1000/60)+"'"+Math.floor(parseInt(H)/1000%60);
}else{$("videoUI_duration").style.display="none";
}if(O){$("videoUI_format").innerHTML=" - File Format:"+O;
}else{$("videoUI_format").style.display="none";
}if(G){if(navigator.userAgent.toLowerCase().indexOf("mac")&&a10.browser.isFirefox()){$("videoUI_rollover").innerHTML='<embed wmode="window"'+G.substring(G.indexOf("embed")+5);
}else{$("videoUI_rollover").innerHTML="<"+G;
}}if(J){$("videoUI_summary").innerHTML=J;
}else{$("videoUI_summary").style.display="none";
}var N="";
if(J){N=$("videoUI_emaildes").innerHTML+"<"+J+">\n"+$("videoUI_emailurl").innerHTML+"<"+E+">\n\n"+$("videoUI_emailend").innerHTML+"\n"+$("videoUI_emailcom").innerHTML;
}else{N=$("videoUI_emailurl").innerHTML+"<"+E+">\n\n"+$("videoUI_emailend").innerHTML+"\n"+$("videoUI_emailcom").innerHTML;
}$("videoUI_email").href="mailto:?subject="+encodeURIComponent($("videoUI_emailsubject").innerHTML+"<"+K+">")+"&body="+encodeURIComponent(N);
$("videoUI_embedText").value="<"+G;
$("videoUI_urlText").value=E;
$("videoUI_embed").style.display="none";
$("videoUI_url").style.display="none";
$("videoUI_dialogTitle").href=E;
if($("videoUI_save")&&$("videoUI_"+A)){$("videoUI_nosave").style.display="inline";
$("videoUI_save").onclick=function(){if($("videoUI_"+A)){$("videoUI_"+A).onclick();
$("videoUI_rollover").innerHTML='<embed wmode="transparent"'+G.substring(G.indexOf("embed")+5);
}sct(44071,$("videoUI_save"));
return false;
};
}else{$("videoUI_nosave").style.display="none";
}a10.event.addListener($("videoUI_dialogCloseButton"),"click",this.closeButtonHandler);
a10.event.addListener(window,"resize",this.windowResizedHandler);
a10.event.addListener(window,"scroll",this.windowScrolledHandler);
a10.event.addListener(document,"click",this.clickHandler);
a10.element.show(this.id);
this.afterSwap();
var B=Math.floor(($("videoUI_rollover").offsetWidth-28)/13);
var L=(K.length>B)?K.substring(0,B)+"...":K;
$("videoUI_dialogTitle").innerHTML=L;
},afterSwap:function(){if(a10.browser.isIE6()&&this.cover){this.cover.hide();
}if(a10.browser.isIE6()&&this.width){$("videoUI_dialog").style.width=this.width+"px";
}this.centerDialog(true);
this.updateLightBoxCoverSize();
a10.element.show("videoUI_lightboxCover");
a10.element.show("videoUI_lightbox");
$("videoUI_lightboxCover").style.zIndex=4000;
$("videoUI_lightbox").style.zIndex=4001;
if(a10.browser.isIE6()){if(!this.cover){this.cover=new a10.IFrameCover("videoUI_dialog");
}this.cover.show();
}if(this.options.focusOn){var A=a10.form.getElements(this.options.focusOn)[0];
try{A.focus();
}catch(B){}}},hide:function(){if(this.options&&this.options.onClose&&!this.options.onClose()){return ;
}var A=$("videoUI_dialog").firstChild;
a10.element.hide(A);
if(A){document.body.appendChild(A);
}a10.event.removeListener($("videoUI_dialogCloseButton"),"click",this.closeButtonHandler);
a10.event.removeListener(window,"resize",this.windowResizedHandler);
a10.event.removeListener(window,"scroll",this.windowScrolledHandler);
a10.event.removeListener(document,"click",this.clickHandler);
$("videoUI_dialog").style.width="";
if(a10.browser.isIE6()){this.cover.hide();
}a10.element.hide("videoUI_lightboxCover");
a10.element.hide("videoUI_lightbox");
if(this.options&&this.options.onAfterClose){this.options.onAfterClose();
}},centerDialog:function(A){var D=a10.browser.innerDimension();
var C=$("videoUI_lightbox");
if(C&&(C.style.display!="none"||A)){C.style.left=((D[0]/2)-(a10.element.getWidth(C)/2))+"px";
var B=(D[1]/2)-(a10.element.getHeight(C)/2);
if(a10.browser.isIE6()){B+=a10.util.scrollTop();
}if(B<0){B=0;
}C.style.top=B+"px";
if(a10.browser.isIE6()){if(this.cover){this.cover.reposition();
}}}},updateLightBoxCoverSize:function(){if(!a10.browser.isIE6()){return ;
}var H=$("videoUI_lightboxCover");
var G=$("leftRail");
var F=$("midRail");
var A=$("rightRail");
var E;
if(G){var B=G.offsetTop+G.offsetHeight;
var D=F.offsetTop+F.offsetHeight;
var C=A.offsetTop+A.offsetHeight;
E=B;
if(D>E){E=D;
}if(C>E){E=C;
}}else{E=document.body.offsetHeight;
}H.style.height=E+"px";
},windowResized:function(){this.updateLightBoxCoverSize();
this.centerDialog();
},windowScrolled:function(){if(a10.browser.isIE6()){this.centerDialog();
}}});
if(typeof dialogLoaded!="undefined"){dialogLoaded();
}
