/*       Source:  Local Cache                                                                 */
/*     Location:  rsrc:115284:nu_ll:/html/js/menubar.js.pkg.php:92                            */
/*      Machine:  10.16.139.110                                                               */
/*    Generated:  September 13th 2008 1:22:08 AM PDT                                          */
/*    HTTP Host:  static.ak.fbcdn.net                                                         */
/*       Locale:  nu_ll                                                                       */


function ads_fetch_admarket_ad(page,handler,error_handler){var data={'page':page};var r=new AsyncRequest().setURI('/ads/ajax/fetch_admarket_ad.php').setData(data).setHandler(handler).setErrorHandler(error_handler).send();}

function AdsFeedback(title,body,click_value,log_data,clicked_elem){this.title=title;this.body=body;this.click_value=click_value;this.log_data=log_data;var sponsor_div=$('ssponsor');var ad_divs=DOM.scry(sponsor_div,'div.admarket_ad');for(i=0;i<ad_divs.length;i++){if(is_descendent(clicked_elem,ad_divs[i])){this.ad_div=ad_divs[i];break;}}
return this;}
copy_properties(AdsFeedback.prototype,{_log:function(event,data){var params='type=usage'+'&params[]='+escapeURI(event)+'&params[]='+escapeURI(data?data:'')+'&';new AsyncSignal('/ads/ajax/tracking_log.php?'+params).send();},_disable_ad:function(data){var params='params='+escapeURI(data?data:'')+'&';new AsyncSignal('/ads/ajax/disable_ad.php?'+params).send();},show_dialog:function(){var log_and_cancel_btn={name:'cancel',label:tx('sh:cancel-button'),className:'inputaux'};var ads_dialog_feedback_handler=function(r){if(r==log_and_cancel_btn){var reason_value=0;var other_text='';var data=this.log_data+'|'+reason_value+'|'+other_text;this._log('ads_feedback',data);}else if(r==Dialog.OK){if(this.click_value==1){var reason_value=get_form_select_value($('like_select'));}else{var reason_value=get_form_select_value($('dislike_select'));}
var data=this.log_data+'|'+reason_value;var other_text_el=$('ads_feedback_form_other_text');data=data+'|'+other_text_el.value;this._log('ads_feedback',data);if(this.click_value==1){this._show_success();}else{this._disable_ad(data);this.cycle_ad();}}}.bind(this);new Dialog().setTitle(this.title).setBody(this.body).setButtons([Dialog.OK,log_and_cancel_btn]).setHandler(ads_dialog_feedback_handler).show();},cycle_ad:function(){var onResponse=function(asyncResponse){var payload=asyncResponse.getPayload();if(payload['html']){var new_ad_elem=DOM.createFromMarkup(payload['html'])[0];set_inner_html(this.ad_div,new_ad_elem.innerHTML);}else{hide(DOM.find(this.ad_div,'div.ads_feedback'));hide(DOM.find(this.ad_div,'div.next_ad_button'));}}.bind(this);var onError=function(asyncResponse){hide(DOM.find(this.ad_div,'div.ads_feedback'));hide(DOM.find(this.ad_div,'div.next_ad_button'));}.bind(this);var page=URI.getRequestURI().getPath();ads_fetch_admarket_ad(page,onResponse,onError);},_show_success:function(){hide(DOM.find(this.ad_div,'div.ads_feedback'));show(DOM.find(this.ad_div,'div.next_ad_button'));}});function ads_feedback_select_onchange(click_value){if(click_value==1){var selected_other=(get_form_select_value($('like_select'))==4);}else{var selected_other=(get_form_select_value($('dislike_select'))==7);}
if(selected_other){show($('ads_feedback_form_other_text'));}else{hide($('ads_feedback_form_other_text'));}}

function MenuBar(core_menu_id){this.core_menu_id=core_menu_id;this.core_menu=$(core_menu_id);this.menus=DOM.scry(this.core_menu,'div.fb_menu');this.timeout=250;}
copy_properties(MenuBar.prototype,{setTimeoutInterval:function(timeout){this.timeout=timeout;return this;},init:function(){var i;for(i=0;i<this.menus.length;i++){var menu=this.menus[i];var dropdown_id=menu.id+'_dropdown';if(ge(dropdown_id)){var menu_anchor=menu.firstChild.firstChild;var dropdown=$(dropdown_id);hover_menu(menu_anchor).registerHTMLMenu(dropdown_id).setPosition(dropmenu.ALIGN_LEFT).setTimeoutInterval(this.timeout).addHook('show',bind(this,'_onShowCallback',menu_anchor,dropdown)).addHook('hide',bind(this,'_onHideCallback',menu_anchor)).initialize();}}},_onShowCallback:function(clickTarget,menuElement){CSS.addClass(clickTarget,'hover');var scroller=window['ScrollArea']&&ScrollArea.getInnerInstance(menuElement);if(scroller){scroller.moveTo(0);}},_onHideCallback:function(clickTarget){CSS.removeClass(clickTarget,'hover');}});
if (window.Bootloader) { Bootloader.done(["js\/menubar.js.pkg.php"]); }