function OAS_RICH(position) {
if (position == 'Right3') {
document.write ('<iframe width=180 height=70 scrolling=yes marginheight=0 marginwidth=0 frameborder=0 src="www.vg.no_files/doubleclick.html"></iframe>');
}
if (position == 'Top3') {
document.write ('<!-- \n');
document.write ('Support: http://ads.vg.basefarm.net#OasDefault/aconto_capital_tb_030908#182772#aconto_gr.swf.html#b38ae#1168271945#125#S#Top3#www.vg.no/front##\n');
document.write ('--><script id="extFlashTop31" type="text/javascript" src="www.vg.no_files/TFSMflashobject.js"></script>\n');
document.write ('<SCRIPT Language="JavaScript">\n');
document.write ('<!--\n');
document.write ('var swflocation585256656 = "www.vg.no_files/5.swf";\n');
document.write ('var fallbacklocation585256656 = "www.vg.no_files/5.gif";\n');
document.write ('if(!document.body)\n');
document.write ('document.write("<html><body>");\n');
document.write ('OASd = document;\n');
document.write ('plug =(navigator.mimeTypes && navigator.mimeTypes["application/x-shockwave-flash"]) ? navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin : 0;\n');
document.write ('if(plug){plug = parseInt(plug.description.substring(plug.description.indexOf(".")-1)) >= 6;}\n');
document.write ('else if(navigator.userAgent && navigator.userAgent.indexOf("MSIE")>=0 \n');
document.write ('&&(navigator.userAgent.indexOf("Windows 95")>=0 || navigator.userAgent.indexOf("Windows 98")>=0 || navigator.userAgent.indexOf("Windows NT")>=0)){document.write("<SCRIPT LANGUAGE=VBScript\\');
document.write ('> \\');
document.write ('n");\n');
document.write ('document.write("on error resume next \\');
document.write ('n");\n');
document.write ('document.write("plug =(IsObject(CreateObject(\\');
document.write ('"ShockwaveFlash.ShockwaveFlash.6\\');
document.write ('")))\\');
document.write ('n");\n');
document.write ('document.write("</SCRIPT\\');
document.write ('> \\');
document.write ('n");}\n');
document.write ('\n');
document.write ('if(plug)\n');
document.write ('{\n');
document.write ('document.write("<div id=\\');
document.write ('"FinContentTop31\\');
document.write ('"></div>");\n');
document.write ('function loadFlashTop31(){\n');
document.write ('	if(navigator.userAgent.indexOf("MSIE") != -1 && navigator.userAgent.indexOf("Opera") == -1){\n');
document.write ('	\n');
document.write ('		if (extFlashTop31.readyState == "complete")\n');
document.write ('  		{\n');
document.write ('	   		FlashObject(""+swflocation585256656+"?clickTAG=http://ads.vg.basefarm.net/RealMedia/ads/click_lx.ads/www.vg.no/front/419846538/Top3/OasDefault/aconto_capital_tb_030908/aconto_gr.swf.html/64356563643031363438626538346630", "OAS_AD_Top3", "width=768 height=150", "", "clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" ,"6", "FinContentTop31");\n');
document.write ('			extFlashTop31.onreadystatechange = "";\n');
document.write ('		}\n');
document.write ('	\n');
document.write ('		extFlashTop31.onreadystatechange = loadFlashTop31;\n');
document.write ('	}\n');
document.write ('	else\n');
document.write ('	{\n');
document.write ('           OASfp=" Menu=FALSE swModifyReport=TRUE width=768 height=150 ";\n');
document.write ('           OASd.write("<object id=\\');
document.write ('"techsource_Top3\\');
document.write ('" classid=\\');
document.write ('"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\\');
document.write ('" codebase=\\');
document.write ('"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=3,0,0,0\\');
document.write ('""+OASfp+">");\n');
document.write ('           OASd.write("<param name=src value=\\');
document.write ('""+swflocation585256656+"\\');
document.write ('"><param name=quality value=autohigh><param name=loop value=true><param name=play value=true><param name=menu value=false><param name=wmode><param name=FlashVars value=\\');
document.write ('"clickTAG=http://ads.vg.basefarm.net/RealMedia/ads/click_lx.ads/www.vg.no/front/419846538/Top3/OasDefault/aconto_capital_tb_030908/aconto_gr.swf.html/64356563643031363438626538346630\\');
document.write ('">");\n');
document.write ('           OASd.write("<embed src=\\');
document.write ('""+swflocation585256656+"\\');
document.write ('""+OASfp+"pluginspage=\\');
document.write ('"http://www.macromedia.com/shockwave\\');
document.write ('" type=\\');
document.write ('"application/x-shockwave-flash\\');
document.write ('" width=768 height=150 PLAY=true LOOP=true QUALITY=autohigh FlashVars=\\');
document.write ('"clickTAG=http://ads.vg.basefarm.net/RealMedia/ads/click_lx.ads/www.vg.no/front/419846538/Top3/OasDefault/aconto_capital_tb_030908/aconto_gr.swf.html/64356563643031363438626538346630\\');
document.write ('">");\n');
document.write ('           OASd.write("</embed></object>");\n');
document.write ('        }\n');
document.write ('\n');
document.write ('}\n');
document.write ('	loadFlashTop31();\n');
document.write ('}\n');
document.write ('else\n');
document.write ('{\n');
document.write ('OASd.write("<a href=\\');
document.write ('"http://ads.vg.basefarm.net/RealMedia/ads/click_lx.ads/www.vg.no/front/419846538/Top3/OasDefault/aconto_capital_tb_030908/aconto_gr.swf.html/64356563643031363438626538346630\\');
document.write ('" target=\\');
document.write ('"_top\\');
document.write ('"><img src=\\');
document.write ('""+fallbacklocation585256656+"\\');
document.write ('" width=768 height=150 border=0 alt=\\');
document.write ('"\\');
document.write ('"></a>");}\n');
document.write ('if(!document.body)\n');
document.write ('document.write("</body></html>");\n');
document.write ('//-->\n');
document.write ('</SCRIPT>');
}
if (position == 'Bottom1') {
document.write ('<iframe width="468" height="400" scrolling="yes" marginheight="0" marginwidth="0" frameborder="0" name=257457021 id=603987601 src="www.vg.no_files/adtech1.html"></iframe>');
}
if (position == 'Bottom2') {
document.write ('<iframe width="468" height="400" scrolling="yes" marginheight="0" marginwidth="0" frameborder="0" name=1228156583 id=732228369 src="www.vg.no_files/adtech1.html"></iframe>');
}
if (position == 'x21') {
document.write ('<iframe width="180" height="120" scrolling="yes" marginheight="0" marginwidth="0" frameborder="0" name=1972458328 id=1405315419 src="www.vg.no_files/adtech1.html"></iframe>');
}
if (position == 'x22') {
document.write ('<!-- \n');
document.write ('Support: http://ads.vg.basefarm.net#OasDefault/ventelo_knapp_front_010108#181544#vg_08_08.swf.html#b38ae#1168271945#125#S#x22#www.vg.no/front##\n');
document.write ('--><script id="extFlashx221" type="text/javascript" src="www.vg.no_files/TFSMflashobject.js"></script>\n');
document.write ('<SCRIPT Language="JavaScript">\n');
document.write ('<!--\n');
document.write ('var swflocation1873355294 = "www.vg.no_files/vg_08_08.swf";\n');
document.write ('var fallbacklocation1873355294 = "www.vg.no_files/t.gif";\n');
document.write ('if(!document.body)\n');
document.write ('document.write("<html><body>");\n');
document.write ('OASd = document;\n');
document.write ('plug =(navigator.mimeTypes && navigator.mimeTypes["application/x-shockwave-flash"]) ? navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin : 0;\n');
document.write ('if(plug){plug = parseInt(plug.description.substring(plug.description.indexOf(".")-1)) >= 6;}\n');
document.write ('else if(navigator.userAgent && navigator.userAgent.indexOf("MSIE")>=0 \n');
document.write ('&&(navigator.userAgent.indexOf("Windows 95")>=0 || navigator.userAgent.indexOf("Windows 98")>=0 || navigator.userAgent.indexOf("Windows NT")>=0)){document.write("<SCRIPT LANGUAGE=VBScript\\');
document.write ('> \\');
document.write ('n");\n');
document.write ('document.write("on error resume next \\');
document.write ('n");\n');
document.write ('document.write("plug =(IsObject(CreateObject(\\');
document.write ('"ShockwaveFlash.ShockwaveFlash.6\\');
document.write ('")))\\');
document.write ('n");\n');
document.write ('document.write("</SCRIPT\\');
document.write ('> \\');
document.write ('n");}\n');
document.write ('\n');
document.write ('if(plug)\n');
document.write ('{\n');
document.write ('document.write("<div id=\\');
document.write ('"FinContentx221\\');
document.write ('"></div>");\n');
document.write ('function loadFlashx221(){\n');
document.write ('	if(navigator.userAgent.indexOf("MSIE") != -1 && navigator.userAgent.indexOf("Opera") == -1){\n');
document.write ('	\n');
document.write ('		if (extFlashx221.readyState == "complete")\n');
document.write ('  		{\n');
document.write ('	   		FlashObject(""+swflocation1873355294+"?clickTAG=http://ads.vg.basefarm.net/RealMedia/ads/click_lx.ads/www.vg.no/front/1897447996/x22/OasDefault/ventelo_knapp_front_010108/vg_08_08.swf.html/64356563643031363438626538346630", "OAS_AD_x22", "width=180 height=120", "", "clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" ,"6", "FinContentx221");\n');
document.write ('			extFlashx221.onreadystatechange = "";\n');
document.write ('		}\n');
document.write ('	\n');
document.write ('		extFlashx221.onreadystatechange = loadFlashx221;\n');
document.write ('	}\n');
document.write ('	else\n');
document.write ('	{\n');
document.write ('           OASfp=" Menu=FALSE swModifyReport=TRUE width=180 height=120 ";\n');
document.write ('           OASd.write("<object id=\\');
document.write ('"techsource_x22\\');
document.write ('" classid=\\');
document.write ('"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\\');
document.write ('" codebase=\\');
document.write ('"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=3,0,0,0\\');
document.write ('""+OASfp+">");\n');
document.write ('           OASd.write("<param name=src value=\\');
document.write ('""+swflocation1873355294+"\\');
document.write ('"><param name=quality value=autohigh><param name=loop value=true><param name=play value=true><param name=menu value=false><param name=wmode value=transparent><param name=FlashVars value=\\');
document.write ('"clickTAG=http://ads.vg.basefarm.net/RealMedia/ads/click_lx.ads/www.vg.no/front/1897447996/x22/OasDefault/ventelo_knapp_front_010108/vg_08_08.swf.html/64356563643031363438626538346630\\');
document.write ('">");\n');
document.write ('           OASd.write("<embed src=\\');
document.write ('""+swflocation1873355294+"\\');
document.write ('""+OASfp+"pluginspage=\\');
document.write ('"http://www.macromedia.com/shockwave\\');
document.write ('" type=\\');
document.write ('"application/x-shockwave-flash\\');
document.write ('" width=180 height=120 PLAY=true LOOP=true QUALITY=autohigh WMODE=transparent FlashVars=\\');
document.write ('"clickTAG=http://ads.vg.basefarm.net/RealMedia/ads/click_lx.ads/www.vg.no/front/1897447996/x22/OasDefault/ventelo_knapp_front_010108/vg_08_08.swf.html/64356563643031363438626538346630\\');
document.write ('">");\n');
document.write ('           OASd.write("</embed></object>");\n');
document.write ('        }\n');
document.write ('\n');
document.write ('}\n');
document.write ('	loadFlashx221();\n');
document.write ('}\n');
document.write ('else\n');
document.write ('{\n');
document.write ('OASd.write("<a href=\\');
document.write ('"http://ads.vg.basefarm.net/RealMedia/ads/click_lx.ads/www.vg.no/front/1897447996/x22/OasDefault/ventelo_knapp_front_010108/vg_08_08.swf.html/64356563643031363438626538346630\\');
document.write ('" target=\\');
document.write ('"_top\\');
document.write ('"><img src=\\');
document.write ('""+fallbacklocation1873355294+"\\');
document.write ('" width=1 height=1 border=0 alt=\\');
document.write ('"\\');
document.write ('"></a>");}\n');
document.write ('if(!document.body)\n');
document.write ('document.write("</body></html>");\n');
document.write ('//-->\n');
document.write ('</SCRIPT>');
}
if (position == 'x23') {
document.write ('<!-- \n');
document.write ('Support: http://ads.vg.basefarm.net#OasDefault/NGT_knapp_front_2008#181753#4869-vg-knapp-tilbud.swf.html#b38ae#1168271945#125#S#x23#www.vg.no/front##\n');
document.write ('--><script id="extFlashx231" type="text/javascript" src="www.vg.no_files/TFSMflashobject.js"></script>\n');
document.write ('<SCRIPT Language="JavaScript">\n');
document.write ('<!--\n');
document.write ('var swflocation997825264 = "www.vg.no_files/4869-vg-knapp-tilbud.swf";\n');
document.write ('var fallbacklocation997825264 = "www.vg.no_files/4869-vg-knapp-tilbud.gif";\n');
document.write ('if(!document.body)\n');
document.write ('document.write("<html><body>");\n');
document.write ('OASd = document;\n');
document.write ('plug =(navigator.mimeTypes && navigator.mimeTypes["application/x-shockwave-flash"]) ? navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin : 0;\n');
document.write ('if(plug){plug = parseInt(plug.description.substring(plug.description.indexOf(".")-1)) >= 6;}\n');
document.write ('else if(navigator.userAgent && navigator.userAgent.indexOf("MSIE")>=0 \n');
document.write ('&&(navigator.userAgent.indexOf("Windows 95")>=0 || navigator.userAgent.indexOf("Windows 98")>=0 || navigator.userAgent.indexOf("Windows NT")>=0)){document.write("<SCRIPT LANGUAGE=VBScript\\');
document.write ('> \\');
document.write ('n");\n');
document.write ('document.write("on error resume next \\');
document.write ('n");\n');
document.write ('document.write("plug =(IsObject(CreateObject(\\');
document.write ('"ShockwaveFlash.ShockwaveFlash.6\\');
document.write ('")))\\');
document.write ('n");\n');
document.write ('document.write("</SCRIPT\\');
document.write ('> \\');
document.write ('n");}\n');
document.write ('\n');
document.write ('if(plug)\n');
document.write ('{\n');
document.write ('document.write("<div id=\\');
document.write ('"FinContentx231\\');
document.write ('"></div>");\n');
document.write ('function loadFlashx231(){\n');
document.write ('	if(navigator.userAgent.indexOf("MSIE") != -1 && navigator.userAgent.indexOf("Opera") == -1){\n');
document.write ('	\n');
document.write ('		if (extFlashx231.readyState == "complete")\n');
document.write ('  		{\n');
document.write ('	   		FlashObject(""+swflocation997825264+"?clickTAG=http://ads.vg.basefarm.net/RealMedia/ads/click_lx.ads/www.vg.no/front/259900008/x23/OasDefault/NGT_knapp_front_2008/4869-vg-knapp-tilbud.swf.html/64356563643031363438626538346630", "OAS_AD_x23", "width=180 height=120", "", "clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" ,"6", "FinContentx231");\n');
document.write ('			extFlashx231.onreadystatechange = "";\n');
document.write ('		}\n');
document.write ('	\n');
document.write ('		extFlashx231.onreadystatechange = loadFlashx231;\n');
document.write ('	}\n');
document.write ('	else\n');
document.write ('	{\n');
document.write ('           OASfp=" Menu=FALSE swModifyReport=TRUE width=180 height=120 ";\n');
document.write ('           OASd.write("<object id=\\');
document.write ('"techsource_x23\\');
document.write ('" classid=\\');
document.write ('"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\\');
document.write ('" codebase=\\');
document.write ('"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=3,0,0,0\\');
document.write ('""+OASfp+">");\n');
document.write ('           OASd.write("<param name=src value=\\');
document.write ('""+swflocation997825264+"\\');
document.write ('"><param name=quality value=autohigh><param name=loop value=true><param name=play value=true><param name=menu value=false><param name=wmode value=transparent><param name=FlashVars value=\\');
document.write ('"clickTAG=http://ads.vg.basefarm.net/RealMedia/ads/click_lx.ads/www.vg.no/front/259900008/x23/OasDefault/NGT_knapp_front_2008/4869-vg-knapp-tilbud.swf.html/64356563643031363438626538346630\\');
document.write ('">");\n');
document.write ('           OASd.write("<embed src=\\');
document.write ('""+swflocation997825264+"\\');
document.write ('""+OASfp+"pluginspage=\\');
document.write ('"http://www.macromedia.com/shockwave\\');
document.write ('" type=\\');
document.write ('"application/x-shockwave-flash\\');
document.write ('" width=180 height=120 PLAY=true LOOP=true QUALITY=autohigh WMODE=transparent FlashVars=\\');
document.write ('"clickTAG=http://ads.vg.basefarm.net/RealMedia/ads/click_lx.ads/www.vg.no/front/259900008/x23/OasDefault/NGT_knapp_front_2008/4869-vg-knapp-tilbud.swf.html/64356563643031363438626538346630\\');
document.write ('">");\n');
document.write ('           OASd.write("</embed></object>");\n');
document.write ('        }\n');
document.write ('\n');
document.write ('}\n');
document.write ('	loadFlashx231();\n');
document.write ('}\n');
document.write ('else\n');
document.write ('{\n');
document.write ('OASd.write("<a href=\\');
document.write ('"http://ads.vg.basefarm.net/RealMedia/ads/click_lx.ads/www.vg.no/front/259900008/x23/OasDefault/NGT_knapp_front_2008/4869-vg-knapp-tilbud.swf.html/64356563643031363438626538346630\\');
document.write ('" target=\\');
document.write ('"_top\\');
document.write ('"><img src=\\');
document.write ('""+fallbacklocation997825264+"\\');
document.write ('" width=180 height=120 border=0 alt=\\');
document.write ('"\\');
document.write ('"></a>");}\n');
document.write ('if(!document.body)\n');
document.write ('document.write("</body></html>");\n');
document.write ('//-->\n');
document.write ('</SCRIPT>');
}
if (position == 'x07') {
document.write ('&nbsp;');
}
if (position == 'x09') {
document.write ('<!-- \n');
document.write ('Support: http://ads.vg.basefarm.net#OasDefault/bonnier_bob_x07_x09_030908#182924#180x650.swf.html#b38ae#1168271945#125#S#x09#www.vg.no/front##\n');
document.write ('--><script id="extFlashx091" type="text/javascript" src="www.vg.no_files/TFSMflashobject.js"></script>\n');
document.write ('<SCRIPT Language="JavaScript">\n');
document.write ('<!--\n');
document.write ('var swflocation1209922756 = "www.vg.no_files/180x650.swf";\n');
document.write ('var fallbacklocation1209922756 = "www.vg.no_files/180x650.gif";\n');
document.write ('if(!document.body)\n');
document.write ('document.write("<html><body>");\n');
document.write ('OASd = document;\n');
document.write ('plug =(navigator.mimeTypes && navigator.mimeTypes["application/x-shockwave-flash"]) ? navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin : 0;\n');
document.write ('if(plug){plug = parseInt(plug.description.substring(plug.description.indexOf(".")-1)) >= 6;}\n');
document.write ('else if(navigator.userAgent && navigator.userAgent.indexOf("MSIE")>=0 \n');
document.write ('&&(navigator.userAgent.indexOf("Windows 95")>=0 || navigator.userAgent.indexOf("Windows 98")>=0 || navigator.userAgent.indexOf("Windows NT")>=0)){document.write("<SCRIPT LANGUAGE=VBScript\\');
document.write ('> \\');
document.write ('n");\n');
document.write ('document.write("on error resume next \\');
document.write ('n");\n');
document.write ('document.write("plug =(IsObject(CreateObject(\\');
document.write ('"ShockwaveFlash.ShockwaveFlash.6\\');
document.write ('")))\\');
document.write ('n");\n');
document.write ('document.write("</SCRIPT\\');
document.write ('> \\');
document.write ('n");}\n');
document.write ('\n');
document.write ('if(plug)\n');
document.write ('{\n');
document.write ('document.write("<div id=\\');
document.write ('"FinContentx091\\');
document.write ('"></div>");\n');
document.write ('function loadFlashx091(){\n');
document.write ('	if(navigator.userAgent.indexOf("MSIE") != -1 && navigator.userAgent.indexOf("Opera") == -1){\n');
document.write ('	\n');
document.write ('		if (extFlashx091.readyState == "complete")\n');
document.write ('  		{\n');
document.write ('	   		FlashObject(""+swflocation1209922756+"?clickTAG=http://ads.vg.basefarm.net/RealMedia/ads/click_lx.ads/www.vg.no/front/1236499438/x09/OasDefault/bonnier_bob_x07_x09_030908/180x650.swf.html/64356563643031363438626538346630", "OAS_AD_x09", "width=180 height=650", "", "clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" ,"6", "FinContentx091");\n');
document.write ('			extFlashx091.onreadystatechange = "";\n');
document.write ('		}\n');
document.write ('	\n');
document.write ('		extFlashx091.onreadystatechange = loadFlashx091;\n');
document.write ('	}\n');
document.write ('	else\n');
document.write ('	{\n');
document.write ('           OASfp=" Menu=FALSE swModifyReport=TRUE width=180 height=650 ";\n');
document.write ('           OASd.write("<object id=\\');
document.write ('"techsource_x09\\');
document.write ('" classid=\\');
document.write ('"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\\');
document.write ('" codebase=\\');
document.write ('"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=3,0,0,0\\');
document.write ('""+OASfp+">");\n');
document.write ('           OASd.write("<param name=src value=\\');
document.write ('""+swflocation1209922756+"\\');
document.write ('"><param name=quality value=autohigh><param name=loop value=true><param name=play value=true><param name=menu value=false><param name=wmode value=transparent><param name=FlashVars value=\\');
document.write ('"clickTAG=http://ads.vg.basefarm.net/RealMedia/ads/click_lx.ads/www.vg.no/front/1236499438/x09/OasDefault/bonnier_bob_x07_x09_030908/180x650.swf.html/64356563643031363438626538346630\\');
document.write ('">");\n');
document.write ('           OASd.write("<embed src=\\');
document.write ('""+swflocation1209922756+"\\');
document.write ('""+OASfp+"pluginspage=\\');
document.write ('"http://www.macromedia.com/shockwave\\');
document.write ('" type=\\');
document.write ('"application/x-shockwave-flash\\');
document.write ('" width=180 height=650 PLAY=true LOOP=true QUALITY=autohigh WMODE=transparent FlashVars=\\');
document.write ('"clickTAG=http://ads.vg.basefarm.net/RealMedia/ads/click_lx.ads/www.vg.no/front/1236499438/x09/OasDefault/bonnier_bob_x07_x09_030908/180x650.swf.html/64356563643031363438626538346630\\');
document.write ('">");\n');
document.write ('           OASd.write("</embed></object>");\n');
document.write ('        }\n');
document.write ('\n');
document.write ('}\n');
document.write ('	loadFlashx091();\n');
document.write ('}\n');
document.write ('else\n');
document.write ('{\n');
document.write ('OASd.write("<a href=\\');
document.write ('"http://ads.vg.basefarm.net/RealMedia/ads/click_lx.ads/www.vg.no/front/1236499438/x09/OasDefault/bonnier_bob_x07_x09_030908/180x650.swf.html/64356563643031363438626538346630\\');
document.write ('" target=\\');
document.write ('"_blank\\');
document.write ('"><img src=\\');
document.write ('""+fallbacklocation1209922756+"\\');
document.write ('" width=180 height=650 border=0 alt=\\');
document.write ('"\\');
document.write ('"></a>");}\n');
document.write ('if(!document.body)\n');
document.write ('document.write("</body></html>");\n');
document.write ('//-->\n');
document.write ('</SCRIPT>');
}
if (position == 'x04') {
document.write ('<!-- \n');
document.write ('Support: http://ads.vg.basefarm.net#OasDefault/dentway_menyknapp2_sept_2008#182817#115x150_4_no.swf.html#b38ae#1168271945#125#S#x04#www.vg.no/front##\n');
document.write ('--><script id="extFlashx041" type="text/javascript" src="www.vg.no_files/TFSMflashobject.js"></script>\n');
document.write ('<SCRIPT Language="JavaScript">\n');
document.write ('<!--\n');
document.write ('var swflocation1951853530 = "www.vg.no_files/115x150_4_no.swf";\n');
document.write ('var fallbacklocation1951853530 = "www.vg.no_files/t.gif";\n');
document.write ('if(!document.body)\n');
document.write ('document.write("<html><body>");\n');
document.write ('OASd = document;\n');
document.write ('plug =(navigator.mimeTypes && navigator.mimeTypes["application/x-shockwave-flash"]) ? navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin : 0;\n');
document.write ('if(plug){plug = parseInt(plug.description.substring(plug.description.indexOf(".")-1)) >= 6;}\n');
document.write ('else if(navigator.userAgent && navigator.userAgent.indexOf("MSIE")>=0 \n');
document.write ('&&(navigator.userAgent.indexOf("Windows 95")>=0 || navigator.userAgent.indexOf("Windows 98")>=0 || navigator.userAgent.indexOf("Windows NT")>=0)){document.write("<SCRIPT LANGUAGE=VBScript\\');
document.write ('> \\');
document.write ('n");\n');
document.write ('document.write("on error resume next \\');
document.write ('n");\n');
document.write ('document.write("plug =(IsObject(CreateObject(\\');
document.write ('"ShockwaveFlash.ShockwaveFlash.6\\');
document.write ('")))\\');
document.write ('n");\n');
document.write ('document.write("</SCRIPT\\');
document.write ('> \\');
document.write ('n");}\n');
document.write ('\n');
document.write ('if(plug)\n');
document.write ('{\n');
document.write ('document.write("<div id=\\');
document.write ('"FinContentx041\\');
document.write ('"></div>");\n');
document.write ('function loadFlashx041(){\n');
document.write ('	if(navigator.userAgent.indexOf("MSIE") != -1 && navigator.userAgent.indexOf("Opera") == -1){\n');
document.write ('	\n');
document.write ('		if (extFlashx041.readyState == "complete")\n');
document.write ('  		{\n');
document.write ('	   		FlashObject(""+swflocation1951853530+"?clickTag=http://ads.vg.basefarm.net/RealMedia/ads/click_lx.ads/www.vg.no/front/106520981/x04/OasDefault/dentway_menyknapp2_sept_2008/115x150_4_no.swf.html/64356563643031363438626538346630", "OAS_AD_x04", "width=115 height=150", "", "clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" ,"6", "FinContentx041");\n');
document.write ('			extFlashx041.onreadystatechange = "";\n');
document.write ('		}\n');
document.write ('	\n');
document.write ('		extFlashx041.onreadystatechange = loadFlashx041;\n');
document.write ('	}\n');
document.write ('	else\n');
document.write ('	{\n');
document.write ('           OASfp=" Menu=FALSE swModifyReport=TRUE width=115 height=150 ";\n');
document.write ('           OASd.write("<object id=\\');
document.write ('"techsource_x04\\');
document.write ('" classid=\\');
document.write ('"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\\');
document.write ('" codebase=\\');
document.write ('"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=3,0,0,0\\');
document.write ('""+OASfp+">");\n');
document.write ('           OASd.write("<param name=src value=\\');
document.write ('""+swflocation1951853530+"\\');
document.write ('"><param name=quality value=autohigh><param name=loop value=true><param name=play value=true><param name=menu value=false><param name=wmode value=transparent><param name=FlashVars value=\\');
document.write ('"clickTag=http://ads.vg.basefarm.net/RealMedia/ads/click_lx.ads/www.vg.no/front/106520981/x04/OasDefault/dentway_menyknapp2_sept_2008/115x150_4_no.swf.html/64356563643031363438626538346630\\');
document.write ('">");\n');
document.write ('           OASd.write("<embed src=\\');
document.write ('""+swflocation1951853530+"\\');
document.write ('""+OASfp+"pluginspage=\\');
document.write ('"http://www.macromedia.com/shockwave\\');
document.write ('" type=\\');
document.write ('"application/x-shockwave-flash\\');
document.write ('" width=115 height=150 PLAY=true LOOP=true QUALITY=autohigh WMODE=transparent FlashVars=\\');
document.write ('"clickTag=http://ads.vg.basefarm.net/RealMedia/ads/click_lx.ads/www.vg.no/front/106520981/x04/OasDefault/dentway_menyknapp2_sept_2008/115x150_4_no.swf.html/64356563643031363438626538346630\\');
document.write ('">");\n');
document.write ('           OASd.write("</embed></object>");\n');
document.write ('        }\n');
document.write ('\n');
document.write ('}\n');
document.write ('	loadFlashx041();\n');
document.write ('}\n');
document.write ('else\n');
document.write ('{\n');
document.write ('OASd.write("<a href=\\');
document.write ('"http://ads.vg.basefarm.net/RealMedia/ads/click_lx.ads/www.vg.no/front/106520981/x04/OasDefault/dentway_menyknapp2_sept_2008/115x150_4_no.swf.html/64356563643031363438626538346630\\');
document.write ('" target=\\');
document.write ('"_blank\\');
document.write ('"><img src=\\');
document.write ('""+fallbacklocation1951853530+"\\');
document.write ('" width=1 height=1 border=0 alt=\\');
document.write ('"\\');
document.write ('"></a>");}\n');
document.write ('if(!document.body)\n');
document.write ('document.write("</body></html>");\n');
document.write ('//-->\n');
document.write ('</SCRIPT>');
}
if (position == 'x05') {
document.write ('<A HREF="http://ads.vg.basefarm.net/RealMedia/ads/click_lx.ads/www.vg.no/front/903344731/x05/default/empty.gif/64356563643031363438626538346630" target="_top"><IMG SRC="www.vg.no_files/empty.gif"  width="2" height="2" ALT="" border="0" BORDER="0"></A>');
}
if (position == 'x03') {
document.write ('<!-- \n');
document.write ('Support: http://ads.vg.basefarm.net#OasDefault/finn_menyknapp_2008#179505#115x150_pakkereiser.swf.html#b38ae#1168271945#125#S#x03#www.vg.no/front##\n');
document.write ('--><script id="extFlashx031" type="text/javascript" src="www.vg.no_files/TFSMflashobject.js"></script>\n');
document.write ('<SCRIPT Language="JavaScript">\n');
document.write ('<!--\n');
document.write ('var swflocation293967821 = "www.vg.no_files/115x150_pakkereiser3.swf";\n');
document.write ('var fallbacklocation293967821 = "www.vg.no_files/115x150_pakkereiser.jpg";\n');
document.write ('if(!document.body)\n');
document.write ('document.write("<html><body>");\n');
document.write ('OASd = document;\n');
document.write ('plug =(navigator.mimeTypes && navigator.mimeTypes["application/x-shockwave-flash"]) ? navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin : 0;\n');
document.write ('if(plug){plug = parseInt(plug.description.substring(plug.description.indexOf(".")-1)) >= 6;}\n');
document.write ('else if(navigator.userAgent && navigator.userAgent.indexOf("MSIE")>=0 \n');
document.write ('&&(navigator.userAgent.indexOf("Windows 95")>=0 || navigator.userAgent.indexOf("Windows 98")>=0 || navigator.userAgent.indexOf("Windows NT")>=0)){document.write("<SCRIPT LANGUAGE=VBScript\\');
document.write ('> \\');
document.write ('n");\n');
document.write ('document.write("on error resume next \\');
document.write ('n");\n');
document.write ('document.write("plug =(IsObject(CreateObject(\\');
document.write ('"ShockwaveFlash.ShockwaveFlash.6\\');
document.write ('")))\\');
document.write ('n");\n');
document.write ('document.write("</SCRIPT\\');
document.write ('> \\');
document.write ('n");}\n');
document.write ('\n');
document.write ('if(plug)\n');
document.write ('{\n');
document.write ('document.write("<div id=\\');
document.write ('"FinContentx031\\');
document.write ('"></div>");\n');
document.write ('function loadFlashx031(){\n');
document.write ('	if(navigator.userAgent.indexOf("MSIE") != -1 && navigator.userAgent.indexOf("Opera") == -1){\n');
document.write ('	\n');
document.write ('		if (extFlashx031.readyState == "complete")\n');
document.write ('  		{\n');
document.write ('	   		FlashObject(""+swflocation293967821+"?clickTAG=http://ads.vg.basefarm.net/RealMedia/ads/click_lx.ads/www.vg.no/front/1634569197/x03/OasDefault/finn_menyknapp_2008/115x150_pakkereiser.swf.html/64356563643031363438626538346630?http%3A%2F%2Fwww.finn.no%2Ffinn%2Ftravel%2Fprepackage%2Fresult%3FsiteId%3D1%26channelId%3D1%26searchKey%3DSEARCH_ID_TRAVEL_PREPACKAGE%26WT.mc_id%3DVG_115x150_pakkereiser&clickTAG1=http://ads.vg.basefarm.net/RealMedia/ads/click_lx.ads/www.vg.no/front/1634569197/x03/OasDefault/finn_menyknapp_2008/115x150_pakkereiser.swf.html/64356563643031363438626538346630?http%3A%2F%2Fwww.finn.no%2Freise%3FWT.mc_id%3DVG_115x150_pakkereiser%20", "OAS_AD_x03", "width=115 height=150", "", "clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" ,"6", "FinContentx031");\n');
document.write ('			extFlashx031.onreadystatechange = "";\n');
document.write ('		}\n');
document.write ('	\n');
document.write ('		extFlashx031.onreadystatechange = loadFlashx031;\n');
document.write ('	}\n');
document.write ('	else\n');
document.write ('	{\n');
document.write ('           OASfp=" Menu=FALSE swModifyReport=TRUE width=115 height=150 ";\n');
document.write ('           OASd.write("<object id=\\');
document.write ('"techsource_x03\\');
document.write ('" classid=\\');
document.write ('"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\\');
document.write ('" codebase=\\');
document.write ('"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=3,0,0,0\\');
document.write ('""+OASfp+">");\n');
document.write ('           OASd.write("<param name=src value=\\');
document.write ('""+swflocation293967821+"\\');
document.write ('"><param name=quality value=autohigh><param name=loop value=true><param name=play value=true><param name=menu value=false><param name=wmode value=transparent><param name=FlashVars value=\\');
document.write ('"clickTAG=http://ads.vg.basefarm.net/RealMedia/ads/click_lx.ads/www.vg.no/front/1634569197/x03/OasDefault/finn_menyknapp_2008/115x150_pakkereiser.swf.html/64356563643031363438626538346630?http%3A%2F%2Fwww.finn.no%2Ffinn%2Ftravel%2Fprepackage%2Fresult%3FsiteId%3D1%26channelId%3D1%26searchKey%3DSEARCH_ID_TRAVEL_PREPACKAGE%26WT.mc_id%3DVG_115x150_pakkereiser&clickTAG1=http://ads.vg.basefarm.net/RealMedia/ads/click_lx.ads/www.vg.no/front/1634569197/x03/OasDefault/finn_menyknapp_2008/115x150_pakkereiser.swf.html/64356563643031363438626538346630?http%3A%2F%2Fwww.finn.no%2Freise%3FWT.mc_id%3DVG_115x150_pakkereiser%20\\');
document.write ('">");\n');
document.write ('           OASd.write("<embed src=\\');
document.write ('""+swflocation293967821+"\\');
document.write ('""+OASfp+"pluginspage=\\');
document.write ('"http://www.macromedia.com/shockwave\\');
document.write ('" type=\\');
document.write ('"application/x-shockwave-flash\\');
document.write ('" width=115 height=150 PLAY=true LOOP=true QUALITY=autohigh WMODE=transparent FlashVars=\\');
document.write ('"clickTAG=http://ads.vg.basefarm.net/RealMedia/ads/click_lx.ads/www.vg.no/front/1634569197/x03/OasDefault/finn_menyknapp_2008/115x150_pakkereiser.swf.html/64356563643031363438626538346630?http%3A%2F%2Fwww.finn.no%2Ffinn%2Ftravel%2Fprepackage%2Fresult%3FsiteId%3D1%26channelId%3D1%26searchKey%3DSEARCH_ID_TRAVEL_PREPACKAGE%26WT.mc_id%3DVG_115x150_pakkereiser&clickTAG1=http://ads.vg.basefarm.net/RealMedia/ads/click_lx.ads/www.vg.no/front/1634569197/x03/OasDefault/finn_menyknapp_2008/115x150_pakkereiser.swf.html/64356563643031363438626538346630?http%3A%2F%2Fwww.finn.no%2Freise%3FWT.mc_id%3DVG_115x150_pakkereiser%20\\');
document.write ('">");\n');
document.write ('           OASd.write("</embed></object>");\n');
document.write ('        }\n');
document.write ('\n');
document.write ('}\n');
document.write ('	loadFlashx031();\n');
document.write ('}\n');
document.write ('else\n');
document.write ('{\n');
document.write ('OASd.write("<a href=\\');
document.write ('"http://ads.vg.basefarm.net/RealMedia/ads/click_lx.ads/www.vg.no/front/1634569197/x03/OasDefault/finn_menyknapp_2008/115x150_pakkereiser.swf.html/64356563643031363438626538346630\\');
document.write ('" target=\\');
document.write ('"_top\\');
document.write ('"><img src=\\');
document.write ('""+fallbacklocation293967821+"\\');
document.write ('" width=115 height=150 border=0 alt=\\');
document.write ('"\\');
document.write ('"></a>");}\n');
document.write ('if(!document.body)\n');
document.write ('document.write("</body></html>");\n');
document.write ('//-->\n');
document.write ('</SCRIPT>');
}
}
