var zIrr=new Array("altmedicine", "Cathy Wong", "Alternative Medicine", 
"architecture", "Jackie Craven", "Architecture", 
"atlanta", "Joy Johnston", "Atlanta, GA", 
"babyparenting", "Stephanie Brown", "Parenting: Babies & Toddlers", 
"baking", "Carroll Pellegrinelli", "Desserts / Baking", 
"banking", "Justin Pritchard", "Banking / Loans", 
"bbq", "Derrick Riches", "Barbecues & Grilling", 
"beadwork", "Paula S. Morgan", "Beadwork", 
"beer", "Bryce Eddings", "Beer", 
"bodybuilding", "Hugo Rivera", "Bodybuilding", 
"boxing", "Andrew Eisele", "Boxing", 
"camping", "David Sweet", "Camping", 
"careerplanning", "Dawn Rosenberg McKay", "Career Planning", 
"cars", "Aaron Gold", "Cars", 
"casinogambling", "Bill Burton", "Casino Gambling", 
"cats", "Franny Syufy", "Cats", 
"childcare", "Robin McClure", "Child Care", 
"christianity", "Mary Fairchild", "Christianity - General", 
"classicalmusic", "Aaron Green", "Classical Music", 
"crime", "Charles Montaldo", "Crime / Punishment", 
"cruises", "Linda Garrison", "Cruises", 
"entertaining", "Donna Pilato", "Entertaining", 
"ergonomics", "Chris Adams", "Ergonomics", 
"fictionwriting", "Ginny Wiehardt", "Fiction Writing", 
"figureskating", "Jo Ann Schneider Farris", "Figure Skating", 
"fishing", "Ronnie Garrison", "Freshwater Fishing", 
"forestry", "Steve Nix", "Forestry", 
"french", "Laura K. Lawless", "French Language", 
"gardening", "Marie Iannotti", "Gardening", 
"geography", "Matt Rosenberg", "Geography", 
"geology", "Andrew Alden", "Geology", 
"gocaribbean", "Robert Curley", "Caribbean for Visitors", 
"gochicago", "Prescott Carlson", "Chicago for Visitors", 
"goeasteurope", "Kerry Kubilius", "Eastern Europe for Visitors", 
"gogermany", "Michele Hartley", "Germany for Visitors", 
"gohawaii", "John Fischer", "Hawaii / South Pacific for Visitors", 
"gonewengland", "Kim Knox Beckius", "New England for Visitors", 
"gonyc", "Heather Cross", "New York City for Visitors", 
"goscandinavia", "Terri Mapes", "Scandinavia for Visitors", 
"gosw", "Elizabeth Mitchell", "Southwestern United States for Visitors", 
"gourmetfood", "Brett Moore", "Gourmet Food", 
"greekfood", "Nancy Gaifyllia", "Greek Food", 
"hartford", "Kim Knox Beckius", "Hartford, CT", 
"healing", "Phylameana lila Desy", "Holistic Healing", 
"heavymetal", "Chad Bowar", "Heavy Metal", 
"homebuying", "Elizabeth Weintraub", "Home Buying / Selling", 
"homerepair", "Bob Formisano", "Home Repair", 
"homeworktips", "Grace Fleming", "Homework / Study Tips", 
"horses", "Katherine Blocksdorf", "Horses", 
"hotels", "Charlyn Keating Chisholm", "Hotels / Resorts / Inns", 
"housekeeping", "Sarah Aguirre", "Housekeeping", 
"humor", "Mike Durrett", "Humor", 
"huntsville", "Jean Brandau", "Huntsville", 
"interiordec", "Coral Nafie", "Interior Decorating", 
"jewelry", "Carly Wickell", "Jewelry / Accessories", 
"jewelrymaking", "Tammy Powley", "Jewelry Making", 
"jobsearch", "Alison Doyle", "Job Searching", 
"learningdisabilities", "Ann Logsdon", "Learning Disabilities", 
"longisland", "Dawn Rosenberg McKay", "Long Island", 
"memphis", "Teresa R. Simpson", "Memphis", 
"mexicanfood", "Chelsie Kenyon", "Mexican Cuisine", 
"moving", "Diane Schmidt", "Moving", 
"nutrition", "Shereen Jegtvig", "Nutrition", 
"paranormal", "Stephen Wagner", "Paranormal Phenomena", 
"personalweb", "Linda Roeder", "Personal Web Pages", 
"phoenix", "Judy Hedding", "Phoenix, AZ", 
"pilates", "Marguerite Ogle", "Pilates", 
"pregnancy", "Robin Elise Weiss, LCCE", "Pregnancy & Childbirth", 
"presentationsoft", "Wendy Russell", "Presentation Software", 
"privateschool", "Robert Kennedy", "Private Schools", 
"quilting", "Janet Wickell", "Quilting", 
"sandiego", "Inigo Figuracion", "San Diego, CA", 
"seniorliving", "Sharon O&#39;Brien", "Senior Living", 
"singleparents", "Jennifer Wolf", "Single Parents", 
"skateboard", "Steve Cave", "Skateboarding", 
"southernfood", "Diana Rattray", "Southern U.S. Cuisine", 
"spas", "Anitra Brown", "Spas", 
"specialchildren", "Terri Mauro", "Parenting Special Needs", 
"stress", "Elizabeth Scott, M.S.", "Stress Management", 
"suvs", "Jason Fogelson", "SUVs", 
"terrorism", "Amy Zalman, Ph.D.", "Terrorism Issues", 
"themeparks", "Arthur Levine", "Theme Parks", 
"top40", "Bill Lamb", "Top 40 / Pop", 
"travelwithkids", "Teresa Plowright", "Travel with Kids", 
"urbanlegends", "David Emery", "Urban Legends and Folklore", 
"walking", "Wendy Bumgardner", "Walking", 
"weather", "Rachelle Oblack", "Weather", 
"webdesign", "Jennifer Kyrnin", "Web Design / HTML", 
"weddings", "Nina Callaway", "Weddings", 
"wordprocessing", "James Marshall", "Word Processing", 
"worldfilm", "Jurgen Fauth & Marcy Dermansky", "World / Independent Film", 
"yoga", "Ann Pizer", "Yoga" 
);
function zr(m){return Math.floor(Math.random()*99999)%m}
l=zIrr.length,r=Math.floor(l/3),s=zr(r)*3,i=s;
